// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as data_models$0 from "../../models/data_models/models.js";

export class Info {
    "id": string;
    "session_id": number;
    "message_id"?: number | null;
    "tool_call_id"?: string;
    "title": string;
    "command": string;
    "args": string;
    "cwd": string;
    "status": string;
    "visible": boolean;
    "pid": number;
    "exit_code"?: number | null;
    "current_cursor": number;

    /** Creates a new Info instance. */
    constructor($$source: Partial<Info> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("session_id" in $$source)) {
            this["session_id"] = 0;
        }
        if (!("title" in $$source)) {
            this["title"] = "";
        }
        if (!("command" in $$source)) {
            this["command"] = "";
        }
        if (!("args" in $$source)) {
            this["args"] = "";
        }
        if (!("cwd" in $$source)) {
            this["cwd"] = "";
        }
        if (!("status" in $$source)) {
            this["status"] = "";
        }
        if (!("visible" in $$source)) {
            this["visible"] = false;
        }
        if (!("pid" in $$source)) {
            this["pid"] = 0;
        }
        if (!("current_cursor" in $$source)) {
            this["current_cursor"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Info instance from a string or object.
     */
    static createFrom($$source: any = {}): Info {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Info($$parsedSource as Partial<Info>);
    }
}

export const TerminalOutputChunk = data_models$0.TerminalOutputChunk;
export type TerminalOutputChunk = data_models$0.TerminalOutputChunk;
