// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class CloseAddMemoryInput {

    /** Creates a new CloseAddMemoryInput instance. */
    constructor($$source: Partial<CloseAddMemoryInput> = {}) {

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CloseAddMemoryInput instance from a string or object.
     */
    static createFrom($$source: any = {}): CloseAddMemoryInput {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new CloseAddMemoryInput($$parsedSource as Partial<CloseAddMemoryInput>);
    }
}

export class CloseAddMemoryOutput {

    /** Creates a new CloseAddMemoryOutput instance. */
    constructor($$source: Partial<CloseAddMemoryOutput> = {}) {

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CloseAddMemoryOutput instance from a string or object.
     */
    static createFrom($$source: any = {}): CloseAddMemoryOutput {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new CloseAddMemoryOutput($$parsedSource as Partial<CloseAddMemoryOutput>);
    }
}

export class CloseAddProviderInput {

    /** Creates a new CloseAddProviderInput instance. */
    constructor($$source: Partial<CloseAddProviderInput> = {}) {

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CloseAddProviderInput instance from a string or object.
     */
    static createFrom($$source: any = {}): CloseAddProviderInput {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new CloseAddProviderInput($$parsedSource as Partial<CloseAddProviderInput>);
    }
}

export class CloseAddProviderOutput {

    /** Creates a new CloseAddProviderOutput instance. */
    constructor($$source: Partial<CloseAddProviderOutput> = {}) {

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CloseAddProviderOutput instance from a string or object.
     */
    static createFrom($$source: any = {}): CloseAddProviderOutput {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new CloseAddProviderOutput($$parsedSource as Partial<CloseAddProviderOutput>);
    }
}

export class CloseAddSkillInput {

    /** Creates a new CloseAddSkillInput instance. */
    constructor($$source: Partial<CloseAddSkillInput> = {}) {

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CloseAddSkillInput instance from a string or object.
     */
    static createFrom($$source: any = {}): CloseAddSkillInput {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new CloseAddSkillInput($$parsedSource as Partial<CloseAddSkillInput>);
    }
}

export class CloseAddSkillOutput {

    /** Creates a new CloseAddSkillOutput instance. */
    constructor($$source: Partial<CloseAddSkillOutput> = {}) {

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CloseAddSkillOutput instance from a string or object.
     */
    static createFrom($$source: any = {}): CloseAddSkillOutput {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new CloseAddSkillOutput($$parsedSource as Partial<CloseAddSkillOutput>);
    }
}

export class OpenAddMemoryInput {

    /** Creates a new OpenAddMemoryInput instance. */
    constructor($$source: Partial<OpenAddMemoryInput> = {}) {

        Object.assign(this, $$source);
    }

    /**
     * Creates a new OpenAddMemoryInput instance from a string or object.
     */
    static createFrom($$source: any = {}): OpenAddMemoryInput {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new OpenAddMemoryInput($$parsedSource as Partial<OpenAddMemoryInput>);
    }
}

export class OpenAddMemoryOutput {

    /** Creates a new OpenAddMemoryOutput instance. */
    constructor($$source: Partial<OpenAddMemoryOutput> = {}) {

        Object.assign(this, $$source);
    }

    /**
     * Creates a new OpenAddMemoryOutput instance from a string or object.
     */
    static createFrom($$source: any = {}): OpenAddMemoryOutput {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new OpenAddMemoryOutput($$parsedSource as Partial<OpenAddMemoryOutput>);
    }
}

export class OpenAddProviderInput {

    /** Creates a new OpenAddProviderInput instance. */
    constructor($$source: Partial<OpenAddProviderInput> = {}) {

        Object.assign(this, $$source);
    }

    /**
     * Creates a new OpenAddProviderInput instance from a string or object.
     */
    static createFrom($$source: any = {}): OpenAddProviderInput {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new OpenAddProviderInput($$parsedSource as Partial<OpenAddProviderInput>);
    }
}

export class OpenAddProviderOutput {

    /** Creates a new OpenAddProviderOutput instance. */
    constructor($$source: Partial<OpenAddProviderOutput> = {}) {

        Object.assign(this, $$source);
    }

    /**
     * Creates a new OpenAddProviderOutput instance from a string or object.
     */
    static createFrom($$source: any = {}): OpenAddProviderOutput {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new OpenAddProviderOutput($$parsedSource as Partial<OpenAddProviderOutput>);
    }
}

export class OpenAddSkillInput {

    /** Creates a new OpenAddSkillInput instance. */
    constructor($$source: Partial<OpenAddSkillInput> = {}) {

        Object.assign(this, $$source);
    }

    /**
     * Creates a new OpenAddSkillInput instance from a string or object.
     */
    static createFrom($$source: any = {}): OpenAddSkillInput {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new OpenAddSkillInput($$parsedSource as Partial<OpenAddSkillInput>);
    }
}

export class OpenAddSkillOutput {

    /** Creates a new OpenAddSkillOutput instance. */
    constructor($$source: Partial<OpenAddSkillOutput> = {}) {

        Object.assign(this, $$source);
    }

    /**
     * Creates a new OpenAddSkillOutput instance from a string or object.
     */
    static createFrom($$source: any = {}): OpenAddSkillOutput {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new OpenAddSkillOutput($$parsedSource as Partial<OpenAddSkillOutput>);
    }
}

export class OpenOnboardingInput {

    /** Creates a new OpenOnboardingInput instance. */
    constructor($$source: Partial<OpenOnboardingInput> = {}) {

        Object.assign(this, $$source);
    }

    /**
     * Creates a new OpenOnboardingInput instance from a string or object.
     */
    static createFrom($$source: any = {}): OpenOnboardingInput {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new OpenOnboardingInput($$parsedSource as Partial<OpenOnboardingInput>);
    }
}

export class OpenOnboardingOutput {

    /** Creates a new OpenOnboardingOutput instance. */
    constructor($$source: Partial<OpenOnboardingOutput> = {}) {

        Object.assign(this, $$source);
    }

    /**
     * Creates a new OpenOnboardingOutput instance from a string or object.
     */
    static createFrom($$source: any = {}): OpenOnboardingOutput {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new OpenOnboardingOutput($$parsedSource as Partial<OpenOnboardingOutput>);
    }
}

export class OpenSettingsInput {
    "tab": string;

    /** Creates a new OpenSettingsInput instance. */
    constructor($$source: Partial<OpenSettingsInput> = {}) {
        if (!("tab" in $$source)) {
            this["tab"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new OpenSettingsInput instance from a string or object.
     */
    static createFrom($$source: any = {}): OpenSettingsInput {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new OpenSettingsInput($$parsedSource as Partial<OpenSettingsInput>);
    }
}

export class OpenSettingsOutput {

    /** Creates a new OpenSettingsOutput instance. */
    constructor($$source: Partial<OpenSettingsOutput> = {}) {

        Object.assign(this, $$source);
    }

    /**
     * Creates a new OpenSettingsOutput instance from a string or object.
     */
    static createFrom($$source: any = {}): OpenSettingsOutput {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new OpenSettingsOutput($$parsedSource as Partial<OpenSettingsOutput>);
    }
}
