// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class CancelDownloadInput {

    /** Creates a new CancelDownloadInput instance. */
    constructor($$source: Partial<CancelDownloadInput> = {}) {

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CancelDownloadInput instance from a string or object.
     */
    static createFrom($$source: any = {}): CancelDownloadInput {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new CancelDownloadInput($$parsedSource as Partial<CancelDownloadInput>);
    }
}

export class CancelDownloadOutput {

    /** Creates a new CancelDownloadOutput instance. */
    constructor($$source: Partial<CancelDownloadOutput> = {}) {

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CancelDownloadOutput instance from a string or object.
     */
    static createFrom($$source: any = {}): CancelDownloadOutput {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new CancelDownloadOutput($$parsedSource as Partial<CancelDownloadOutput>);
    }
}

export class DownloadNodeInput {

    /** Creates a new DownloadNodeInput instance. */
    constructor($$source: Partial<DownloadNodeInput> = {}) {

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DownloadNodeInput instance from a string or object.
     */
    static createFrom($$source: any = {}): DownloadNodeInput {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new DownloadNodeInput($$parsedSource as Partial<DownloadNodeInput>);
    }
}

export class DownloadNodeOutput {

    /** Creates a new DownloadNodeOutput instance. */
    constructor($$source: Partial<DownloadNodeOutput> = {}) {

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DownloadNodeOutput instance from a string or object.
     */
    static createFrom($$source: any = {}): DownloadNodeOutput {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new DownloadNodeOutput($$parsedSource as Partial<DownloadNodeOutput>);
    }
}

export class GetStatusInput {

    /** Creates a new GetStatusInput instance. */
    constructor($$source: Partial<GetStatusInput> = {}) {

        Object.assign(this, $$source);
    }

    /**
     * Creates a new GetStatusInput instance from a string or object.
     */
    static createFrom($$source: any = {}): GetStatusInput {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new GetStatusInput($$parsedSource as Partial<GetStatusInput>);
    }
}

export class GetStatusOutput {
    "state": string;
    "version": string;
    "install_dir": string;
    "node_path": string;
    "npm_path": string;
    "error_msg": string;

    /** Creates a new GetStatusOutput instance. */
    constructor($$source: Partial<GetStatusOutput> = {}) {
        if (!("state" in $$source)) {
            this["state"] = "";
        }
        if (!("version" in $$source)) {
            this["version"] = "";
        }
        if (!("install_dir" in $$source)) {
            this["install_dir"] = "";
        }
        if (!("node_path" in $$source)) {
            this["node_path"] = "";
        }
        if (!("npm_path" in $$source)) {
            this["npm_path"] = "";
        }
        if (!("error_msg" in $$source)) {
            this["error_msg"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new GetStatusOutput instance from a string or object.
     */
    static createFrom($$source: any = {}): GetStatusOutput {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new GetStatusOutput($$parsedSource as Partial<GetStatusOutput>);
    }
}

export class MarkDownloadLaterInput {

    /** Creates a new MarkDownloadLaterInput instance. */
    constructor($$source: Partial<MarkDownloadLaterInput> = {}) {

        Object.assign(this, $$source);
    }

    /**
     * Creates a new MarkDownloadLaterInput instance from a string or object.
     */
    static createFrom($$source: any = {}): MarkDownloadLaterInput {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new MarkDownloadLaterInput($$parsedSource as Partial<MarkDownloadLaterInput>);
    }
}

export class MarkDownloadLaterOutput {

    /** Creates a new MarkDownloadLaterOutput instance. */
    constructor($$source: Partial<MarkDownloadLaterOutput> = {}) {

        Object.assign(this, $$source);
    }

    /**
     * Creates a new MarkDownloadLaterOutput instance from a string or object.
     */
    static createFrom($$source: any = {}): MarkDownloadLaterOutput {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new MarkDownloadLaterOutput($$parsedSource as Partial<MarkDownloadLaterOutput>);
    }
}
