// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Notification exposes global notification CRUD and waiter coordination to Wails.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as notification_dto$0 from "./notification_dto/models.js";

/**
 * DismissNotification permanently removes a notification row.
 */
export function DismissNotification(input: notification_dto$0.DismissNotificationInput): $CancellablePromise<notification_dto$0.DismissNotificationOutput | null> {
    return $Call.ByID(4018102223, input).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * ListNotifications returns the current notification list ordered by creation time.
 */
export function ListNotifications(input: notification_dto$0.ListNotificationsInput): $CancellablePromise<notification_dto$0.ListNotificationsOutput | null> {
    return $Call.ByID(449301312, input).then(($result: any) => {
        return $$createType3($result);
    });
}

/**
 * Notify creates a notification record and broadcasts a created event.
 */
export function Notify(input: notification_dto$0.NotifyInput): $CancellablePromise<notification_dto$0.NotifyOutput | null> {
    return $Call.ByID(2070088381, input).then(($result: any) => {
        return $$createType5($result);
    });
}

/**
 * NotifyAttention creates a needs_attention notification and registers a waiter for user action.
 */
export function NotifyAttention(sessionID: number, title: string, message: string): $CancellablePromise<number> {
    return $Call.ByID(1932454753, sessionID, title, message);
}

/**
 * RejectNotification marks a notification resolved and wakes any waiter with a rejection error.
 */
export function RejectNotification(input: notification_dto$0.ResolveNotificationInput): $CancellablePromise<notification_dto$0.ResolveNotificationOutput | null> {
    return $Call.ByID(2011469280, input).then(($result: any) => {
        return $$createType7($result);
    });
}

/**
 * ResolveNotification marks a notification resolved, emits an event, and wakes waiters as success.
 */
export function ResolveNotification(input: notification_dto$0.ResolveNotificationInput): $CancellablePromise<notification_dto$0.ResolveNotificationOutput | null> {
    return $Call.ByID(386642831, input).then(($result: any) => {
        return $$createType7($result);
    });
}

/**
 * WaitForResolution blocks until the notification is resolved, rejected, dismissed, or times out.
 */
export function WaitForResolution(notificationID: number): $CancellablePromise<void> {
    return $Call.ByID(271049410, notificationID);
}

// Private type creation functions
const $$createType0 = notification_dto$0.DismissNotificationOutput.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = notification_dto$0.ListNotificationsOutput.createFrom;
const $$createType3 = $Create.Nullable($$createType2);
const $$createType4 = notification_dto$0.NotifyOutput.createFrom;
const $$createType5 = $Create.Nullable($$createType4);
const $$createType6 = notification_dto$0.ResolveNotificationOutput.createFrom;
const $$createType7 = $Create.Nullable($$createType6);
