// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as data_models$0 from "../../../models/data_models/models.js";

/**
 * CancelLoginCliInput terminates a running login session.
 */
export class CancelLoginCliInput {
    "id": string;

    /** Creates a new CancelLoginCliInput instance. */
    constructor($$source: Partial<CancelLoginCliInput> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CancelLoginCliInput instance from a string or object.
     */
    static createFrom($$source: any = {}): CancelLoginCliInput {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new CancelLoginCliInput($$parsedSource as Partial<CancelLoginCliInput>);
    }
}

export class DeleteExtensionInput {
    "id": string;

    /** Creates a new DeleteExtensionInput instance. */
    constructor($$source: Partial<DeleteExtensionInput> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DeleteExtensionInput instance from a string or object.
     */
    static createFrom($$source: any = {}): DeleteExtensionInput {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new DeleteExtensionInput($$parsedSource as Partial<DeleteExtensionInput>);
    }
}

export class DeleteExtensionOutput {

    /** Creates a new DeleteExtensionOutput instance. */
    constructor($$source: Partial<DeleteExtensionOutput> = {}) {

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DeleteExtensionOutput instance from a string or object.
     */
    static createFrom($$source: any = {}): DeleteExtensionOutput {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new DeleteExtensionOutput($$parsedSource as Partial<DeleteExtensionOutput>);
    }
}

/**
 * GenerateCliManifestInput identifies which CLI plugin to regenerate the manifest for.
 */
export class GenerateCliManifestInput {
    "id": string;

    /** Creates a new GenerateCliManifestInput instance. */
    constructor($$source: Partial<GenerateCliManifestInput> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new GenerateCliManifestInput instance from a string or object.
     */
    static createFrom($$source: any = {}): GenerateCliManifestInput {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new GenerateCliManifestInput($$parsedSource as Partial<GenerateCliManifestInput>);
    }
}

/**
 * GenerateCliManifestOutput returns the refreshed extension after a successful generation.
 */
export class GenerateCliManifestOutput {
    "extension": data_models$0.ExtensionItem;

    /** Creates a new GenerateCliManifestOutput instance. */
    constructor($$source: Partial<GenerateCliManifestOutput> = {}) {
        if (!("extension" in $$source)) {
            this["extension"] = (new data_models$0.ExtensionItem());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new GenerateCliManifestOutput instance from a string or object.
     */
    static createFrom($$source: any = {}): GenerateCliManifestOutput {
        const $$createField0_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("extension" in $$parsedSource) {
            $$parsedSource["extension"] = $$createField0_0($$parsedSource["extension"]);
        }
        return new GenerateCliManifestOutput($$parsedSource as Partial<GenerateCliManifestOutput>);
    }
}

export class GetExtensionDetailInput {
    "id": string;

    /** Creates a new GetExtensionDetailInput instance. */
    constructor($$source: Partial<GetExtensionDetailInput> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new GetExtensionDetailInput instance from a string or object.
     */
    static createFrom($$source: any = {}): GetExtensionDetailInput {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new GetExtensionDetailInput($$parsedSource as Partial<GetExtensionDetailInput>);
    }
}

export class GetExtensionDetailOutput {
    "extension": data_models$0.ExtensionItem;
    "config_text": string;

    /** Creates a new GetExtensionDetailOutput instance. */
    constructor($$source: Partial<GetExtensionDetailOutput> = {}) {
        if (!("extension" in $$source)) {
            this["extension"] = (new data_models$0.ExtensionItem());
        }
        if (!("config_text" in $$source)) {
            this["config_text"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new GetExtensionDetailOutput instance from a string or object.
     */
    static createFrom($$source: any = {}): GetExtensionDetailOutput {
        const $$createField0_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("extension" in $$parsedSource) {
            $$parsedSource["extension"] = $$createField0_0($$parsedSource["extension"]);
        }
        return new GetExtensionDetailOutput($$parsedSource as Partial<GetExtensionDetailOutput>);
    }
}

export class ImportExtensionInput {
    "kind": string;
    "path": string;

    /** Creates a new ImportExtensionInput instance. */
    constructor($$source: Partial<ImportExtensionInput> = {}) {
        if (!("kind" in $$source)) {
            this["kind"] = "";
        }
        if (!("path" in $$source)) {
            this["path"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ImportExtensionInput instance from a string or object.
     */
    static createFrom($$source: any = {}): ImportExtensionInput {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ImportExtensionInput($$parsedSource as Partial<ImportExtensionInput>);
    }
}

export class ImportExtensionOutput {
    "extension": data_models$0.ExtensionItem;

    /** Creates a new ImportExtensionOutput instance. */
    constructor($$source: Partial<ImportExtensionOutput> = {}) {
        if (!("extension" in $$source)) {
            this["extension"] = (new data_models$0.ExtensionItem());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ImportExtensionOutput instance from a string or object.
     */
    static createFrom($$source: any = {}): ImportExtensionOutput {
        const $$createField0_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("extension" in $$parsedSource) {
            $$parsedSource["extension"] = $$createField0_0($$parsedSource["extension"]);
        }
        return new ImportExtensionOutput($$parsedSource as Partial<ImportExtensionOutput>);
    }
}

/**
 * InstallCliFromNpmInput is the request to install a CLI plugin from a published npm package.
 */
export class InstallCliFromNpmInput {
    "npm_package": string;
    "name": string;

    /** Creates a new InstallCliFromNpmInput instance. */
    constructor($$source: Partial<InstallCliFromNpmInput> = {}) {
        if (!("npm_package" in $$source)) {
            this["npm_package"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new InstallCliFromNpmInput instance from a string or object.
     */
    static createFrom($$source: any = {}): InstallCliFromNpmInput {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new InstallCliFromNpmInput($$parsedSource as Partial<InstallCliFromNpmInput>);
    }
}

/**
 * InstallCliFromNpmOutput returns the persisted ExtensionItem after a successful install.
 */
export class InstallCliFromNpmOutput {
    "extension": data_models$0.ExtensionItem;

    /** Creates a new InstallCliFromNpmOutput instance. */
    constructor($$source: Partial<InstallCliFromNpmOutput> = {}) {
        if (!("extension" in $$source)) {
            this["extension"] = (new data_models$0.ExtensionItem());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new InstallCliFromNpmOutput instance from a string or object.
     */
    static createFrom($$source: any = {}): InstallCliFromNpmOutput {
        const $$createField0_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("extension" in $$parsedSource) {
            $$parsedSource["extension"] = $$createField0_0($$parsedSource["extension"]);
        }
        return new InstallCliFromNpmOutput($$parsedSource as Partial<InstallCliFromNpmOutput>);
    }
}

export class ListAvailableToolsInput {

    /** Creates a new ListAvailableToolsInput instance. */
    constructor($$source: Partial<ListAvailableToolsInput> = {}) {

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ListAvailableToolsInput instance from a string or object.
     */
    static createFrom($$source: any = {}): ListAvailableToolsInput {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ListAvailableToolsInput($$parsedSource as Partial<ListAvailableToolsInput>);
    }
}

export class ListAvailableToolsOutput {
    "tools": ToolItem[];

    /** Creates a new ListAvailableToolsOutput instance. */
    constructor($$source: Partial<ListAvailableToolsOutput> = {}) {
        if (!("tools" in $$source)) {
            this["tools"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ListAvailableToolsOutput instance from a string or object.
     */
    static createFrom($$source: any = {}): ListAvailableToolsOutput {
        const $$createField0_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("tools" in $$parsedSource) {
            $$parsedSource["tools"] = $$createField0_0($$parsedSource["tools"]);
        }
        return new ListAvailableToolsOutput($$parsedSource as Partial<ListAvailableToolsOutput>);
    }
}

export class ListExtensionsInput {

    /** Creates a new ListExtensionsInput instance. */
    constructor($$source: Partial<ListExtensionsInput> = {}) {

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ListExtensionsInput instance from a string or object.
     */
    static createFrom($$source: any = {}): ListExtensionsInput {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ListExtensionsInput($$parsedSource as Partial<ListExtensionsInput>);
    }
}

export class ListExtensionsOutput {
    "extensions": data_models$0.ExtensionItem[];

    /** Creates a new ListExtensionsOutput instance. */
    constructor($$source: Partial<ListExtensionsOutput> = {}) {
        if (!("extensions" in $$source)) {
            this["extensions"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ListExtensionsOutput instance from a string or object.
     */
    static createFrom($$source: any = {}): ListExtensionsOutput {
        const $$createField0_0 = $$createType3;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("extensions" in $$parsedSource) {
            $$parsedSource["extensions"] = $$createField0_0($$parsedSource["extensions"]);
        }
        return new ListExtensionsOutput($$parsedSource as Partial<ListExtensionsOutput>);
    }
}

/**
 * LoginCliInput identifies the CLI plugin to start a login session for.
 */
export class LoginCliInput {
    "id": string;

    /** Creates a new LoginCliInput instance. */
    constructor($$source: Partial<LoginCliInput> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new LoginCliInput instance from a string or object.
     */
    static createFrom($$source: any = {}): LoginCliInput {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new LoginCliInput($$parsedSource as Partial<LoginCliInput>);
    }
}

/**
 * LoginCliOutput is empty; actual output is delivered via "cli.login.output" and "cli.login.done" events.
 */
export class LoginCliOutput {

    /** Creates a new LoginCliOutput instance. */
    constructor($$source: Partial<LoginCliOutput> = {}) {

        Object.assign(this, $$source);
    }

    /**
     * Creates a new LoginCliOutput instance from a string or object.
     */
    static createFrom($$source: any = {}): LoginCliOutput {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new LoginCliOutput($$parsedSource as Partial<LoginCliOutput>);
    }
}

export class ReloadExtensionInput {
    "id": string;

    /** Creates a new ReloadExtensionInput instance. */
    constructor($$source: Partial<ReloadExtensionInput> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ReloadExtensionInput instance from a string or object.
     */
    static createFrom($$source: any = {}): ReloadExtensionInput {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ReloadExtensionInput($$parsedSource as Partial<ReloadExtensionInput>);
    }
}

export class ReloadExtensionOutput {
    "extension": data_models$0.ExtensionItem;

    /** Creates a new ReloadExtensionOutput instance. */
    constructor($$source: Partial<ReloadExtensionOutput> = {}) {
        if (!("extension" in $$source)) {
            this["extension"] = (new data_models$0.ExtensionItem());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ReloadExtensionOutput instance from a string or object.
     */
    static createFrom($$source: any = {}): ReloadExtensionOutput {
        const $$createField0_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("extension" in $$parsedSource) {
            $$parsedSource["extension"] = $$createField0_0($$parsedSource["extension"]);
        }
        return new ReloadExtensionOutput($$parsedSource as Partial<ReloadExtensionOutput>);
    }
}

/**
 * ResetCliDataInput identifies which CLI plugin's data directory to clear.
 */
export class ResetCliDataInput {
    "id": string;

    /** Creates a new ResetCliDataInput instance. */
    constructor($$source: Partial<ResetCliDataInput> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ResetCliDataInput instance from a string or object.
     */
    static createFrom($$source: any = {}): ResetCliDataInput {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ResetCliDataInput($$parsedSource as Partial<ResetCliDataInput>);
    }
}

/**
 * ResetCliDataOutput is empty; clients re-fetch the extension if they need updated state.
 */
export class ResetCliDataOutput {

    /** Creates a new ResetCliDataOutput instance. */
    constructor($$source: Partial<ResetCliDataOutput> = {}) {

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ResetCliDataOutput instance from a string or object.
     */
    static createFrom($$source: any = {}): ResetCliDataOutput {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ResetCliDataOutput($$parsedSource as Partial<ResetCliDataOutput>);
    }
}

/**
 * ResizeLoginCliInput resizes the PTY of a running login session.
 */
export class ResizeLoginCliInput {
    "id": string;
    "rows": number;
    "cols": number;

    /** Creates a new ResizeLoginCliInput instance. */
    constructor($$source: Partial<ResizeLoginCliInput> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("rows" in $$source)) {
            this["rows"] = 0;
        }
        if (!("cols" in $$source)) {
            this["cols"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ResizeLoginCliInput instance from a string or object.
     */
    static createFrom($$source: any = {}): ResizeLoginCliInput {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ResizeLoginCliInput($$parsedSource as Partial<ResizeLoginCliInput>);
    }
}

export class SaveExtensionConfigInput {
    "id": string;
    "config_text": string;

    /** Creates a new SaveExtensionConfigInput instance. */
    constructor($$source: Partial<SaveExtensionConfigInput> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("config_text" in $$source)) {
            this["config_text"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SaveExtensionConfigInput instance from a string or object.
     */
    static createFrom($$source: any = {}): SaveExtensionConfigInput {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SaveExtensionConfigInput($$parsedSource as Partial<SaveExtensionConfigInput>);
    }
}

export class SaveExtensionConfigOutput {
    "extension": data_models$0.ExtensionItem;

    /** Creates a new SaveExtensionConfigOutput instance. */
    constructor($$source: Partial<SaveExtensionConfigOutput> = {}) {
        if (!("extension" in $$source)) {
            this["extension"] = (new data_models$0.ExtensionItem());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SaveExtensionConfigOutput instance from a string or object.
     */
    static createFrom($$source: any = {}): SaveExtensionConfigOutput {
        const $$createField0_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("extension" in $$parsedSource) {
            $$parsedSource["extension"] = $$createField0_0($$parsedSource["extension"]);
        }
        return new SaveExtensionConfigOutput($$parsedSource as Partial<SaveExtensionConfigOutput>);
    }
}

/**
 * SendLoginStdinInput sends raw bytes to a running login session's stdin.
 */
export class SendLoginStdinInput {
    "id": string;
    "data": string;

    /** Creates a new SendLoginStdinInput instance. */
    constructor($$source: Partial<SendLoginStdinInput> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("data" in $$source)) {
            this["data"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SendLoginStdinInput instance from a string or object.
     */
    static createFrom($$source: any = {}): SendLoginStdinInput {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SendLoginStdinInput($$parsedSource as Partial<SendLoginStdinInput>);
    }
}

export class ToggleExtensionInput {
    "id": string;
    "enabled": boolean;

    /** Creates a new ToggleExtensionInput instance. */
    constructor($$source: Partial<ToggleExtensionInput> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("enabled" in $$source)) {
            this["enabled"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ToggleExtensionInput instance from a string or object.
     */
    static createFrom($$source: any = {}): ToggleExtensionInput {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ToggleExtensionInput($$parsedSource as Partial<ToggleExtensionInput>);
    }
}

export class ToggleExtensionOutput {
    "extension": data_models$0.ExtensionItem;

    /** Creates a new ToggleExtensionOutput instance. */
    constructor($$source: Partial<ToggleExtensionOutput> = {}) {
        if (!("extension" in $$source)) {
            this["extension"] = (new data_models$0.ExtensionItem());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ToggleExtensionOutput instance from a string or object.
     */
    static createFrom($$source: any = {}): ToggleExtensionOutput {
        const $$createField0_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("extension" in $$parsedSource) {
            $$parsedSource["extension"] = $$createField0_0($$parsedSource["extension"]);
        }
        return new ToggleExtensionOutput($$parsedSource as Partial<ToggleExtensionOutput>);
    }
}

export class ToolItem {
    "id": string;
    "name": string;
    "description": string;
    "category": string;

    /** Creates a new ToolItem instance. */
    constructor($$source: Partial<ToolItem> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("description" in $$source)) {
            this["description"] = "";
        }
        if (!("category" in $$source)) {
            this["category"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ToolItem instance from a string or object.
     */
    static createFrom($$source: any = {}): ToolItem {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ToolItem($$parsedSource as Partial<ToolItem>);
    }
}

/**
 * UpdateCliManifestInput carries the edited manifest JSON text for a specific CLI plugin.
 */
export class UpdateCliManifestInput {
    "id": string;
    "manifest_text": string;

    /** Creates a new UpdateCliManifestInput instance. */
    constructor($$source: Partial<UpdateCliManifestInput> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("manifest_text" in $$source)) {
            this["manifest_text"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new UpdateCliManifestInput instance from a string or object.
     */
    static createFrom($$source: any = {}): UpdateCliManifestInput {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new UpdateCliManifestInput($$parsedSource as Partial<UpdateCliManifestInput>);
    }
}

/**
 * UpdateCliManifestOutput returns the updated ExtensionItem after manifest validation + save.
 */
export class UpdateCliManifestOutput {
    "extension": data_models$0.ExtensionItem;

    /** Creates a new UpdateCliManifestOutput instance. */
    constructor($$source: Partial<UpdateCliManifestOutput> = {}) {
        if (!("extension" in $$source)) {
            this["extension"] = (new data_models$0.ExtensionItem());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new UpdateCliManifestOutput instance from a string or object.
     */
    static createFrom($$source: any = {}): UpdateCliManifestOutput {
        const $$createField0_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("extension" in $$parsedSource) {
            $$parsedSource["extension"] = $$createField0_0($$parsedSource["extension"]);
        }
        return new UpdateCliManifestOutput($$parsedSource as Partial<UpdateCliManifestOutput>);
    }
}

// Private type creation functions
const $$createType0 = data_models$0.ExtensionItem.createFrom;
const $$createType1 = ToolItem.createFrom;
const $$createType2 = $Create.Array($$createType1);
const $$createType3 = $Create.Array($$createType0);
