// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Terminal exposes interactive terminal operations to the frontend.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as terminal_dto$0 from "./terminal_dto/models.js";

/**
 * ListTerminals returns visible and persisted terminal sessions for a chat session.
 */
export function ListTerminals(input: terminal_dto$0.ListTerminalsInput): $CancellablePromise<terminal_dto$0.ListTerminalsOutput | null> {
    return $Call.ByID(2151253471, input).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * ReadTerminalOutput returns output chunks after the supplied byte cursor.
 */
export function ReadTerminalOutput(input: terminal_dto$0.ReadTerminalOutputInput): $CancellablePromise<terminal_dto$0.ReadTerminalOutputOutput | null> {
    return $Call.ByID(1407420907, input).then(($result: any) => {
        return $$createType3($result);
    });
}

/**
 * ResizeTerminal updates the PTY size to match the frontend terminal viewport.
 */
export function ResizeTerminal(input: terminal_dto$0.ResizeTerminalInput): $CancellablePromise<terminal_dto$0.ResizeTerminalOutput | null> {
    return $Call.ByID(4038674622, input).then(($result: any) => {
        return $$createType5($result);
    });
}

/**
 * WriteTerminalInput sends user keystrokes or pasted text to an active terminal.
 */
export function WriteTerminalInput(input: terminal_dto$0.WriteTerminalInputInput): $CancellablePromise<terminal_dto$0.WriteTerminalInputOutput | null> {
    return $Call.ByID(2552138663, input).then(($result: any) => {
        return $$createType7($result);
    });
}

// Private type creation functions
const $$createType0 = terminal_dto$0.ListTerminalsOutput.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = terminal_dto$0.ReadTerminalOutputOutput.createFrom;
const $$createType3 = $Create.Nullable($$createType2);
const $$createType4 = terminal_dto$0.ResizeTerminalOutput.createFrom;
const $$createType5 = $Create.Nullable($$createType4);
const $$createType6 = terminal_dto$0.WriteTerminalInputOutput.createFrom;
const $$createType7 = $Create.Nullable($$createType6);
