// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ChatList(arg1, arg2, arg3, arg4) {
  return window['go']['service']['Service']['ChatList'](arg1, arg2, arg3, arg4);
}

export function GetModels() {
  return window['go']['service']['Service']['GetModels']();
}

export function GetProviders() {
  return window['go']['service']['Service']['GetProviders']();
}

export function Startup(arg1) {
  return window['go']['service']['Service']['Startup'](arg1);
}
