// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {context} from '../models';
import {view_models} from '../models';
import {data_models} from '../models';

export function ChatList(arg1:context.Context,arg2:number,arg3:number,arg4:any):Promise<Array<view_models.Chat>>;

export function GetModels():Promise<Array<data_models.Model>>;

export function GetProviders():Promise<Array<data_models.Provider>>;

export function Startup(arg1:context.Context):Promise<void>;
