// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetModels() {
  return window['go']['service']['Service']['GetModels']();
}

export function Startup(arg1) {
  return window['go']['service']['Service']['Startup'](arg1);
}
