// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {view_models} from '../models';
import {schema} from '../models';
import {data_models} from '../models';
import {context} from '../models';
import {storage} from '../models';

export function ChatList(arg1:number,arg2:number,arg3:any,arg4:boolean):Promise<view_models.ChatList>;

export function ChatMessages(arg1:string,arg2:number,arg3:number):Promise<view_models.MessageList>;

export function Completions(arg1:string,arg2:string,arg3:schema.Message):Promise<view_models.Completions>;

export function DeleteChat(arg1:string):Promise<void>;

export function GetModels():Promise<Array<data_models.Model>>;

export function GetProviders():Promise<Array<data_models.Provider>>;

export function RenameChat(arg1:string,arg2:string):Promise<void>;

export function Startup(arg1:context.Context,arg2:storage.Storage):Promise<void>;
