// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {data_models} from '../models';
import {context} from '../models';

export function GetModels():Promise<Array<data_models.Model>>;

export function GetProviders():Promise<Array<data_models.Provider>>;

export function Startup(arg1:context.Context):Promise<void>;
