// Package skills holds the on-disk Skill model and IO for the Skills system.
package skills

import "time"

// Source identifies where a skill originated.
type Source string

const (
	// SourceBuiltin marks skills that ship with the application.
	SourceBuiltin Source = "builtin"
	// SourceUser marks skills installed by the user.
	SourceUser Source = "user"
	// SourceAI marks skills generated by an AI assistant.
	SourceAI Source = "ai"
)

// Skill is the in-memory representation of one skill.
// Body is the markdown content beneath the frontmatter.
type Skill struct {
	Name        string    `json:"name"`
	Description string    `json:"description"`
	Body        string    `json:"body"`
	Source      Source    `json:"source"`
	Disabled    bool      `json:"disabled"`
	UpdatedAt   time.Time `json:"updated_at"`
}

// SidecarManifest is the .lemontea sidecar stored next to a SKILL.md on disk.
// Built-in skills do not have a sidecar.
type SidecarManifest struct {
	Source    Source    `json:"source"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}
