// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Provider manages provider persistence and view-model conversion.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as provider_dto$0 from "./provider_dto/models.js";

/**
 * CreateProvider inserts a new provider record, bulk-saves its models, and sets the default model when specified.
 */
export function CreateProvider(input: provider_dto$0.CreateProviderInput): $CancellablePromise<provider_dto$0.CreateProviderOutput | null> {
    return $Call.ByID(3091785465, input).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * DeleteModel soft-deletes a single model record by its ID.
 */
export function DeleteModel(input: provider_dto$0.DeleteModelInput): $CancellablePromise<provider_dto$0.DeleteModelOutput | null> {
    return $Call.ByID(676242928, input).then(($result: any) => {
        return $$createType3($result);
    });
}

/**
 * DeleteProvider removes the provider, all its models, and the default-model record.
 */
export function DeleteProvider(input: provider_dto$0.DeleteProviderInput): $CancellablePromise<provider_dto$0.DeleteProviderOutput | null> {
    return $Call.ByID(940055810, input).then(($result: any) => {
        return $$createType5($result);
    });
}

/**
 * EditProvider updates the provider's mutable fields and creates any new models (id == 0) in the input list.
 */
export function EditProvider(input: provider_dto$0.EditProviderInput): $CancellablePromise<provider_dto$0.EditProviderOutput | null> {
    return $Call.ByID(1735819593, input).then(($result: any) => {
        return $$createType7($result);
    });
}

/**
 * ListProviders returns all provider view models with per-provider model lists and default-state annotations.
 */
export function ListProviders(input: provider_dto$0.ListProvidersInput): $CancellablePromise<provider_dto$0.ListProvidersOutput | null> {
    return $Call.ByID(1310620314, input).then(($result: any) => {
        return $$createType9($result);
    });
}

/**
 * ProviderAndModelList returns all providers with their models, both sorted by name ascending.
 */
export function ProviderAndModelList(input: provider_dto$0.ProviderAndModelListInput): $CancellablePromise<provider_dto$0.ProviderAndModelListOutput | null> {
    return $Call.ByID(2156855483, input).then(($result: any) => {
        return $$createType11($result);
    });
}

/**
 * RequestProviderModelList fetches the live model list from the provider API.
 */
export function RequestProviderModelList(input: provider_dto$0.RequestProviderModelListInput): $CancellablePromise<provider_dto$0.RequestProviderModelListOutput | null> {
    return $Call.ByID(3038676137, input).then(($result: any) => {
        return $$createType13($result);
    });
}

/**
 * SetDefault marks a provider as the global default and sets its default model.
 * When ModelId is nil the first model (sorted by name) is used.
 */
export function SetDefault(input: provider_dto$0.SetDefaultInput): $CancellablePromise<provider_dto$0.SetDefaultOutput | null> {
    return $Call.ByID(2411515717, input).then(($result: any) => {
        return $$createType15($result);
    });
}

// Private type creation functions
const $$createType0 = provider_dto$0.CreateProviderOutput.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = provider_dto$0.DeleteModelOutput.createFrom;
const $$createType3 = $Create.Nullable($$createType2);
const $$createType4 = provider_dto$0.DeleteProviderOutput.createFrom;
const $$createType5 = $Create.Nullable($$createType4);
const $$createType6 = provider_dto$0.EditProviderOutput.createFrom;
const $$createType7 = $Create.Nullable($$createType6);
const $$createType8 = provider_dto$0.ListProvidersOutput.createFrom;
const $$createType9 = $Create.Nullable($$createType8);
const $$createType10 = provider_dto$0.ProviderAndModelListOutput.createFrom;
const $$createType11 = $Create.Nullable($$createType10);
const $$createType12 = provider_dto$0.RequestProviderModelListOutput.createFrom;
const $$createType13 = $Create.Nullable($$createType12);
const $$createType14 = provider_dto$0.SetDefaultOutput.createFrom;
const $$createType15 = $Create.Nullable($$createType14);
