// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as view_model$0 from "../../../models/view_model/models.js";

export class LanguageListInput {

    /** Creates a new LanguageListInput instance. */
    constructor($$source: Partial<LanguageListInput> = {}) {

        Object.assign(this, $$source);
    }

    /**
     * Creates a new LanguageListInput instance from a string or object.
     */
    static createFrom($$source: any = {}): LanguageListInput {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new LanguageListInput($$parsedSource as Partial<LanguageListInput>);
    }
}

export class LanguageListOutput {
    "languages": view_model$0.Language[];

    /** Creates a new LanguageListOutput instance. */
    constructor($$source: Partial<LanguageListOutput> = {}) {
        if (!("languages" in $$source)) {
            this["languages"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new LanguageListOutput instance from a string or object.
     */
    static createFrom($$source: any = {}): LanguageListOutput {
        const $$createField0_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("languages" in $$parsedSource) {
            $$parsedSource["languages"] = $$createField0_0($$parsedSource["languages"]);
        }
        return new LanguageListOutput($$parsedSource as Partial<LanguageListOutput>);
    }
}

export class RegionListInput {

    /** Creates a new RegionListInput instance. */
    constructor($$source: Partial<RegionListInput> = {}) {

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RegionListInput instance from a string or object.
     */
    static createFrom($$source: any = {}): RegionListInput {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new RegionListInput($$parsedSource as Partial<RegionListInput>);
    }
}

export class RegionListOutput {
    "regions": view_model$0.Region[];

    /** Creates a new RegionListOutput instance. */
    constructor($$source: Partial<RegionListOutput> = {}) {
        if (!("regions" in $$source)) {
            this["regions"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RegionListOutput instance from a string or object.
     */
    static createFrom($$source: any = {}): RegionListOutput {
        const $$createField0_0 = $$createType3;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("regions" in $$parsedSource) {
            $$parsedSource["regions"] = $$createField0_0($$parsedSource["regions"]);
        }
        return new RegionListOutput($$parsedSource as Partial<RegionListOutput>);
    }
}

export class SupportedProviderListInput {

    /** Creates a new SupportedProviderListInput instance. */
    constructor($$source: Partial<SupportedProviderListInput> = {}) {

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SupportedProviderListInput instance from a string or object.
     */
    static createFrom($$source: any = {}): SupportedProviderListInput {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SupportedProviderListInput($$parsedSource as Partial<SupportedProviderListInput>);
    }
}

export class SupportedProviderListOutput {
    "supported_providers": view_model$0.SupportedProvider[];

    /** Creates a new SupportedProviderListOutput instance. */
    constructor($$source: Partial<SupportedProviderListOutput> = {}) {
        if (!("supported_providers" in $$source)) {
            this["supported_providers"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SupportedProviderListOutput instance from a string or object.
     */
    static createFrom($$source: any = {}): SupportedProviderListOutput {
        const $$createField0_0 = $$createType5;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("supported_providers" in $$parsedSource) {
            $$parsedSource["supported_providers"] = $$createField0_0($$parsedSource["supported_providers"]);
        }
        return new SupportedProviderListOutput($$parsedSource as Partial<SupportedProviderListOutput>);
    }
}

// Private type creation functions
const $$createType0 = view_model$0.Language.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = view_model$0.Region.createFrom;
const $$createType3 = $Create.Array($$createType2);
const $$createType4 = view_model$0.SupportedProvider.createFrom;
const $$createType5 = $Create.Array($$createType4);
