// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as schema$0 from "../../../../../../../github.com/cloudwego/eino/schema/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as gorm$0 from "../../../../../../../gorm.io/gorm/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as time$0 from "../../../../../../../time/models.js";

export class AssistantMessageExtra {
    "tool_uses": ToolUse[];
    "finish_reason": string;
    "finish_error": string;

    /** Creates a new AssistantMessageExtra instance. */
    constructor($$source: Partial<AssistantMessageExtra> = {}) {
        if (!("tool_uses" in $$source)) {
            this["tool_uses"] = [];
        }
        if (!("finish_reason" in $$source)) {
            this["finish_reason"] = "";
        }
        if (!("finish_error" in $$source)) {
            this["finish_error"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AssistantMessageExtra instance from a string or object.
     */
    static createFrom($$source: any = {}): AssistantMessageExtra {
        const $$createField0_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("tool_uses" in $$parsedSource) {
            $$parsedSource["tool_uses"] = $$createField0_0($$parsedSource["tool_uses"]);
        }
        return new AssistantMessageExtra($$parsedSource as Partial<AssistantMessageExtra>);
    }
}

export class Chat {
    "id": number;
    "created_at": time$0.Time;
    "updated_at": time$0.Time;
    "deleted_at": gorm$0.DeletedAt;
    "uuid": string;
    "title": string;
    "prompt": string;
    "is_collection": boolean;

    /** Creates a new Chat instance. */
    constructor($$source: Partial<Chat> = {}) {
        if (!("id" in $$source)) {
            this["id"] = 0;
        }
        if (!("created_at" in $$source)) {
            this["created_at"] = null;
        }
        if (!("updated_at" in $$source)) {
            this["updated_at"] = null;
        }
        if (!("deleted_at" in $$source)) {
            this["deleted_at"] = null;
        }
        if (!("uuid" in $$source)) {
            this["uuid"] = "";
        }
        if (!("title" in $$source)) {
            this["title"] = "";
        }
        if (!("prompt" in $$source)) {
            this["prompt"] = "";
        }
        if (!("is_collection" in $$source)) {
            this["is_collection"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Chat instance from a string or object.
     */
    static createFrom($$source: any = {}): Chat {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Chat($$parsedSource as Partial<Chat>);
    }
}

export class File {
    "name": string;
    "path": string;

    /**
     * 如果是图像的话，生成60x60的预览图
     */
    "preview": string | null;
    "mine_type": string;
    "size": number;

    /** Creates a new File instance. */
    constructor($$source: Partial<File> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("path" in $$source)) {
            this["path"] = "";
        }
        if (!("preview" in $$source)) {
            this["preview"] = null;
        }
        if (!("mine_type" in $$source)) {
            this["mine_type"] = "";
        }
        if (!("size" in $$source)) {
            this["size"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new File instance from a string or object.
     */
    static createFrom($$source: any = {}): File {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new File($$parsedSource as Partial<File>);
    }
}

export class Message {
    "id": number;
    "created_at": time$0.Time;
    "updated_at": time$0.Time;
    "deleted_at": gorm$0.DeletedAt;
    "chat_uuid": string;
    "message_uuid": string;
    "role": schema$0.RoleType;
    "content": string;
    "reasoning_content": string;
    "user_message_extra_content": string;
    "assistant_message_extra_content": string;
    "user_message_extra": UserMessageExtra | null;
    "assistant_message_extra": AssistantMessageExtra | null;

    /** Creates a new Message instance. */
    constructor($$source: Partial<Message> = {}) {
        if (!("id" in $$source)) {
            this["id"] = 0;
        }
        if (!("created_at" in $$source)) {
            this["created_at"] = null;
        }
        if (!("updated_at" in $$source)) {
            this["updated_at"] = null;
        }
        if (!("deleted_at" in $$source)) {
            this["deleted_at"] = null;
        }
        if (!("chat_uuid" in $$source)) {
            this["chat_uuid"] = "";
        }
        if (!("message_uuid" in $$source)) {
            this["message_uuid"] = "";
        }
        if (!("role" in $$source)) {
            this["role"] = schema$0.RoleType.$zero;
        }
        if (!("content" in $$source)) {
            this["content"] = "";
        }
        if (!("reasoning_content" in $$source)) {
            this["reasoning_content"] = "";
        }
        if (!("user_message_extra_content" in $$source)) {
            this["user_message_extra_content"] = "";
        }
        if (!("assistant_message_extra_content" in $$source)) {
            this["assistant_message_extra_content"] = "";
        }
        if (!("user_message_extra" in $$source)) {
            this["user_message_extra"] = null;
        }
        if (!("assistant_message_extra" in $$source)) {
            this["assistant_message_extra"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Message instance from a string or object.
     */
    static createFrom($$source: any = {}): Message {
        const $$createField11_0 = $$createType3;
        const $$createField12_0 = $$createType5;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("user_message_extra" in $$parsedSource) {
            $$parsedSource["user_message_extra"] = $$createField11_0($$parsedSource["user_message_extra"]);
        }
        if ("assistant_message_extra" in $$parsedSource) {
            $$parsedSource["assistant_message_extra"] = $$createField12_0($$parsedSource["assistant_message_extra"]);
        }
        return new Message($$parsedSource as Partial<Message>);
    }
}

export class Model {
    "id": number;
    "created_at": time$0.Time;
    "updated_at": time$0.Time;
    "deleted_at": gorm$0.DeletedAt;

    /**
     * 提供方id
     */
    "provider_id": number;
    "model": string;
    "owned_by": string;
    "object": string;
    "enable": boolean;
    "alias": string | null;
    "is_custom": boolean;

    /** Creates a new Model instance. */
    constructor($$source: Partial<Model> = {}) {
        if (!("id" in $$source)) {
            this["id"] = 0;
        }
        if (!("created_at" in $$source)) {
            this["created_at"] = null;
        }
        if (!("updated_at" in $$source)) {
            this["updated_at"] = null;
        }
        if (!("deleted_at" in $$source)) {
            this["deleted_at"] = null;
        }
        if (!("provider_id" in $$source)) {
            this["provider_id"] = 0;
        }
        if (!("model" in $$source)) {
            this["model"] = "";
        }
        if (!("owned_by" in $$source)) {
            this["owned_by"] = "";
        }
        if (!("object" in $$source)) {
            this["object"] = "";
        }
        if (!("enable" in $$source)) {
            this["enable"] = false;
        }
        if (!("alias" in $$source)) {
            this["alias"] = null;
        }
        if (!("is_custom" in $$source)) {
            this["is_custom"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Model instance from a string or object.
     */
    static createFrom($$source: any = {}): Model {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Model($$parsedSource as Partial<Model>);
    }
}

export enum ProviderType {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    ProviderTypeDeepseek = "deepseek",
    ProviderTypeAliyuns = "aliyuns",
    ProviderTypeOpenrouter = "openrouter",
    ProviderTypeOllama = "ollama",
    ProviderTypeOther = "other",
};

export class Task {
    "id": number;
    "created_at": time$0.Time;
    "updated_at": time$0.Time;
    "deleted_at": gorm$0.DeletedAt;
    "task_uuid": string;
    "chat_uuid": string;
    "assistant_message_uuid": string;
    "status": TaskStatus;
    "event_key": string;
    "finish_reason": string;
    "finish_error": string;
    "started_at": time$0.Time | null;
    "finished_at": time$0.Time | null;
    "last_output_at": time$0.Time | null;

    /** Creates a new Task instance. */
    constructor($$source: Partial<Task> = {}) {
        if (!("id" in $$source)) {
            this["id"] = 0;
        }
        if (!("created_at" in $$source)) {
            this["created_at"] = null;
        }
        if (!("updated_at" in $$source)) {
            this["updated_at"] = null;
        }
        if (!("deleted_at" in $$source)) {
            this["deleted_at"] = null;
        }
        if (!("task_uuid" in $$source)) {
            this["task_uuid"] = "";
        }
        if (!("chat_uuid" in $$source)) {
            this["chat_uuid"] = "";
        }
        if (!("assistant_message_uuid" in $$source)) {
            this["assistant_message_uuid"] = "";
        }
        if (!("status" in $$source)) {
            this["status"] = TaskStatus.$zero;
        }
        if (!("event_key" in $$source)) {
            this["event_key"] = "";
        }
        if (!("finish_reason" in $$source)) {
            this["finish_reason"] = "";
        }
        if (!("finish_error" in $$source)) {
            this["finish_error"] = "";
        }
        if (!("started_at" in $$source)) {
            this["started_at"] = null;
        }
        if (!("finished_at" in $$source)) {
            this["finished_at"] = null;
        }
        if (!("last_output_at" in $$source)) {
            this["last_output_at"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Task instance from a string or object.
     */
    static createFrom($$source: any = {}): Task {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Task($$parsedSource as Partial<Task>);
    }
}

export enum TaskStatus {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    TaskStatusPending = "pending",
    TaskStatusRunning = "running",
    TaskStatusCompleted = "completed",
    TaskStatusFailed = "failed",
    TaskStatusStopped = "stopped",
};

export class ToolUse {
    "index": number;
    "call_id": string;
    "content_pos": number;
    "tool_id": string;
    "tool_name": string;
    "tool_description": string;
    "tool_result": string;
    "status": ToolUseStatus;
    "started_at": time$0.Time | null;
    "finished_at": time$0.Time | null;
    "elapsed_ms": number;

    /** Creates a new ToolUse instance. */
    constructor($$source: Partial<ToolUse> = {}) {
        if (!("index" in $$source)) {
            this["index"] = 0;
        }
        if (!("call_id" in $$source)) {
            this["call_id"] = "";
        }
        if (!("content_pos" in $$source)) {
            this["content_pos"] = 0;
        }
        if (!("tool_id" in $$source)) {
            this["tool_id"] = "";
        }
        if (!("tool_name" in $$source)) {
            this["tool_name"] = "";
        }
        if (!("tool_description" in $$source)) {
            this["tool_description"] = "";
        }
        if (!("tool_result" in $$source)) {
            this["tool_result"] = "";
        }
        if (!("status" in $$source)) {
            this["status"] = ToolUseStatus.$zero;
        }
        if (!("started_at" in $$source)) {
            this["started_at"] = null;
        }
        if (!("finished_at" in $$source)) {
            this["finished_at"] = null;
        }
        if (!("elapsed_ms" in $$source)) {
            this["elapsed_ms"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ToolUse instance from a string or object.
     */
    static createFrom($$source: any = {}): ToolUse {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ToolUse($$parsedSource as Partial<ToolUse>);
    }
}

export enum ToolUseStatus {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    ToolUseStatusPending = "pending",
    ToolUseStatusRunning = "running",
    ToolUseStatusDone = "done",
    ToolUseStatusError = "error",
};

export class UserMessageExtra {
    /**
     * 模型id
     */
    "model_id": number;

    /**
     * 模型名称
     */
    "model_name": string;

    /**
     * 文件路径
     */
    "files": File[];

    /**
     * 工具id
     */
    "tools": string[];

    /**
     * agent id
     */
    "agents": string[];

    /** Creates a new UserMessageExtra instance. */
    constructor($$source: Partial<UserMessageExtra> = {}) {
        if (!("model_id" in $$source)) {
            this["model_id"] = 0;
        }
        if (!("model_name" in $$source)) {
            this["model_name"] = "";
        }
        if (!("files" in $$source)) {
            this["files"] = [];
        }
        if (!("tools" in $$source)) {
            this["tools"] = [];
        }
        if (!("agents" in $$source)) {
            this["agents"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new UserMessageExtra instance from a string or object.
     */
    static createFrom($$source: any = {}): UserMessageExtra {
        const $$createField2_0 = $$createType7;
        const $$createField3_0 = $$createType8;
        const $$createField4_0 = $$createType8;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("files" in $$parsedSource) {
            $$parsedSource["files"] = $$createField2_0($$parsedSource["files"]);
        }
        if ("tools" in $$parsedSource) {
            $$parsedSource["tools"] = $$createField3_0($$parsedSource["tools"]);
        }
        if ("agents" in $$parsedSource) {
            $$parsedSource["agents"] = $$createField4_0($$parsedSource["agents"]);
        }
        return new UserMessageExtra($$parsedSource as Partial<UserMessageExtra>);
    }
}

// Private type creation functions
const $$createType0 = ToolUse.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = UserMessageExtra.createFrom;
const $$createType3 = $Create.Nullable($$createType2);
const $$createType4 = AssistantMessageExtra.createFrom;
const $$createType5 = $Create.Nullable($$createType4);
const $$createType6 = File.createFrom;
const $$createType7 = $Create.Array($$createType6);
const $$createType8 = $Create.Array($Create.Any);
