// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as gorm$0 from "../../../../../../../gorm.io/gorm/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as time$0 from "../../../../../../../time/models.js";

/**
 * ExtensionItem stores one imported MCP tool or plugin entry.
 */
export class ExtensionItem {
    "id": string;
    "name": string;
    "description": string;
    "author": string;
    "version": string;
    "kind": string;
    "enabled": boolean;
    "runtime_status": string;
    "runtime_message": string;
    "root_dir": string;
    "source_dir": string;
    "config_file_path": string;
    "tools": ExtensionTool[];

    /** Creates a new ExtensionItem instance. */
    constructor($$source: Partial<ExtensionItem> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("description" in $$source)) {
            this["description"] = "";
        }
        if (!("author" in $$source)) {
            this["author"] = "";
        }
        if (!("version" in $$source)) {
            this["version"] = "";
        }
        if (!("kind" in $$source)) {
            this["kind"] = "";
        }
        if (!("enabled" in $$source)) {
            this["enabled"] = false;
        }
        if (!("runtime_status" in $$source)) {
            this["runtime_status"] = "";
        }
        if (!("runtime_message" in $$source)) {
            this["runtime_message"] = "";
        }
        if (!("root_dir" in $$source)) {
            this["root_dir"] = "";
        }
        if (!("source_dir" in $$source)) {
            this["source_dir"] = "";
        }
        if (!("config_file_path" in $$source)) {
            this["config_file_path"] = "";
        }
        if (!("tools" in $$source)) {
            this["tools"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ExtensionItem instance from a string or object.
     */
    static createFrom($$source: any = {}): ExtensionItem {
        const $$createField12_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("tools" in $$parsedSource) {
            $$parsedSource["tools"] = $$createField12_0($$parsedSource["tools"]);
        }
        return new ExtensionItem($$parsedSource as Partial<ExtensionItem>);
    }
}

/**
 * ExtensionTool stores discovered tool metadata for an imported extension.
 */
export class ExtensionTool {
    "tool_id": string;
    "server_id": string;
    "name": string;
    "description": string;
    "enabled": boolean;
    "requires_confirm": boolean;

    /** Creates a new ExtensionTool instance. */
    constructor($$source: Partial<ExtensionTool> = {}) {
        if (!("tool_id" in $$source)) {
            this["tool_id"] = "";
        }
        if (!("server_id" in $$source)) {
            this["server_id"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("description" in $$source)) {
            this["description"] = "";
        }
        if (!("enabled" in $$source)) {
            this["enabled"] = false;
        }
        if (!("requires_confirm" in $$source)) {
            this["requires_confirm"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ExtensionTool instance from a string or object.
     */
    static createFrom($$source: any = {}): ExtensionTool {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ExtensionTool($$parsedSource as Partial<ExtensionTool>);
    }
}

/**
 * TerminalOutputChunk stores an append-only slice of terminal output.
 */
export class TerminalOutputChunk {
    "id": number;
    "created_at": time$0.Time;
    "updated_at": time$0.Time;
    "deleted_at": gorm$0.DeletedAt;
    "terminal_id": string;
    "seq": number;
    "cursor_start": number;
    "cursor_end": number;
    "data": string;

    /** Creates a new TerminalOutputChunk instance. */
    constructor($$source: Partial<TerminalOutputChunk> = {}) {
        if (!("id" in $$source)) {
            this["id"] = 0;
        }
        if (!("created_at" in $$source)) {
            this["created_at"] = null;
        }
        if (!("updated_at" in $$source)) {
            this["updated_at"] = null;
        }
        if (!("deleted_at" in $$source)) {
            this["deleted_at"] = null;
        }
        if (!("terminal_id" in $$source)) {
            this["terminal_id"] = "";
        }
        if (!("seq" in $$source)) {
            this["seq"] = 0;
        }
        if (!("cursor_start" in $$source)) {
            this["cursor_start"] = 0;
        }
        if (!("cursor_end" in $$source)) {
            this["cursor_end"] = 0;
        }
        if (!("data" in $$source)) {
            this["data"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TerminalOutputChunk instance from a string or object.
     */
    static createFrom($$source: any = {}): TerminalOutputChunk {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new TerminalOutputChunk($$parsedSource as Partial<TerminalOutputChunk>);
    }
}

// Private type creation functions
const $$createType0 = ExtensionTool.createFrom;
const $$createType1 = $Create.Array($$createType0);
