// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Plugin manages imported MCP tools and future plugin entries.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as tools$0 from "../../pkg/agent/tools/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as plugin_dto$0 from "./plugin_dto/models.js";

/**
 * CancelLoginCli terminates a running login flow. Sets the orchestrator's abort
 * flag so the next step (if any) is skipped, and signals the current step's session
 * so its PTY dies and the orchestrator advances out of its output drain.
 */
export function CancelLoginCli(input: plugin_dto$0.CancelLoginCliInput): $CancellablePromise<void> {
    return $Call.ByID(1683333287, input);
}

/**
 * DeleteExtension removes one imported extension from config and deletes its install directory.
 * For CLI plugins this preserves plugins/cli_data/<name>/ (login state, manifest) by design;
 * use ResetCliData to clear that separately.
 */
export function DeleteExtension(input: plugin_dto$0.DeleteExtensionInput): $CancellablePromise<plugin_dto$0.DeleteExtensionOutput | null> {
    return $Call.ByID(885750792, input).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * GenerateCliManifest probes the CLI help output, asks the default chat model to draft a manifest, and persists it.
 */
export function GenerateCliManifest(input: plugin_dto$0.GenerateCliManifestInput): $CancellablePromise<plugin_dto$0.GenerateCliManifestOutput | null> {
    return $Call.ByID(3316722306, input).then(($result: any) => {
        return $$createType3($result);
    });
}

/**
 * GenerateCliManifestSync satisfies tools.CliManifestGenerator.
 */
export function GenerateCliManifestSync(extensionID: string): $CancellablePromise<string> {
    return $Call.ByID(4081191801, extensionID);
}

/**
 * GetExtensionDetail returns one extension plus its editable config file text.
 */
export function GetExtensionDetail(input: plugin_dto$0.GetExtensionDetailInput): $CancellablePromise<plugin_dto$0.GetExtensionDetailOutput | null> {
    return $Call.ByID(4263438156, input).then(($result: any) => {
        return $$createType5($result);
    });
}

/**
 * ImportExtension imports a local extension directory into the app data dir and persists it to config.
 */
export function ImportExtension(input: plugin_dto$0.ImportExtensionInput): $CancellablePromise<plugin_dto$0.ImportExtensionOutput | null> {
    return $Call.ByID(365615110, input).then(($result: any) => {
        return $$createType7($result);
    });
}

/**
 * InstallCliFromNpm installs a published npm package as a CLI plugin and persists it to config.json.
 */
export function InstallCliFromNpm(input: plugin_dto$0.InstallCliFromNpmInput): $CancellablePromise<plugin_dto$0.InstallCliFromNpmOutput | null> {
    return $Call.ByID(2588570828, input).then(($result: any) => {
        return $$createType9($result);
    });
}

/**
 * InstallCliSync satisfies tools.CliInstaller. It wraps the existing InstallCliFromNpm and emits progress events.
 */
export function InstallCliSync(npmPackage: string, name: string, onProgress: any): $CancellablePromise<string> {
    return $Call.ByID(2165116820, npmPackage, name, onProgress);
}

/**
 * ListAvailableTools returns builtin tools plus all enabled extension tool groups currently discoverable from config.
 */
export function ListAvailableTools(input: plugin_dto$0.ListAvailableToolsInput): $CancellablePromise<plugin_dto$0.ListAvailableToolsOutput | null> {
    return $Call.ByID(2259081982, input).then(($result: any) => {
        return $$createType11($result);
    });
}

/**
 * ListExtensions returns all imported plugin and MCP entries from persisted config.
 */
export function ListExtensions(input: plugin_dto$0.ListExtensionsInput): $CancellablePromise<plugin_dto$0.ListExtensionsOutput | null> {
    return $Call.ByID(3055040758, input).then(($result: any) => {
        return $$createType13($result);
    });
}

/**
 * LoginCli starts an interactive login flow for the named CLI plugin and returns immediately.
 * The flow runs each entry in manifest.ResolveLoginSteps() sequentially against the same PTY
 * dialog — output streams to the "cli.login.output" event throughout; "cli.login.done" is
 * emitted once when the whole flow ends (last step success, first step failure, or cancellation).
 */
export function LoginCli(input: plugin_dto$0.LoginCliInput): $CancellablePromise<plugin_dto$0.LoginCliOutput | null> {
    return $Call.ByID(1636532429, input).then(($result: any) => {
        return $$createType15($result);
    });
}

/**
 * ReloadExtension re-discovers tools from the current on-disk config for one extension.
 */
export function ReloadExtension(input: plugin_dto$0.ReloadExtensionInput): $CancellablePromise<plugin_dto$0.ReloadExtensionOutput | null> {
    return $Call.ByID(97654438, input).then(($result: any) => {
        return $$createType17($result);
    });
}

/**
 * ReportCliInstallProgress satisfies tools.CliInstallProgressReporter.
 */
export function ReportCliInstallProgress(sessionID: number, item: tools$0.CliInstallProgressItem): $CancellablePromise<void> {
    return $Call.ByID(2923896780, sessionID, item);
}

/**
 * ResetCliData removes the cli_data/<name> subtree for the given CLI plugin (login state, manifest, XDG dirs).
 */
export function ResetCliData(input: plugin_dto$0.ResetCliDataInput): $CancellablePromise<plugin_dto$0.ResetCliDataOutput | null> {
    return $Call.ByID(563484271, input).then(($result: any) => {
        return $$createType19($result);
    });
}

/**
 * ResizeLoginCli resizes the PTY window of a running login session.
 */
export function ResizeLoginCli(input: plugin_dto$0.ResizeLoginCliInput): $CancellablePromise<void> {
    return $Call.ByID(1741981989, input);
}

/**
 * RunCliCommandSync satisfies tools.CliCommandRunner.
 */
export function RunCliCommandSync(extensionID: string, argv: string[], outputMode: string, timeoutSeconds: number, onProgress: any): $CancellablePromise<string> {
    return $Call.ByID(413170665, extensionID, argv, outputMode, timeoutSeconds, onProgress);
}

/**
 * SaveExtensionConfig writes the edited config file and refreshes discovered tools.
 */
export function SaveExtensionConfig(input: plugin_dto$0.SaveExtensionConfigInput): $CancellablePromise<plugin_dto$0.SaveExtensionConfigOutput | null> {
    return $Call.ByID(1438647368, input).then(($result: any) => {
        return $$createType21($result);
    });
}

/**
 * SendLoginStdin forwards raw bytes to the running login session's PTY stdin.
 */
export function SendLoginStdin(input: plugin_dto$0.SendLoginStdinInput): $CancellablePromise<void> {
    return $Call.ByID(1518424595, input);
}

/**
 * ToggleExtension updates the enabled state and refreshes discovered tools when enabling.
 */
export function ToggleExtension(input: plugin_dto$0.ToggleExtensionInput): $CancellablePromise<plugin_dto$0.ToggleExtensionOutput | null> {
    return $Call.ByID(1222899149, input).then(($result: any) => {
        return $$createType23($result);
    });
}

/**
 * UpdateCliManifest validates the submitted JSON, writes it via cli.SaveManifest, and refreshes the persisted ExtensionItem.
 */
export function UpdateCliManifest(input: plugin_dto$0.UpdateCliManifestInput): $CancellablePromise<plugin_dto$0.UpdateCliManifestOutput | null> {
    return $Call.ByID(3735920080, input).then(($result: any) => {
        return $$createType25($result);
    });
}

// Private type creation functions
const $$createType0 = plugin_dto$0.DeleteExtensionOutput.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = plugin_dto$0.GenerateCliManifestOutput.createFrom;
const $$createType3 = $Create.Nullable($$createType2);
const $$createType4 = plugin_dto$0.GetExtensionDetailOutput.createFrom;
const $$createType5 = $Create.Nullable($$createType4);
const $$createType6 = plugin_dto$0.ImportExtensionOutput.createFrom;
const $$createType7 = $Create.Nullable($$createType6);
const $$createType8 = plugin_dto$0.InstallCliFromNpmOutput.createFrom;
const $$createType9 = $Create.Nullable($$createType8);
const $$createType10 = plugin_dto$0.ListAvailableToolsOutput.createFrom;
const $$createType11 = $Create.Nullable($$createType10);
const $$createType12 = plugin_dto$0.ListExtensionsOutput.createFrom;
const $$createType13 = $Create.Nullable($$createType12);
const $$createType14 = plugin_dto$0.LoginCliOutput.createFrom;
const $$createType15 = $Create.Nullable($$createType14);
const $$createType16 = plugin_dto$0.ReloadExtensionOutput.createFrom;
const $$createType17 = $Create.Nullable($$createType16);
const $$createType18 = plugin_dto$0.ResetCliDataOutput.createFrom;
const $$createType19 = $Create.Nullable($$createType18);
const $$createType20 = plugin_dto$0.SaveExtensionConfigOutput.createFrom;
const $$createType21 = $Create.Nullable($$createType20);
const $$createType22 = plugin_dto$0.ToggleExtensionOutput.createFrom;
const $$createType23 = $Create.Nullable($$createType22);
const $$createType24 = plugin_dto$0.UpdateCliManifestOutput.createFrom;
const $$createType25 = $Create.Nullable($$createType24);
