// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as view_model$0 from "../../../models/view_model/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as provider$0 from "../../../pkg/provider/models.js";

export class EnterHomeInput {

    /** Creates a new EnterHomeInput instance. */
    constructor($$source: Partial<EnterHomeInput> = {}) {

        Object.assign(this, $$source);
    }

    /**
     * Creates a new EnterHomeInput instance from a string or object.
     */
    static createFrom($$source: any = {}): EnterHomeInput {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new EnterHomeInput($$parsedSource as Partial<EnterHomeInput>);
    }
}

export class EnterHomeOutput {

    /** Creates a new EnterHomeOutput instance. */
    constructor($$source: Partial<EnterHomeOutput> = {}) {

        Object.assign(this, $$source);
    }

    /**
     * Creates a new EnterHomeOutput instance from a string or object.
     */
    static createFrom($$source: any = {}): EnterHomeOutput {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new EnterHomeOutput($$parsedSource as Partial<EnterHomeOutput>);
    }
}

export class ExitAppInput {

    /** Creates a new ExitAppInput instance. */
    constructor($$source: Partial<ExitAppInput> = {}) {

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ExitAppInput instance from a string or object.
     */
    static createFrom($$source: any = {}): ExitAppInput {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ExitAppInput($$parsedSource as Partial<ExitAppInput>);
    }
}

export class ExitAppOutput {

    /** Creates a new ExitAppOutput instance. */
    constructor($$source: Partial<ExitAppOutput> = {}) {

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ExitAppOutput instance from a string or object.
     */
    static createFrom($$source: any = {}): ExitAppOutput {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ExitAppOutput($$parsedSource as Partial<ExitAppOutput>);
    }
}

/**
 * IsInitializedInput is the empty input for IsInitialized.
 */
export class IsInitializedInput {

    /** Creates a new IsInitializedInput instance. */
    constructor($$source: Partial<IsInitializedInput> = {}) {

        Object.assign(this, $$source);
    }

    /**
     * Creates a new IsInitializedInput instance from a string or object.
     */
    static createFrom($$source: any = {}): IsInitializedInput {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new IsInitializedInput($$parsedSource as Partial<IsInitializedInput>);
    }
}

/**
 * IsInitializedOutput carries whether the application has finished onboarding.
 */
export class IsInitializedOutput {
    "initialized": boolean;

    /** Creates a new IsInitializedOutput instance. */
    constructor($$source: Partial<IsInitializedOutput> = {}) {
        if (!("initialized" in $$source)) {
            this["initialized"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new IsInitializedOutput instance from a string or object.
     */
    static createFrom($$source: any = {}): IsInitializedOutput {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new IsInitializedOutput($$parsedSource as Partial<IsInitializedOutput>);
    }
}

/**
 * SaveProviderAndMarkInitializedInput mirrors provider_dto.CreateProviderInput plus onboarding intent.
 */
export class SaveProviderAndMarkInitializedInput {
    "provider_name": string;
    "provider_type": provider$0.Type;
    "base_url": string;
    "api_key": string;
    "enable": boolean;
    "default_model": string | null;
    "models": view_model$0.Model[];

    /** Creates a new SaveProviderAndMarkInitializedInput instance. */
    constructor($$source: Partial<SaveProviderAndMarkInitializedInput> = {}) {
        if (!("provider_name" in $$source)) {
            this["provider_name"] = "";
        }
        if (!("provider_type" in $$source)) {
            this["provider_type"] = provider$0.Type.$zero;
        }
        if (!("base_url" in $$source)) {
            this["base_url"] = "";
        }
        if (!("api_key" in $$source)) {
            this["api_key"] = "";
        }
        if (!("enable" in $$source)) {
            this["enable"] = false;
        }
        if (!("default_model" in $$source)) {
            this["default_model"] = null;
        }
        if (!("models" in $$source)) {
            this["models"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SaveProviderAndMarkInitializedInput instance from a string or object.
     */
    static createFrom($$source: any = {}): SaveProviderAndMarkInitializedInput {
        const $$createField6_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("models" in $$parsedSource) {
            $$parsedSource["models"] = $$createField6_0($$parsedSource["models"]);
        }
        return new SaveProviderAndMarkInitializedInput($$parsedSource as Partial<SaveProviderAndMarkInitializedInput>);
    }
}

/**
 * SaveProviderAndMarkInitializedOutput is an empty acknowledgement.
 */
export class SaveProviderAndMarkInitializedOutput {

    /** Creates a new SaveProviderAndMarkInitializedOutput instance. */
    constructor($$source: Partial<SaveProviderAndMarkInitializedOutput> = {}) {

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SaveProviderAndMarkInitializedOutput instance from a string or object.
     */
    static createFrom($$source: any = {}): SaveProviderAndMarkInitializedOutput {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SaveProviderAndMarkInitializedOutput($$parsedSource as Partial<SaveProviderAndMarkInitializedOutput>);
    }
}

// Private type creation functions
const $$createType0 = view_model$0.Model.createFrom;
const $$createType1 = $Create.Array($$createType0);
