// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as data_models$0 from "../models/data_models/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as view_models$0 from "../models/view_models/models.js";

export function AddMCPToolFromFolder(path: string): $CancellablePromise<view_models$0.Tool | null> {
    return $Call.ByID(2335892937, path).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * AddProvider 添加供应商
 */
export function AddProvider(provider: view_models$0.Provider): $CancellablePromise<void> {
    return $Call.ByID(2363217024, provider);
}

/**
 * AddProviderCustomModel 添加自定义模型
 */
export function AddProviderCustomModel(providerId: number, modelName: string): $CancellablePromise<void> {
    return $Call.ByID(1808092888, providerId, modelName);
}

/**
 * ChatInfo 对话信息
 */
export function ChatInfo(chatUuid: string): $CancellablePromise<view_models$0.Chat | null> {
    return $Call.ByID(1668598080, chatUuid).then(($result: any) => {
        return $$createType3($result);
    });
}

/**
 * ChatList 聊天列表
 */
export function ChatList(offset: number, limit: number, keyword: string | null, isCollection: boolean): $CancellablePromise<view_models$0.ChatList | null> {
    return $Call.ByID(1229500932, offset, limit, keyword, isCollection).then(($result: any) => {
        return $$createType5($result);
    });
}

/**
 * ChatMessages 聊天消息
 */
export function ChatMessages(chatUuid: string, offset: number, limit: number): $CancellablePromise<view_models$0.MessageList | null> {
    return $Call.ByID(4205977752, chatUuid, offset, limit).then(($result: any) => {
        return $$createType7($result);
    });
}

/**
 * CollectionChat 收藏/取消收藏对话
 */
export function CollectionChat(chatUuid: string, isCollection: boolean): $CancellablePromise<void> {
    return $Call.ByID(1162381388, chatUuid, isCollection);
}

export function CompleteOnboarding(provider: view_models$0.Provider): $CancellablePromise<void> {
    return $Call.ByID(1964169468, provider);
}

/**
 * Completions 聊天
 */
export function Completions(inputMessage: view_models$0.Message): $CancellablePromise<view_models$0.Completions | null> {
    return $Call.ByID(2526998161, inputMessage).then(($result: any) => {
        return $$createType9($result);
    });
}

/**
 * DeleteChat 删除聊天
 */
export function DeleteChat(chatUuid: string): $CancellablePromise<void> {
    return $Call.ByID(2431139091, chatUuid);
}

export function DeleteMCPTool(toolID: string): $CancellablePromise<void> {
    return $Call.ByID(2048187701, toolID);
}

/**
 * DeleteProvider 删除供应商
 */
export function DeleteProvider(providerId: number): $CancellablePromise<void> {
    return $Call.ByID(1837639636, providerId);
}

export function DeleteProviderCustomModel(providerId: number, modelName: string): $CancellablePromise<void> {
    return $Call.ByID(2573490636, providerId, modelName);
}

export function ExitApp(): $CancellablePromise<void> {
    return $Call.ByID(125618793);
}

/**
 * GenChatTitle 创建聊天标题
 */
export function GenChatTitle(chatUuid: string, modelId: number, modelName: string, update: boolean): $CancellablePromise<string> {
    return $Call.ByID(726618912, chatUuid, modelId, modelName, update);
}

export function GetAppPreferences(): $CancellablePromise<view_models$0.AppPreferences | null> {
    return $Call.ByID(3272455837).then(($result: any) => {
        return $$createType11($result);
    });
}

export function GetChatActiveTask(chatUuid: string): $CancellablePromise<view_models$0.Task | null> {
    return $Call.ByID(230063095, chatUuid).then(($result: any) => {
        return $$createType13($result);
    });
}

/**
 * GetModels 获取所有模型
 */
export function GetModels(enableProvider: boolean | null, enableModel: boolean | null): $CancellablePromise<view_models$0.Model[]> {
    return $Call.ByID(2435611672, enableProvider, enableModel).then(($result: any) => {
        return $$createType15($result);
    });
}

export function GetPromptFile(name: string): $CancellablePromise<view_models$0.PromptFileDetail | null> {
    return $Call.ByID(508910466, name).then(($result: any) => {
        return $$createType17($result);
    });
}

/**
 * GetProviderModels 获取供应商模型信息
 */
export function GetProviderModels(provider: view_models$0.Provider): $CancellablePromise<view_models$0.Model[]> {
    return $Call.ByID(1264152129, provider).then(($result: any) => {
        return $$createType15($result);
    });
}

/**
 * GetProviders 获取所有供应商
 */
export function GetProviders(): $CancellablePromise<view_models$0.Provider[]> {
    return $Call.ByID(3921712104).then(($result: any) => {
        return $$createType19($result);
    });
}

export function GetRunningTasks(): $CancellablePromise<view_models$0.TaskList | null> {
    return $Call.ByID(2644190933).then(($result: any) => {
        return $$createType21($result);
    });
}

/**
 * GetSupportProviders 获取支持的供应商列表
 */
export function GetSupportProviders(): $CancellablePromise<view_models$0.SupportProvider[]> {
    return $Call.ByID(4035154853).then(($result: any) => {
        return $$createType23($result);
    });
}

export function GetTask(taskUuid: string): $CancellablePromise<view_models$0.Task | null> {
    return $Call.ByID(167956275, taskUuid).then(($result: any) => {
        return $$createType13($result);
    });
}

export function GetTools(): $CancellablePromise<view_models$0.Tool[]> {
    return $Call.ByID(432097153).then(($result: any) => {
        return $$createType24($result);
    });
}

export function IsInitialized(): $CancellablePromise<boolean> {
    return $Call.ByID(2734665048);
}

export function ListPromptFiles(): $CancellablePromise<view_models$0.PromptFileSummary[]> {
    return $Call.ByID(3509338483).then(($result: any) => {
        return $$createType26($result);
    });
}

export function OpenFile(path: string): $CancellablePromise<void> {
    return $Call.ByID(639918028, path);
}

export function OpenSettingsWindow(): $CancellablePromise<void> {
    return $Call.ByID(3479182543);
}

/**
 * RenameChat 重命名聊天
 */
export function RenameChat(chatUuid: string, title: string): $CancellablePromise<void> {
    return $Call.ByID(2654224378, chatUuid, title);
}

export function ResetPromptFile(name: string): $CancellablePromise<view_models$0.PromptFileDetail | null> {
    return $Call.ByID(2827988805, name).then(($result: any) => {
        return $$createType17($result);
    });
}

export function RespondToolApproval(input: data_models$0.ToolApprovalResponse): $CancellablePromise<void> {
    return $Call.ByID(1866640078, input);
}

export function SelectFiles(): $CancellablePromise<view_models$0.FileInfo[]> {
    return $Call.ByID(1220601789).then(($result: any) => {
        return $$createType28($result);
    });
}

export function SelectMCPFolder(): $CancellablePromise<string> {
    return $Call.ByID(2243094534);
}

export function StopCompletions(messageKey: string): $CancellablePromise<void> {
    return $Call.ByID(115959129, messageKey);
}

export function StopTask(taskUuid: string): $CancellablePromise<void> {
    return $Call.ByID(2829427223, taskUuid);
}

export function UpdateAppPreferences(input: view_models$0.AppPreferences): $CancellablePromise<view_models$0.AppPreferences | null> {
    return $Call.ByID(3440343940, input).then(($result: any) => {
        return $$createType11($result);
    });
}

export function UpdateMCPToolEnabled(toolID: string, enabled: boolean): $CancellablePromise<void> {
    return $Call.ByID(2043009872, toolID, enabled);
}

export function UpdatePromptFile(name: string, content: string): $CancellablePromise<view_models$0.PromptFileDetail | null> {
    return $Call.ByID(487143775, name, content).then(($result: any) => {
        return $$createType17($result);
    });
}

/**
 * UpdateProvider 更新供应商
 */
export function UpdateProvider(id: number, provider: view_models$0.Provider | null): $CancellablePromise<void> {
    return $Call.ByID(2109525354, id, provider);
}

/**
 * UpdateProviderModels 更新供应商
 */
export function UpdateProviderModels(providerId: number): $CancellablePromise<void> {
    return $Call.ByID(3054855516, providerId);
}

// Private type creation functions
const $$createType0 = view_models$0.Tool.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = data_models$0.Chat.createFrom;
const $$createType3 = $Create.Nullable($$createType2);
const $$createType4 = view_models$0.ChatList.createFrom;
const $$createType5 = $Create.Nullable($$createType4);
const $$createType6 = view_models$0.MessageList.createFrom;
const $$createType7 = $Create.Nullable($$createType6);
const $$createType8 = view_models$0.Completions.createFrom;
const $$createType9 = $Create.Nullable($$createType8);
const $$createType10 = view_models$0.AppPreferences.createFrom;
const $$createType11 = $Create.Nullable($$createType10);
const $$createType12 = data_models$0.Task.createFrom;
const $$createType13 = $Create.Nullable($$createType12);
const $$createType14 = view_models$0.Model.createFrom;
const $$createType15 = $Create.Array($$createType14);
const $$createType16 = view_models$0.PromptFileDetail.createFrom;
const $$createType17 = $Create.Nullable($$createType16);
const $$createType18 = view_models$0.Provider.createFrom;
const $$createType19 = $Create.Array($$createType18);
const $$createType20 = view_models$0.TaskList.createFrom;
const $$createType21 = $Create.Nullable($$createType20);
const $$createType22 = view_models$0.SupportProvider.createFrom;
const $$createType23 = $Create.Array($$createType22);
const $$createType24 = $Create.Array($$createType0);
const $$createType25 = view_models$0.PromptFileSummary.createFrom;
const $$createType26 = $Create.Array($$createType25);
const $$createType27 = data_models$0.File.createFrom;
const $$createType28 = $Create.Array($$createType27);
