// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as provider$0 from "../../../pkg/provider/models.js";

/**
 * AttachmentInput 是前端发送消息时携带的附件元数据。
 * Name/Mime 可空，后端通过 path 推断后写入存储与 model.Message。
 */
export class AttachmentInput {
    "path": string;
    "name"?: string;
    "mime"?: string;

    /** Creates a new AttachmentInput instance. */
    constructor($$source: Partial<AttachmentInput> = {}) {
        if (!("path" in $$source)) {
            this["path"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AttachmentInput instance from a string or object.
     */
    static createFrom($$source: any = {}): AttachmentInput {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new AttachmentInput($$parsedSource as Partial<AttachmentInput>);
    }
}

export class CreateSessionInput {
    "title": string;
    "tags"?: string[];

    /** Creates a new CreateSessionInput instance. */
    constructor($$source: Partial<CreateSessionInput> = {}) {
        if (!("title" in $$source)) {
            this["title"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CreateSessionInput instance from a string or object.
     */
    static createFrom($$source: any = {}): CreateSessionInput {
        const $$createField1_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("tags" in $$parsedSource) {
            $$parsedSource["tags"] = $$createField1_0($$parsedSource["tags"]);
        }
        return new CreateSessionInput($$parsedSource as Partial<CreateSessionInput>);
    }
}

export class CreateSessionOutput {
    "session_id": number;
    "title": string;
    "tags": string[];

    /** Creates a new CreateSessionOutput instance. */
    constructor($$source: Partial<CreateSessionOutput> = {}) {
        if (!("session_id" in $$source)) {
            this["session_id"] = 0;
        }
        if (!("title" in $$source)) {
            this["title"] = "";
        }
        if (!("tags" in $$source)) {
            this["tags"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CreateSessionOutput instance from a string or object.
     */
    static createFrom($$source: any = {}): CreateSessionOutput {
        const $$createField2_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("tags" in $$parsedSource) {
            $$parsedSource["tags"] = $$createField2_0($$parsedSource["tags"]);
        }
        return new CreateSessionOutput($$parsedSource as Partial<CreateSessionOutput>);
    }
}

export class DeleteSessionInput {
    "session_id": number;

    /** Creates a new DeleteSessionInput instance. */
    constructor($$source: Partial<DeleteSessionInput> = {}) {
        if (!("session_id" in $$source)) {
            this["session_id"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DeleteSessionInput instance from a string or object.
     */
    static createFrom($$source: any = {}): DeleteSessionInput {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new DeleteSessionInput($$parsedSource as Partial<DeleteSessionInput>);
    }
}

export class DeleteSessionOutput {

    /** Creates a new DeleteSessionOutput instance. */
    constructor($$source: Partial<DeleteSessionOutput> = {}) {

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DeleteSessionOutput instance from a string or object.
     */
    static createFrom($$source: any = {}): DeleteSessionOutput {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new DeleteSessionOutput($$parsedSource as Partial<DeleteSessionOutput>);
    }
}

export class GenerateTitleInput {
    "session_id": number;
    "base_url": string;
    "api_key": string;
    "model_name": string;
    "provider_type": provider$0.Type;

    /** Creates a new GenerateTitleInput instance. */
    constructor($$source: Partial<GenerateTitleInput> = {}) {
        if (!("session_id" in $$source)) {
            this["session_id"] = 0;
        }
        if (!("base_url" in $$source)) {
            this["base_url"] = "";
        }
        if (!("api_key" in $$source)) {
            this["api_key"] = "";
        }
        if (!("model_name" in $$source)) {
            this["model_name"] = "";
        }
        if (!("provider_type" in $$source)) {
            this["provider_type"] = provider$0.Type.$zero;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new GenerateTitleInput instance from a string or object.
     */
    static createFrom($$source: any = {}): GenerateTitleInput {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new GenerateTitleInput($$parsedSource as Partial<GenerateTitleInput>);
    }
}

export class GenerateTitleOutput {
    "title": string;

    /** Creates a new GenerateTitleOutput instance. */
    constructor($$source: Partial<GenerateTitleOutput> = {}) {
        if (!("title" in $$source)) {
            this["title"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new GenerateTitleOutput instance from a string or object.
     */
    static createFrom($$source: any = {}): GenerateTitleOutput {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new GenerateTitleOutput($$parsedSource as Partial<GenerateTitleOutput>);
    }
}

export class ListSessionsInput {
    "cursor": number;
    "limit": number;
    "starred_only": boolean;
    "include_hidden": boolean;

    /** Creates a new ListSessionsInput instance. */
    constructor($$source: Partial<ListSessionsInput> = {}) {
        if (!("cursor" in $$source)) {
            this["cursor"] = 0;
        }
        if (!("limit" in $$source)) {
            this["limit"] = 0;
        }
        if (!("starred_only" in $$source)) {
            this["starred_only"] = false;
        }
        if (!("include_hidden" in $$source)) {
            this["include_hidden"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ListSessionsInput instance from a string or object.
     */
    static createFrom($$source: any = {}): ListSessionsInput {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ListSessionsInput($$parsedSource as Partial<ListSessionsInput>);
    }
}

export class ListSessionsOutput {
    "sessions": SessionItem[];
    "next_cursor": number;
    "has_more": boolean;

    /** Creates a new ListSessionsOutput instance. */
    constructor($$source: Partial<ListSessionsOutput> = {}) {
        if (!("sessions" in $$source)) {
            this["sessions"] = [];
        }
        if (!("next_cursor" in $$source)) {
            this["next_cursor"] = 0;
        }
        if (!("has_more" in $$source)) {
            this["has_more"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ListSessionsOutput instance from a string or object.
     */
    static createFrom($$source: any = {}): ListSessionsOutput {
        const $$createField0_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("sessions" in $$parsedSource) {
            $$parsedSource["sessions"] = $$createField0_0($$parsedSource["sessions"]);
        }
        return new ListSessionsOutput($$parsedSource as Partial<ListSessionsOutput>);
    }
}

export class LoadSessionMessagesInput {
    "session_id": number;
    "offset": number;
    "limit": number;

    /** Creates a new LoadSessionMessagesInput instance. */
    constructor($$source: Partial<LoadSessionMessagesInput> = {}) {
        if (!("session_id" in $$source)) {
            this["session_id"] = 0;
        }
        if (!("offset" in $$source)) {
            this["offset"] = 0;
        }
        if (!("limit" in $$source)) {
            this["limit"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new LoadSessionMessagesInput instance from a string or object.
     */
    static createFrom($$source: any = {}): LoadSessionMessagesInput {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new LoadSessionMessagesInput($$parsedSource as Partial<LoadSessionMessagesInput>);
    }
}

export class LoadSessionMessagesOutput {
    "messages": MessageItem[];
    "total": number;
    "has_more": boolean;

    /** Creates a new LoadSessionMessagesOutput instance. */
    constructor($$source: Partial<LoadSessionMessagesOutput> = {}) {
        if (!("messages" in $$source)) {
            this["messages"] = [];
        }
        if (!("total" in $$source)) {
            this["total"] = 0;
        }
        if (!("has_more" in $$source)) {
            this["has_more"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new LoadSessionMessagesOutput instance from a string or object.
     */
    static createFrom($$source: any = {}): LoadSessionMessagesOutput {
        const $$createField0_0 = $$createType4;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("messages" in $$parsedSource) {
            $$parsedSource["messages"] = $$createField0_0($$parsedSource["messages"]);
        }
        return new LoadSessionMessagesOutput($$parsedSource as Partial<LoadSessionMessagesOutput>);
    }
}

export class MarkSessionReadInput {
    "session_id": number;

    /** Creates a new MarkSessionReadInput instance. */
    constructor($$source: Partial<MarkSessionReadInput> = {}) {
        if (!("session_id" in $$source)) {
            this["session_id"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new MarkSessionReadInput instance from a string or object.
     */
    static createFrom($$source: any = {}): MarkSessionReadInput {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new MarkSessionReadInput($$parsedSource as Partial<MarkSessionReadInput>);
    }
}

export class MarkSessionReadOutput {

    /** Creates a new MarkSessionReadOutput instance. */
    constructor($$source: Partial<MarkSessionReadOutput> = {}) {

        Object.assign(this, $$source);
    }

    /**
     * Creates a new MarkSessionReadOutput instance from a string or object.
     */
    static createFrom($$source: any = {}): MarkSessionReadOutput {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new MarkSessionReadOutput($$parsedSource as Partial<MarkSessionReadOutput>);
    }
}

export class MessageItem {
    "id": number;
    "session_id": number;
    "parent_id": number | null;
    "role": string;
    "content_type": string;
    "content": string;
    "model_name": string;
    "agent_name": string;
    "tokens_in": number;
    "tokens_out": number;
    "extra": string;
    "attachments": string;
    "created": string;

    /** Creates a new MessageItem instance. */
    constructor($$source: Partial<MessageItem> = {}) {
        if (!("id" in $$source)) {
            this["id"] = 0;
        }
        if (!("session_id" in $$source)) {
            this["session_id"] = 0;
        }
        if (!("parent_id" in $$source)) {
            this["parent_id"] = null;
        }
        if (!("role" in $$source)) {
            this["role"] = "";
        }
        if (!("content_type" in $$source)) {
            this["content_type"] = "";
        }
        if (!("content" in $$source)) {
            this["content"] = "";
        }
        if (!("model_name" in $$source)) {
            this["model_name"] = "";
        }
        if (!("agent_name" in $$source)) {
            this["agent_name"] = "";
        }
        if (!("tokens_in" in $$source)) {
            this["tokens_in"] = 0;
        }
        if (!("tokens_out" in $$source)) {
            this["tokens_out"] = 0;
        }
        if (!("extra" in $$source)) {
            this["extra"] = "";
        }
        if (!("attachments" in $$source)) {
            this["attachments"] = "";
        }
        if (!("created" in $$source)) {
            this["created"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new MessageItem instance from a string or object.
     */
    static createFrom($$source: any = {}): MessageItem {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new MessageItem($$parsedSource as Partial<MessageItem>);
    }
}

export class RenameSessionInput {
    "session_id": number;
    "title": string;

    /** Creates a new RenameSessionInput instance. */
    constructor($$source: Partial<RenameSessionInput> = {}) {
        if (!("session_id" in $$source)) {
            this["session_id"] = 0;
        }
        if (!("title" in $$source)) {
            this["title"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RenameSessionInput instance from a string or object.
     */
    static createFrom($$source: any = {}): RenameSessionInput {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new RenameSessionInput($$parsedSource as Partial<RenameSessionInput>);
    }
}

export class RenameSessionOutput {

    /** Creates a new RenameSessionOutput instance. */
    constructor($$source: Partial<RenameSessionOutput> = {}) {

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RenameSessionOutput instance from a string or object.
     */
    static createFrom($$source: any = {}): RenameSessionOutput {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new RenameSessionOutput($$parsedSource as Partial<RenameSessionOutput>);
    }
}

export class RespondToConfirmInput {
    "session_id": number;
    "approved": boolean;
    "message": string;
    "action": string;

    /** Creates a new RespondToConfirmInput instance. */
    constructor($$source: Partial<RespondToConfirmInput> = {}) {
        if (!("session_id" in $$source)) {
            this["session_id"] = 0;
        }
        if (!("approved" in $$source)) {
            this["approved"] = false;
        }
        if (!("message" in $$source)) {
            this["message"] = "";
        }
        if (!("action" in $$source)) {
            this["action"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RespondToConfirmInput instance from a string or object.
     */
    static createFrom($$source: any = {}): RespondToConfirmInput {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new RespondToConfirmInput($$parsedSource as Partial<RespondToConfirmInput>);
    }
}

export class RespondToConfirmOutput {

    /** Creates a new RespondToConfirmOutput instance. */
    constructor($$source: Partial<RespondToConfirmOutput> = {}) {

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RespondToConfirmOutput instance from a string or object.
     */
    static createFrom($$source: any = {}): RespondToConfirmOutput {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new RespondToConfirmOutput($$parsedSource as Partial<RespondToConfirmOutput>);
    }
}

export class SendMessageInput {
    "session_id": number;
    "content": string;
    "system_prompt"?: string;
    "skill_name"?: string;
    "base_url": string;
    "api_key": string;
    "model_name": string;
    "provider_type": provider$0.Type;
    "enabled_user_tools": string[];
    "attachments"?: AttachmentInput[];

    /** Creates a new SendMessageInput instance. */
    constructor($$source: Partial<SendMessageInput> = {}) {
        if (!("session_id" in $$source)) {
            this["session_id"] = 0;
        }
        if (!("content" in $$source)) {
            this["content"] = "";
        }
        if (!("base_url" in $$source)) {
            this["base_url"] = "";
        }
        if (!("api_key" in $$source)) {
            this["api_key"] = "";
        }
        if (!("model_name" in $$source)) {
            this["model_name"] = "";
        }
        if (!("provider_type" in $$source)) {
            this["provider_type"] = provider$0.Type.$zero;
        }
        if (!("enabled_user_tools" in $$source)) {
            this["enabled_user_tools"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SendMessageInput instance from a string or object.
     */
    static createFrom($$source: any = {}): SendMessageInput {
        const $$createField8_0 = $$createType0;
        const $$createField9_0 = $$createType6;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("enabled_user_tools" in $$parsedSource) {
            $$parsedSource["enabled_user_tools"] = $$createField8_0($$parsedSource["enabled_user_tools"]);
        }
        if ("attachments" in $$parsedSource) {
            $$parsedSource["attachments"] = $$createField9_0($$parsedSource["attachments"]);
        }
        return new SendMessageInput($$parsedSource as Partial<SendMessageInput>);
    }
}

export class SendMessageOutput {

    /** Creates a new SendMessageOutput instance. */
    constructor($$source: Partial<SendMessageOutput> = {}) {

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SendMessageOutput instance from a string or object.
     */
    static createFrom($$source: any = {}): SendMessageOutput {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SendMessageOutput($$parsedSource as Partial<SendMessageOutput>);
    }
}

export class SessionItem {
    "id": number;
    "title": string;
    "kind": string;
    "tags": string[];
    "starred": boolean;
    "status": string;
    "created": string;
    "updated": string;

    /** Creates a new SessionItem instance. */
    constructor($$source: Partial<SessionItem> = {}) {
        if (!("id" in $$source)) {
            this["id"] = 0;
        }
        if (!("title" in $$source)) {
            this["title"] = "";
        }
        if (!("kind" in $$source)) {
            this["kind"] = "";
        }
        if (!("tags" in $$source)) {
            this["tags"] = [];
        }
        if (!("starred" in $$source)) {
            this["starred"] = false;
        }
        if (!("status" in $$source)) {
            this["status"] = "";
        }
        if (!("created" in $$source)) {
            this["created"] = "";
        }
        if (!("updated" in $$source)) {
            this["updated"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SessionItem instance from a string or object.
     */
    static createFrom($$source: any = {}): SessionItem {
        const $$createField3_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("tags" in $$parsedSource) {
            $$parsedSource["tags"] = $$createField3_0($$parsedSource["tags"]);
        }
        return new SessionItem($$parsedSource as Partial<SessionItem>);
    }
}

/**
 * SpawnTaskSessionInput describes the initial prompt for an automated task session.
 */
export class SpawnTaskSessionInput {
    "title": string;
    "system_prompt": string;
    "user_message": string;
    "skill_name": string;
    "base_url": string;
    "api_key": string;
    "model_name": string;
    "provider_type": provider$0.Type;

    /** Creates a new SpawnTaskSessionInput instance. */
    constructor($$source: Partial<SpawnTaskSessionInput> = {}) {
        if (!("title" in $$source)) {
            this["title"] = "";
        }
        if (!("system_prompt" in $$source)) {
            this["system_prompt"] = "";
        }
        if (!("user_message" in $$source)) {
            this["user_message"] = "";
        }
        if (!("skill_name" in $$source)) {
            this["skill_name"] = "";
        }
        if (!("base_url" in $$source)) {
            this["base_url"] = "";
        }
        if (!("api_key" in $$source)) {
            this["api_key"] = "";
        }
        if (!("model_name" in $$source)) {
            this["model_name"] = "";
        }
        if (!("provider_type" in $$source)) {
            this["provider_type"] = provider$0.Type.$zero;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SpawnTaskSessionInput instance from a string or object.
     */
    static createFrom($$source: any = {}): SpawnTaskSessionInput {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SpawnTaskSessionInput($$parsedSource as Partial<SpawnTaskSessionInput>);
    }
}

/**
 * SpawnTaskSessionOutput returns the created task session identity.
 */
export class SpawnTaskSessionOutput {
    "session_id": number;
    "title": string;

    /** Creates a new SpawnTaskSessionOutput instance. */
    constructor($$source: Partial<SpawnTaskSessionOutput> = {}) {
        if (!("session_id" in $$source)) {
            this["session_id"] = 0;
        }
        if (!("title" in $$source)) {
            this["title"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SpawnTaskSessionOutput instance from a string or object.
     */
    static createFrom($$source: any = {}): SpawnTaskSessionOutput {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SpawnTaskSessionOutput($$parsedSource as Partial<SpawnTaskSessionOutput>);
    }
}

export class StopGenerationInput {
    "session_id": number;

    /** Creates a new StopGenerationInput instance. */
    constructor($$source: Partial<StopGenerationInput> = {}) {
        if (!("session_id" in $$source)) {
            this["session_id"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new StopGenerationInput instance from a string or object.
     */
    static createFrom($$source: any = {}): StopGenerationInput {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new StopGenerationInput($$parsedSource as Partial<StopGenerationInput>);
    }
}

export class StopGenerationOutput {

    /** Creates a new StopGenerationOutput instance. */
    constructor($$source: Partial<StopGenerationOutput> = {}) {

        Object.assign(this, $$source);
    }

    /**
     * Creates a new StopGenerationOutput instance from a string or object.
     */
    static createFrom($$source: any = {}): StopGenerationOutput {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new StopGenerationOutput($$parsedSource as Partial<StopGenerationOutput>);
    }
}

export class ToggleStarSessionInput {
    "session_id": number;
    "starred": boolean;

    /** Creates a new ToggleStarSessionInput instance. */
    constructor($$source: Partial<ToggleStarSessionInput> = {}) {
        if (!("session_id" in $$source)) {
            this["session_id"] = 0;
        }
        if (!("starred" in $$source)) {
            this["starred"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ToggleStarSessionInput instance from a string or object.
     */
    static createFrom($$source: any = {}): ToggleStarSessionInput {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ToggleStarSessionInput($$parsedSource as Partial<ToggleStarSessionInput>);
    }
}

export class ToggleStarSessionOutput {

    /** Creates a new ToggleStarSessionOutput instance. */
    constructor($$source: Partial<ToggleStarSessionOutput> = {}) {

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ToggleStarSessionOutput instance from a string or object.
     */
    static createFrom($$source: any = {}): ToggleStarSessionOutput {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ToggleStarSessionOutput($$parsedSource as Partial<ToggleStarSessionOutput>);
    }
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
const $$createType1 = SessionItem.createFrom;
const $$createType2 = $Create.Array($$createType1);
const $$createType3 = MessageItem.createFrom;
const $$createType4 = $Create.Array($$createType3);
const $$createType5 = AttachmentInput.createFrom;
const $$createType6 = $Create.Array($$createType5);
