// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as schema$0 from "../../../../../../../github.com/cloudwego/eino/schema/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as data_models$0 from "../data_models/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as gorm$0 from "../../../../../../../gorm.io/gorm/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as time$0 from "../../../../../../../time/models.js";

export class Chat {
    "id": number;
    "created_at": time$0.Time;
    "updated_at": time$0.Time;
    "deleted_at": gorm$0.DeletedAt;
    "uuid": string;
    "model_id": number;
    "title": string;
    "prompt": string;
    "is_collection": boolean;
    "content": MatchMessage[];
    "reasoning_content": MatchMessage[];

    /** Creates a new Chat instance. */
    constructor($$source: Partial<Chat> = {}) {
        if (!("id" in $$source)) {
            this["id"] = 0;
        }
        if (!("created_at" in $$source)) {
            this["created_at"] = null;
        }
        if (!("updated_at" in $$source)) {
            this["updated_at"] = null;
        }
        if (!("deleted_at" in $$source)) {
            this["deleted_at"] = null;
        }
        if (!("uuid" in $$source)) {
            this["uuid"] = "";
        }
        if (!("model_id" in $$source)) {
            this["model_id"] = 0;
        }
        if (!("title" in $$source)) {
            this["title"] = "";
        }
        if (!("prompt" in $$source)) {
            this["prompt"] = "";
        }
        if (!("is_collection" in $$source)) {
            this["is_collection"] = false;
        }
        if (!("content" in $$source)) {
            this["content"] = [];
        }
        if (!("reasoning_content" in $$source)) {
            this["reasoning_content"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Chat instance from a string or object.
     */
    static createFrom($$source: any = {}): Chat {
        const $$createField9_0 = $$createType1;
        const $$createField10_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("content" in $$parsedSource) {
            $$parsedSource["content"] = $$createField9_0($$parsedSource["content"]);
        }
        if ("reasoning_content" in $$parsedSource) {
            $$parsedSource["reasoning_content"] = $$createField10_0($$parsedSource["reasoning_content"]);
        }
        return new Chat($$parsedSource as Partial<Chat>);
    }
}

export class ChatList {
    "lists": Chat[];
    "total": number;

    /** Creates a new ChatList instance. */
    constructor($$source: Partial<ChatList> = {}) {
        if (!("lists" in $$source)) {
            this["lists"] = [];
        }
        if (!("total" in $$source)) {
            this["total"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ChatList instance from a string or object.
     */
    static createFrom($$source: any = {}): ChatList {
        const $$createField0_0 = $$createType3;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("lists" in $$parsedSource) {
            $$parsedSource["lists"] = $$createField0_0($$parsedSource["lists"]);
        }
        return new ChatList($$parsedSource as Partial<ChatList>);
    }
}

export class Completions {
    "chat_uuid": string;
    "message_uuid": string;

    /** Creates a new Completions instance. */
    constructor($$source: Partial<Completions> = {}) {
        if (!("chat_uuid" in $$source)) {
            this["chat_uuid"] = "";
        }
        if (!("message_uuid" in $$source)) {
            this["message_uuid"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Completions instance from a string or object.
     */
    static createFrom($$source: any = {}): Completions {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Completions($$parsedSource as Partial<Completions>);
    }
}

export class MatchMessage {
    "role": string;
    "content": string;

    /** Creates a new MatchMessage instance. */
    constructor($$source: Partial<MatchMessage> = {}) {
        if (!("role" in $$source)) {
            this["role"] = "";
        }
        if (!("content" in $$source)) {
            this["content"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new MatchMessage instance from a string or object.
     */
    static createFrom($$source: any = {}): MatchMessage {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new MatchMessage($$parsedSource as Partial<MatchMessage>);
    }
}

export class MessageList {
    "messages": schema$0.Message[];
    "total": number;

    /** Creates a new MessageList instance. */
    constructor($$source: Partial<MessageList> = {}) {
        if (!("messages" in $$source)) {
            this["messages"] = [];
        }
        if (!("total" in $$source)) {
            this["total"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new MessageList instance from a string or object.
     */
    static createFrom($$source: any = {}): MessageList {
        const $$createField0_0 = $$createType5;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("messages" in $$parsedSource) {
            $$parsedSource["messages"] = $$createField0_0($$parsedSource["messages"]);
        }
        return new MessageList($$parsedSource as Partial<MessageList>);
    }
}

export const Model = data_models$0.Model;
export type Model = data_models$0.Model;

export const Provider = data_models$0.Provider;
export type Provider = data_models$0.Provider;

// Private type creation functions
const $$createType0 = MatchMessage.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = Chat.createFrom;
const $$createType3 = $Create.Array($$createType2);
const $$createType4 = schema$0.Message.createFrom;
const $$createType5 = $Create.Array($$createType4);
