// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as data_models$0 from "../data_models/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as gorm$0 from "../../../../../../../gorm.io/gorm/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as time$0 from "../../../../../../../time/models.js";

export class AppPreferences {
    "language": data_models$0.AppLanguage;
    "region": data_models$0.AppRegion;

    /** Creates a new AppPreferences instance. */
    constructor($$source: Partial<AppPreferences> = {}) {
        if (!("language" in $$source)) {
            this["language"] = data_models$0.AppLanguage.$zero;
        }
        if (!("region" in $$source)) {
            this["region"] = data_models$0.AppRegion.$zero;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AppPreferences instance from a string or object.
     */
    static createFrom($$source: any = {}): AppPreferences {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new AppPreferences($$parsedSource as Partial<AppPreferences>);
    }
}

export const Chat = data_models$0.Chat;
export type Chat = data_models$0.Chat;

export class ChatList {
    "lists": Chat[];
    "total": number;

    /** Creates a new ChatList instance. */
    constructor($$source: Partial<ChatList> = {}) {
        if (!("lists" in $$source)) {
            this["lists"] = [];
        }
        if (!("total" in $$source)) {
            this["total"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ChatList instance from a string or object.
     */
    static createFrom($$source: any = {}): ChatList {
        const $$createField0_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("lists" in $$parsedSource) {
            $$parsedSource["lists"] = $$createField0_0($$parsedSource["lists"]);
        }
        return new ChatList($$parsedSource as Partial<ChatList>);
    }
}

export class Completions {
    "chat_uuid": string;
    "task_uuid": string;
    "message_uuid": string;
    "event_key": string;

    /** Creates a new Completions instance. */
    constructor($$source: Partial<Completions> = {}) {
        if (!("chat_uuid" in $$source)) {
            this["chat_uuid"] = "";
        }
        if (!("task_uuid" in $$source)) {
            this["task_uuid"] = "";
        }
        if (!("message_uuid" in $$source)) {
            this["message_uuid"] = "";
        }
        if (!("event_key" in $$source)) {
            this["event_key"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Completions instance from a string or object.
     */
    static createFrom($$source: any = {}): Completions {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Completions($$parsedSource as Partial<Completions>);
    }
}

export const FileInfo = data_models$0.File;
export type FileInfo = data_models$0.File;

export const Message = data_models$0.Message;
export type Message = data_models$0.Message;

export class MessageList {
    "messages": Message[];
    "total": number;

    /** Creates a new MessageList instance. */
    constructor($$source: Partial<MessageList> = {}) {
        if (!("messages" in $$source)) {
            this["messages"] = [];
        }
        if (!("total" in $$source)) {
            this["total"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new MessageList instance from a string or object.
     */
    static createFrom($$source: any = {}): MessageList {
        const $$createField0_0 = $$createType3;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("messages" in $$parsedSource) {
            $$parsedSource["messages"] = $$createField0_0($$parsedSource["messages"]);
        }
        return new MessageList($$parsedSource as Partial<MessageList>);
    }
}

export class Model {
    "id": number;
    "created_at": time$0.Time;
    "updated_at": time$0.Time;
    "deleted_at": gorm$0.DeletedAt;

    /**
     * 提供方id
     */
    "provider_id": number;
    "model": string;
    "owned_by": string;
    "object": string;
    "enable": boolean;
    "alias": string | null;
    "is_custom": boolean;

    /** Creates a new Model instance. */
    constructor($$source: Partial<Model> = {}) {
        if (!("id" in $$source)) {
            this["id"] = 0;
        }
        if (!("created_at" in $$source)) {
            this["created_at"] = null;
        }
        if (!("updated_at" in $$source)) {
            this["updated_at"] = null;
        }
        if (!("deleted_at" in $$source)) {
            this["deleted_at"] = null;
        }
        if (!("provider_id" in $$source)) {
            this["provider_id"] = 0;
        }
        if (!("model" in $$source)) {
            this["model"] = "";
        }
        if (!("owned_by" in $$source)) {
            this["owned_by"] = "";
        }
        if (!("object" in $$source)) {
            this["object"] = "";
        }
        if (!("enable" in $$source)) {
            this["enable"] = false;
        }
        if (!("alias" in $$source)) {
            this["alias"] = null;
        }
        if (!("is_custom" in $$source)) {
            this["is_custom"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Model instance from a string or object.
     */
    static createFrom($$source: any = {}): Model {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Model($$parsedSource as Partial<Model>);
    }
}

export class PromptFileDetail {
    "name": string;
    "title": string;
    "description": string;
    "is_system": boolean;
    "content": string;
    "updated_at": time$0.Time | null;

    /** Creates a new PromptFileDetail instance. */
    constructor($$source: Partial<PromptFileDetail> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("title" in $$source)) {
            this["title"] = "";
        }
        if (!("description" in $$source)) {
            this["description"] = "";
        }
        if (!("is_system" in $$source)) {
            this["is_system"] = false;
        }
        if (!("content" in $$source)) {
            this["content"] = "";
        }
        if (!("updated_at" in $$source)) {
            this["updated_at"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PromptFileDetail instance from a string or object.
     */
    static createFrom($$source: any = {}): PromptFileDetail {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new PromptFileDetail($$parsedSource as Partial<PromptFileDetail>);
    }
}

export class PromptFileSummary {
    "name": string;
    "title": string;
    "description": string;
    "is_system": boolean;
    "updated_at": time$0.Time | null;

    /** Creates a new PromptFileSummary instance. */
    constructor($$source: Partial<PromptFileSummary> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("title" in $$source)) {
            this["title"] = "";
        }
        if (!("description" in $$source)) {
            this["description"] = "";
        }
        if (!("is_system" in $$source)) {
            this["is_system"] = false;
        }
        if (!("updated_at" in $$source)) {
            this["updated_at"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PromptFileSummary instance from a string or object.
     */
    static createFrom($$source: any = {}): PromptFileSummary {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new PromptFileSummary($$parsedSource as Partial<PromptFileSummary>);
    }
}

export class Provider {
    "id": number;
    "created_at": time$0.Time;
    "updated_at": time$0.Time;
    "deleted_at": gorm$0.DeletedAt;

    /**
     * 提供方名称
     */
    "provider_name": string;

    /**
     * 基础url
     */
    "base_url": string;

    /**
     * 文件上传url
     */
    "file_upload_base_url": string | null;

    /**
     * api key
     */
    "api_key": string;

    /**
     * 启用
     */
    "enable": boolean;
    "default_model_id": number | null;
    "models": Model[];
    "custom_models": data_models$0.Model[];
    "provider_type": data_models$0.ProviderType;

    /** Creates a new Provider instance. */
    constructor($$source: Partial<Provider> = {}) {
        if (!("id" in $$source)) {
            this["id"] = 0;
        }
        if (!("created_at" in $$source)) {
            this["created_at"] = null;
        }
        if (!("updated_at" in $$source)) {
            this["updated_at"] = null;
        }
        if (!("deleted_at" in $$source)) {
            this["deleted_at"] = null;
        }
        if (!("provider_name" in $$source)) {
            this["provider_name"] = "";
        }
        if (!("base_url" in $$source)) {
            this["base_url"] = "";
        }
        if (!("file_upload_base_url" in $$source)) {
            this["file_upload_base_url"] = null;
        }
        if (!("api_key" in $$source)) {
            this["api_key"] = "";
        }
        if (!("enable" in $$source)) {
            this["enable"] = false;
        }
        if (!("default_model_id" in $$source)) {
            this["default_model_id"] = null;
        }
        if (!("models" in $$source)) {
            this["models"] = [];
        }
        if (!("custom_models" in $$source)) {
            this["custom_models"] = [];
        }
        if (!("provider_type" in $$source)) {
            this["provider_type"] = data_models$0.ProviderType.$zero;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Provider instance from a string or object.
     */
    static createFrom($$source: any = {}): Provider {
        const $$createField10_0 = $$createType5;
        const $$createField11_0 = $$createType7;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("models" in $$parsedSource) {
            $$parsedSource["models"] = $$createField10_0($$parsedSource["models"]);
        }
        if ("custom_models" in $$parsedSource) {
            $$parsedSource["custom_models"] = $$createField11_0($$parsedSource["custom_models"]);
        }
        return new Provider($$parsedSource as Partial<Provider>);
    }
}

export class SupportProvider {
    "provider_type": data_models$0.ProviderType;
    "icon": string;
    "name": string;
    "base_url": string;
    "file_upload_base_url": string | null;
    "description": string;

    /** Creates a new SupportProvider instance. */
    constructor($$source: Partial<SupportProvider> = {}) {
        if (!("provider_type" in $$source)) {
            this["provider_type"] = data_models$0.ProviderType.$zero;
        }
        if (!("icon" in $$source)) {
            this["icon"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("base_url" in $$source)) {
            this["base_url"] = "";
        }
        if (!("file_upload_base_url" in $$source)) {
            this["file_upload_base_url"] = null;
        }
        if (!("description" in $$source)) {
            this["description"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SupportProvider instance from a string or object.
     */
    static createFrom($$source: any = {}): SupportProvider {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SupportProvider($$parsedSource as Partial<SupportProvider>);
    }
}

export const Task = data_models$0.Task;
export type Task = data_models$0.Task;

export class TaskList {
    "tasks": Task[];

    /** Creates a new TaskList instance. */
    constructor($$source: Partial<TaskList> = {}) {
        if (!("tasks" in $$source)) {
            this["tasks"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TaskList instance from a string or object.
     */
    static createFrom($$source: any = {}): TaskList {
        const $$createField0_0 = $$createType9;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("tasks" in $$parsedSource) {
            $$parsedSource["tasks"] = $$createField0_0($$parsedSource["tasks"]);
        }
        return new TaskList($$parsedSource as Partial<TaskList>);
    }
}

export class Tool {
    "id": string;
    "name": string;
    "description": string;
    "source_type": string;
    "enabled": boolean;
    "is_deletable": boolean;

    /** Creates a new Tool instance. */
    constructor($$source: Partial<Tool> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("description" in $$source)) {
            this["description"] = "";
        }
        if (!("source_type" in $$source)) {
            this["source_type"] = "";
        }
        if (!("enabled" in $$source)) {
            this["enabled"] = false;
        }
        if (!("is_deletable" in $$source)) {
            this["is_deletable"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Tool instance from a string or object.
     */
    static createFrom($$source: any = {}): Tool {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Tool($$parsedSource as Partial<Tool>);
    }
}

// Private type creation functions
const $$createType0 = data_models$0.Chat.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = data_models$0.Message.createFrom;
const $$createType3 = $Create.Array($$createType2);
const $$createType4 = Model.createFrom;
const $$createType5 = $Create.Array($$createType4);
const $$createType6 = data_models$0.Model.createFrom;
const $$createType7 = $Create.Array($$createType6);
const $$createType8 = data_models$0.Task.createFrom;
const $$createType9 = $Create.Array($$createType8);
