// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as schema$0 from "../../../../../../../github.com/cloudwego/eino/schema/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as data_models$0 from "../data_models/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as gorm$0 from "../../../../../../../gorm.io/gorm/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as time$0 from "../../../../../../../time/models.js";

export class Chat {
    "id": number;
    "created_at": time$0.Time;
    "updated_at": time$0.Time;
    "deleted_at": gorm$0.DeletedAt;
    "uuid": string;
    "title": string;
    "prompt": string;
    "is_collection": boolean;
    "content": MatchMessage[];
    "reasoning_content": MatchMessage[];

    /** Creates a new Chat instance. */
    constructor($$source: Partial<Chat> = {}) {
        if (!("id" in $$source)) {
            this["id"] = 0;
        }
        if (!("created_at" in $$source)) {
            this["created_at"] = null;
        }
        if (!("updated_at" in $$source)) {
            this["updated_at"] = null;
        }
        if (!("deleted_at" in $$source)) {
            this["deleted_at"] = null;
        }
        if (!("uuid" in $$source)) {
            this["uuid"] = "";
        }
        if (!("title" in $$source)) {
            this["title"] = "";
        }
        if (!("prompt" in $$source)) {
            this["prompt"] = "";
        }
        if (!("is_collection" in $$source)) {
            this["is_collection"] = false;
        }
        if (!("content" in $$source)) {
            this["content"] = [];
        }
        if (!("reasoning_content" in $$source)) {
            this["reasoning_content"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Chat instance from a string or object.
     */
    static createFrom($$source: any = {}): Chat {
        const $$createField8_0 = $$createType1;
        const $$createField9_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("content" in $$parsedSource) {
            $$parsedSource["content"] = $$createField8_0($$parsedSource["content"]);
        }
        if ("reasoning_content" in $$parsedSource) {
            $$parsedSource["reasoning_content"] = $$createField9_0($$parsedSource["reasoning_content"]);
        }
        return new Chat($$parsedSource as Partial<Chat>);
    }
}

export class ChatList {
    "lists": Chat[];
    "total": number;

    /** Creates a new ChatList instance. */
    constructor($$source: Partial<ChatList> = {}) {
        if (!("lists" in $$source)) {
            this["lists"] = [];
        }
        if (!("total" in $$source)) {
            this["total"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ChatList instance from a string or object.
     */
    static createFrom($$source: any = {}): ChatList {
        const $$createField0_0 = $$createType3;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("lists" in $$parsedSource) {
            $$parsedSource["lists"] = $$createField0_0($$parsedSource["lists"]);
        }
        return new ChatList($$parsedSource as Partial<ChatList>);
    }
}

export class Completions {
    "chat_uuid": string;
    "message_uuid": string;

    /** Creates a new Completions instance. */
    constructor($$source: Partial<Completions> = {}) {
        if (!("chat_uuid" in $$source)) {
            this["chat_uuid"] = "";
        }
        if (!("message_uuid" in $$source)) {
            this["message_uuid"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Completions instance from a string or object.
     */
    static createFrom($$source: any = {}): Completions {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Completions($$parsedSource as Partial<Completions>);
    }
}

export class File {
    "preview": string | null;
    "name": string;
    "file_path": string;
    "mine_type": string;
    "chat_message_part_type": schema$0.ChatMessagePartType;
    "size": number;

    /** Creates a new File instance. */
    constructor($$source: Partial<File> = {}) {
        if (!("preview" in $$source)) {
            this["preview"] = null;
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("file_path" in $$source)) {
            this["file_path"] = "";
        }
        if (!("mine_type" in $$source)) {
            this["mine_type"] = "";
        }
        if (!("chat_message_part_type" in $$source)) {
            this["chat_message_part_type"] = schema$0.ChatMessagePartType.$zero;
        }
        if (!("size" in $$source)) {
            this["size"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new File instance from a string or object.
     */
    static createFrom($$source: any = {}): File {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new File($$parsedSource as Partial<File>);
    }
}

export class MatchMessage {
    "role": string;
    "content": string;

    /** Creates a new MatchMessage instance. */
    constructor($$source: Partial<MatchMessage> = {}) {
        if (!("role" in $$source)) {
            this["role"] = "";
        }
        if (!("content" in $$source)) {
            this["content"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new MatchMessage instance from a string or object.
     */
    static createFrom($$source: any = {}): MatchMessage {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new MatchMessage($$parsedSource as Partial<MatchMessage>);
    }
}

export class MessageList {
    "messages": schema$0.Message[];
    "total": number;

    /** Creates a new MessageList instance. */
    constructor($$source: Partial<MessageList> = {}) {
        if (!("messages" in $$source)) {
            this["messages"] = [];
        }
        if (!("total" in $$source)) {
            this["total"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new MessageList instance from a string or object.
     */
    static createFrom($$source: any = {}): MessageList {
        const $$createField0_0 = $$createType5;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("messages" in $$parsedSource) {
            $$parsedSource["messages"] = $$createField0_0($$parsedSource["messages"]);
        }
        return new MessageList($$parsedSource as Partial<MessageList>);
    }
}

export class MessagePkg {
    "chatUuid": string;
    "model": string;
    "message": schema$0.Message;
    "files": File[];

    /** Creates a new MessagePkg instance. */
    constructor($$source: Partial<MessagePkg> = {}) {
        if (!("chatUuid" in $$source)) {
            this["chatUuid"] = "";
        }
        if (!("model" in $$source)) {
            this["model"] = "";
        }
        if (!("message" in $$source)) {
            this["message"] = (new schema$0.Message());
        }
        if (!("files" in $$source)) {
            this["files"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new MessagePkg instance from a string or object.
     */
    static createFrom($$source: any = {}): MessagePkg {
        const $$createField2_0 = $$createType4;
        const $$createField3_0 = $$createType7;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("message" in $$parsedSource) {
            $$parsedSource["message"] = $$createField2_0($$parsedSource["message"]);
        }
        if ("files" in $$parsedSource) {
            $$parsedSource["files"] = $$createField3_0($$parsedSource["files"]);
        }
        return new MessagePkg($$parsedSource as Partial<MessagePkg>);
    }
}

export class Model {
    "id": number;
    "created_at": time$0.Time;
    "updated_at": time$0.Time;
    "deleted_at": gorm$0.DeletedAt;

    /**
     * 提供方id
     */
    "provider_id": number;
    "model": string;
    "owned_by": string;
    "object": string;
    "enable": boolean;
    "alias": string | null;

    /** Creates a new Model instance. */
    constructor($$source: Partial<Model> = {}) {
        if (!("id" in $$source)) {
            this["id"] = 0;
        }
        if (!("created_at" in $$source)) {
            this["created_at"] = null;
        }
        if (!("updated_at" in $$source)) {
            this["updated_at"] = null;
        }
        if (!("deleted_at" in $$source)) {
            this["deleted_at"] = null;
        }
        if (!("provider_id" in $$source)) {
            this["provider_id"] = 0;
        }
        if (!("model" in $$source)) {
            this["model"] = "";
        }
        if (!("owned_by" in $$source)) {
            this["owned_by"] = "";
        }
        if (!("object" in $$source)) {
            this["object"] = "";
        }
        if (!("enable" in $$source)) {
            this["enable"] = false;
        }
        if (!("alias" in $$source)) {
            this["alias"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Model instance from a string or object.
     */
    static createFrom($$source: any = {}): Model {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Model($$parsedSource as Partial<Model>);
    }
}

export class Provider {
    "id": number;
    "created_at": time$0.Time;
    "updated_at": time$0.Time;
    "deleted_at": gorm$0.DeletedAt;

    /**
     * 提供方名称
     */
    "provider_name": string;

    /**
     * 基础url
     */
    "base_url": string;

    /**
     * 文件上传url
     */
    "file_upload_base_url": string | null;

    /**
     * api key
     */
    "api_key": string;

    /**
     * 启用
     */
    "enable": boolean;
    "default_model_id": number | null;
    "models": Model[];
    "provider_type": data_models$0.ProviderType;

    /** Creates a new Provider instance. */
    constructor($$source: Partial<Provider> = {}) {
        if (!("id" in $$source)) {
            this["id"] = 0;
        }
        if (!("created_at" in $$source)) {
            this["created_at"] = null;
        }
        if (!("updated_at" in $$source)) {
            this["updated_at"] = null;
        }
        if (!("deleted_at" in $$source)) {
            this["deleted_at"] = null;
        }
        if (!("provider_name" in $$source)) {
            this["provider_name"] = "";
        }
        if (!("base_url" in $$source)) {
            this["base_url"] = "";
        }
        if (!("file_upload_base_url" in $$source)) {
            this["file_upload_base_url"] = null;
        }
        if (!("api_key" in $$source)) {
            this["api_key"] = "";
        }
        if (!("enable" in $$source)) {
            this["enable"] = false;
        }
        if (!("default_model_id" in $$source)) {
            this["default_model_id"] = null;
        }
        if (!("models" in $$source)) {
            this["models"] = [];
        }
        if (!("provider_type" in $$source)) {
            this["provider_type"] = data_models$0.ProviderType.$zero;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Provider instance from a string or object.
     */
    static createFrom($$source: any = {}): Provider {
        const $$createField10_0 = $$createType9;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("models" in $$parsedSource) {
            $$parsedSource["models"] = $$createField10_0($$parsedSource["models"]);
        }
        return new Provider($$parsedSource as Partial<Provider>);
    }
}

export class SupportProvider {
    "provider_type": data_models$0.ProviderType;
    "icon": string;
    "name": string;
    "base_url": string;
    "file_upload_base_url": string | null;
    "description": string;

    /** Creates a new SupportProvider instance. */
    constructor($$source: Partial<SupportProvider> = {}) {
        if (!("provider_type" in $$source)) {
            this["provider_type"] = data_models$0.ProviderType.$zero;
        }
        if (!("icon" in $$source)) {
            this["icon"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("base_url" in $$source)) {
            this["base_url"] = "";
        }
        if (!("file_upload_base_url" in $$source)) {
            this["file_upload_base_url"] = null;
        }
        if (!("description" in $$source)) {
            this["description"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SupportProvider instance from a string or object.
     */
    static createFrom($$source: any = {}): SupportProvider {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SupportProvider($$parsedSource as Partial<SupportProvider>);
    }
}

// Private type creation functions
const $$createType0 = MatchMessage.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = Chat.createFrom;
const $$createType3 = $Create.Array($$createType2);
const $$createType4 = schema$0.Message.createFrom;
const $$createType5 = $Create.Array($$createType4);
const $$createType6 = File.createFrom;
const $$createType7 = $Create.Array($$createType6);
const $$createType8 = Model.createFrom;
const $$createType9 = $Create.Array($$createType8);
