// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Memory exposes long-term memory management operations to the frontend.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as memory_dto$0 from "./memory_dto/models.js";

/**
 * CreateMemory creates a manual long-term memory.
 */
export function CreateMemory(input: memory_dto$0.CreateMemoryInput): $CancellablePromise<memory_dto$0.CreateMemoryOutput | null> {
    return $Call.ByID(2134585679, input).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * ForgetMemory hides a memory from future retrieval without deleting the row.
 */
export function ForgetMemory(input: memory_dto$0.ForgetMemoryInput): $CancellablePromise<memory_dto$0.ForgetMemoryOutput | null> {
    return $Call.ByID(3514604890, input).then(($result: any) => {
        return $$createType3($result);
    });
}

/**
 * GetMemory returns one memory by id.
 */
export function GetMemory(input: memory_dto$0.GetMemoryInput): $CancellablePromise<memory_dto$0.GetMemoryOutput | null> {
    return $Call.ByID(491824951, input).then(($result: any) => {
        return $$createType5($result);
    });
}

/**
 * GetMemorySettings loads the persisted memory feature switch.
 */
export function GetMemorySettings(input: memory_dto$0.GetMemorySettingsInput): $CancellablePromise<memory_dto$0.GetMemorySettingsOutput | null> {
    return $Call.ByID(2745096938, input).then(($result: any) => {
        return $$createType7($result);
    });
}

/**
 * GetMemoryStats returns aggregate counts for the memory settings page.
 */
export function GetMemoryStats(input: memory_dto$0.GetMemoryStatsInput): $CancellablePromise<memory_dto$0.GetMemoryStatsOutput | null> {
    return $Call.ByID(985845946, input).then(($result: any) => {
        return $$createType9($result);
    });
}

/**
 * ListMemories returns paginated long-term memories for the management page.
 */
export function ListMemories(input: memory_dto$0.ListMemoriesInput): $CancellablePromise<memory_dto$0.ListMemoriesOutput | null> {
    return $Call.ByID(3639675667, input).then(($result: any) => {
        return $$createType11($result);
    });
}

/**
 * RestoreMemory reactivates a forgotten memory.
 */
export function RestoreMemory(input: memory_dto$0.RestoreMemoryInput): $CancellablePromise<memory_dto$0.RestoreMemoryOutput | null> {
    return $Call.ByID(545546613, input).then(($result: any) => {
        return $$createType13($result);
    });
}

/**
 * SaveMemorySettings persists the memory feature switch.
 */
export function SaveMemorySettings(input: memory_dto$0.SaveMemorySettingsInput): $CancellablePromise<memory_dto$0.SaveMemorySettingsOutput | null> {
    return $Call.ByID(3685509243, input).then(($result: any) => {
        return $$createType15($result);
    });
}

/**
 * UpdateMemory updates editable fields on a long-term memory.
 */
export function UpdateMemory(input: memory_dto$0.UpdateMemoryInput): $CancellablePromise<memory_dto$0.UpdateMemoryOutput | null> {
    return $Call.ByID(1968651778, input).then(($result: any) => {
        return $$createType17($result);
    });
}

// Private type creation functions
const $$createType0 = memory_dto$0.CreateMemoryOutput.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = memory_dto$0.ForgetMemoryOutput.createFrom;
const $$createType3 = $Create.Nullable($$createType2);
const $$createType4 = memory_dto$0.GetMemoryOutput.createFrom;
const $$createType5 = $Create.Nullable($$createType4);
const $$createType6 = memory_dto$0.GetMemorySettingsOutput.createFrom;
const $$createType7 = $Create.Nullable($$createType6);
const $$createType8 = memory_dto$0.GetMemoryStatsOutput.createFrom;
const $$createType9 = $Create.Nullable($$createType8);
const $$createType10 = memory_dto$0.ListMemoriesOutput.createFrom;
const $$createType11 = $Create.Nullable($$createType10);
const $$createType12 = memory_dto$0.RestoreMemoryOutput.createFrom;
const $$createType13 = $Create.Nullable($$createType12);
const $$createType14 = memory_dto$0.SaveMemorySettingsOutput.createFrom;
const $$createType15 = $Create.Nullable($$createType14);
const $$createType16 = memory_dto$0.UpdateMemoryOutput.createFrom;
const $$createType17 = $Create.Nullable($$createType16);
