// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as time$0 from "../../../../../../../../time/models.js";

/**
 * DismissNotificationInput identifies the notification to remove.
 */
export class DismissNotificationInput {
    "id": number;

    /** Creates a new DismissNotificationInput instance. */
    constructor($$source: Partial<DismissNotificationInput> = {}) {
        if (!("id" in $$source)) {
            this["id"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DismissNotificationInput instance from a string or object.
     */
    static createFrom($$source: any = {}): DismissNotificationInput {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new DismissNotificationInput($$parsedSource as Partial<DismissNotificationInput>);
    }
}

/**
 * DismissNotificationOutput is returned after deletion.
 */
export class DismissNotificationOutput {

    /** Creates a new DismissNotificationOutput instance. */
    constructor($$source: Partial<DismissNotificationOutput> = {}) {

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DismissNotificationOutput instance from a string or object.
     */
    static createFrom($$source: any = {}): DismissNotificationOutput {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new DismissNotificationOutput($$parsedSource as Partial<DismissNotificationOutput>);
    }
}

/**
 * ListNotificationsInput controls whether resolved notifications are included.
 */
export class ListNotificationsInput {
    "include_resolved": boolean;

    /** Creates a new ListNotificationsInput instance. */
    constructor($$source: Partial<ListNotificationsInput> = {}) {
        if (!("include_resolved" in $$source)) {
            this["include_resolved"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ListNotificationsInput instance from a string or object.
     */
    static createFrom($$source: any = {}): ListNotificationsInput {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ListNotificationsInput($$parsedSource as Partial<ListNotificationsInput>);
    }
}

/**
 * ListNotificationsOutput wraps the notification list.
 */
export class ListNotificationsOutput {
    "items": NotificationItem[];

    /** Creates a new ListNotificationsOutput instance. */
    constructor($$source: Partial<ListNotificationsOutput> = {}) {
        if (!("items" in $$source)) {
            this["items"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ListNotificationsOutput instance from a string or object.
     */
    static createFrom($$source: any = {}): ListNotificationsOutput {
        const $$createField0_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("items" in $$parsedSource) {
            $$parsedSource["items"] = $$createField0_0($$parsedSource["items"]);
        }
        return new ListNotificationsOutput($$parsedSource as Partial<ListNotificationsOutput>);
    }
}

/**
 * NotificationItem is the frontend-facing notification DTO.
 */
export class NotificationItem {
    "id": number;
    "session_id": number;
    "kind": string;
    "title": string;
    "message": string;
    "created_at": time$0.Time;
    "resolved_at"?: time$0.Time | null;

    /** Creates a new NotificationItem instance. */
    constructor($$source: Partial<NotificationItem> = {}) {
        if (!("id" in $$source)) {
            this["id"] = 0;
        }
        if (!("session_id" in $$source)) {
            this["session_id"] = 0;
        }
        if (!("kind" in $$source)) {
            this["kind"] = "";
        }
        if (!("title" in $$source)) {
            this["title"] = "";
        }
        if (!("message" in $$source)) {
            this["message"] = "";
        }
        if (!("created_at" in $$source)) {
            this["created_at"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new NotificationItem instance from a string or object.
     */
    static createFrom($$source: any = {}): NotificationItem {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new NotificationItem($$parsedSource as Partial<NotificationItem>);
    }
}

/**
 * NotifyInput defines the payload for creating a notification.
 */
export class NotifyInput {
    "session_id": number;
    "kind": string;
    "title": string;
    "message": string;

    /** Creates a new NotifyInput instance. */
    constructor($$source: Partial<NotifyInput> = {}) {
        if (!("session_id" in $$source)) {
            this["session_id"] = 0;
        }
        if (!("kind" in $$source)) {
            this["kind"] = "";
        }
        if (!("title" in $$source)) {
            this["title"] = "";
        }
        if (!("message" in $$source)) {
            this["message"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new NotifyInput instance from a string or object.
     */
    static createFrom($$source: any = {}): NotifyInput {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new NotifyInput($$parsedSource as Partial<NotifyInput>);
    }
}

/**
 * NotifyOutput returns the created notification identifier.
 */
export class NotifyOutput {
    "notification_id": number;

    /** Creates a new NotifyOutput instance. */
    constructor($$source: Partial<NotifyOutput> = {}) {
        if (!("notification_id" in $$source)) {
            this["notification_id"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new NotifyOutput instance from a string or object.
     */
    static createFrom($$source: any = {}): NotifyOutput {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new NotifyOutput($$parsedSource as Partial<NotifyOutput>);
    }
}

/**
 * ResolveNotificationInput identifies the notification to resolve.
 */
export class ResolveNotificationInput {
    "id": number;

    /** Creates a new ResolveNotificationInput instance. */
    constructor($$source: Partial<ResolveNotificationInput> = {}) {
        if (!("id" in $$source)) {
            this["id"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ResolveNotificationInput instance from a string or object.
     */
    static createFrom($$source: any = {}): ResolveNotificationInput {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ResolveNotificationInput($$parsedSource as Partial<ResolveNotificationInput>);
    }
}

/**
 * ResolveNotificationOutput is returned after a resolve or reject action completes.
 */
export class ResolveNotificationOutput {

    /** Creates a new ResolveNotificationOutput instance. */
    constructor($$source: Partial<ResolveNotificationOutput> = {}) {

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ResolveNotificationOutput instance from a string or object.
     */
    static createFrom($$source: any = {}): ResolveNotificationOutput {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ResolveNotificationOutput($$parsedSource as Partial<ResolveNotificationOutput>);
    }
}

// Private type creation functions
const $$createType0 = NotificationItem.createFrom;
const $$createType1 = $Create.Array($$createType0);
