// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * ChatMessageAudioURL is used to represent an audio part in a chat message.
 * Choose either URL or URI.
 * If your model implementation supports it, URL could be used to embed inline audio data as defined in RFC-2397.
 */
export class ChatMessageAudioURL {
    /**
     * URL can either be a traditional URL or a special URL conforming to RFC-2397 (https://www.rfc-editor.org/rfc/rfc2397).
     * double check with model implementations for detailed instructions on how to use this.
     */
    "url"?: string;
    "uri"?: string;

    /**
     * MIMEType is the mime type of the audio, eg. "audio/wav" or "audio/ogg".
     */
    "mime_type"?: string;

    /**
     * Extra is used to store extra information for the audio url.
     */
    "extra"?: { [_: string]: any };

    /** Creates a new ChatMessageAudioURL instance. */
    constructor($$source: Partial<ChatMessageAudioURL> = {}) {

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ChatMessageAudioURL instance from a string or object.
     */
    static createFrom($$source: any = {}): ChatMessageAudioURL {
        const $$createField3_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("extra" in $$parsedSource) {
            $$parsedSource["extra"] = $$createField3_0($$parsedSource["extra"]);
        }
        return new ChatMessageAudioURL($$parsedSource as Partial<ChatMessageAudioURL>);
    }
}

/**
 * ChatMessageFileURL is used to represent an file part in a chat message.
 * Choose either URL or URI.
 */
export class ChatMessageFileURL {
    "url"?: string;
    "uri"?: string;

    /**
     * MIMEType is the mime type of the file, eg. "application/pdf", "text/plain".
     */
    "mime_type"?: string;

    /**
     * Name is the name of the file.
     */
    "name"?: string;

    /**
     * Extra is used to store extra information for the file url.
     */
    "extra"?: { [_: string]: any };

    /** Creates a new ChatMessageFileURL instance. */
    constructor($$source: Partial<ChatMessageFileURL> = {}) {

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ChatMessageFileURL instance from a string or object.
     */
    static createFrom($$source: any = {}): ChatMessageFileURL {
        const $$createField4_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("extra" in $$parsedSource) {
            $$parsedSource["extra"] = $$createField4_0($$parsedSource["extra"]);
        }
        return new ChatMessageFileURL($$parsedSource as Partial<ChatMessageFileURL>);
    }
}

/**
 * ChatMessageImageURL is used to represent an image part in a chat message.
 * Choose either URL or URI.
 * If your model implementation supports it, URL could be used to embed inline image data as defined in RFC-2397.
 */
export class ChatMessageImageURL {
    /**
     * URL can either be a traditional URL or a special URL conforming to RFC-2397 (https://www.rfc-editor.org/rfc/rfc2397).
     * double check with model implementations for detailed instructions on how to use this.
     */
    "url"?: string;
    "uri"?: string;

    /**
     * Detail is the quality of the image url.
     */
    "detail"?: ImageURLDetail;

    /**
     * MIMEType is the mime type of the image, eg. "image/png".
     */
    "mime_type"?: string;

    /**
     * Extra is used to store extra information for the image url.
     */
    "extra"?: { [_: string]: any };

    /** Creates a new ChatMessageImageURL instance. */
    constructor($$source: Partial<ChatMessageImageURL> = {}) {

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ChatMessageImageURL instance from a string or object.
     */
    static createFrom($$source: any = {}): ChatMessageImageURL {
        const $$createField4_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("extra" in $$parsedSource) {
            $$parsedSource["extra"] = $$createField4_0($$parsedSource["extra"]);
        }
        return new ChatMessageImageURL($$parsedSource as Partial<ChatMessageImageURL>);
    }
}

/**
 * ChatMessagePart is the part in a chat message.
 */
export class ChatMessagePart {
    /**
     * Type is the type of the part, eg. "text", "image_url", "audio_url", "video_url", "file_url".
     */
    "type"?: ChatMessagePartType;

    /**
     * Text is the text of the part, it's used when Type is "text".
     */
    "text"?: string;

    /**
     * ImageURL is the image url of the part, it's used when Type is "image_url".
     */
    "image_url"?: ChatMessageImageURL | null;

    /**
     * AudioURL is the audio url of the part, it's used when Type is "audio_url".
     */
    "audio_url"?: ChatMessageAudioURL | null;

    /**
     * VideoURL is the video url of the part, it's used when Type is "video_url".
     */
    "video_url"?: ChatMessageVideoURL | null;

    /**
     * FileURL is the file url of the part, it's used when Type is "file_url".
     */
    "file_url"?: ChatMessageFileURL | null;

    /** Creates a new ChatMessagePart instance. */
    constructor($$source: Partial<ChatMessagePart> = {}) {

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ChatMessagePart instance from a string or object.
     */
    static createFrom($$source: any = {}): ChatMessagePart {
        const $$createField2_0 = $$createType2;
        const $$createField3_0 = $$createType4;
        const $$createField4_0 = $$createType6;
        const $$createField5_0 = $$createType8;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("image_url" in $$parsedSource) {
            $$parsedSource["image_url"] = $$createField2_0($$parsedSource["image_url"]);
        }
        if ("audio_url" in $$parsedSource) {
            $$parsedSource["audio_url"] = $$createField3_0($$parsedSource["audio_url"]);
        }
        if ("video_url" in $$parsedSource) {
            $$parsedSource["video_url"] = $$createField4_0($$parsedSource["video_url"]);
        }
        if ("file_url" in $$parsedSource) {
            $$parsedSource["file_url"] = $$createField5_0($$parsedSource["file_url"]);
        }
        return new ChatMessagePart($$parsedSource as Partial<ChatMessagePart>);
    }
}

/**
 * ChatMessagePartType is the type of the part in a chat message.
 */
export enum ChatMessagePartType {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    /**
     * ChatMessagePartTypeText means the part is a text.
     */
    ChatMessagePartTypeText = "text",

    /**
     * ChatMessagePartTypeImageURL means the part is an image url.
     */
    ChatMessagePartTypeImageURL = "image_url",

    /**
     * ChatMessagePartTypeAudioURL means the part is an audio url.
     */
    ChatMessagePartTypeAudioURL = "audio_url",

    /**
     * ChatMessagePartTypeVideoURL means the part is a video url.
     */
    ChatMessagePartTypeVideoURL = "video_url",

    /**
     * ChatMessagePartTypeFileURL means the part is a file url.
     */
    ChatMessagePartTypeFileURL = "file_url",
};

/**
 * ChatMessageVideoURL is used to represent an video part in a chat message.
 * Choose either URL or URI.
 * If your model implementation supports it, URL could be used to embed inline video data as defined in RFC-2397.
 */
export class ChatMessageVideoURL {
    /**
     * URL can either be a traditional URL or a special URL conforming to RFC-2397 (https://www.rfc-editor.org/rfc/rfc2397).
     * double check with model implementations for detailed instructions on how to use this.
     */
    "url"?: string;
    "uri"?: string;

    /**
     * MIMEType is the mime type of the video, eg. "video/mp4".
     */
    "mime_type"?: string;

    /**
     * Extra is used to store extra information for the video url.
     */
    "extra"?: { [_: string]: any };

    /** Creates a new ChatMessageVideoURL instance. */
    constructor($$source: Partial<ChatMessageVideoURL> = {}) {

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ChatMessageVideoURL instance from a string or object.
     */
    static createFrom($$source: any = {}): ChatMessageVideoURL {
        const $$createField3_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("extra" in $$parsedSource) {
            $$parsedSource["extra"] = $$createField3_0($$parsedSource["extra"]);
        }
        return new ChatMessageVideoURL($$parsedSource as Partial<ChatMessageVideoURL>);
    }
}

/**
 * FunctionCall is the function call in a message.
 * It's used in Assistant Message.
 */
export class FunctionCall {
    /**
     * Name is the name of the function to call, it can be used to identify the specific function.
     */
    "name"?: string;

    /**
     * Arguments is the arguments to call the function with, in JSON format.
     */
    "arguments"?: string;

    /** Creates a new FunctionCall instance. */
    constructor($$source: Partial<FunctionCall> = {}) {

        Object.assign(this, $$source);
    }

    /**
     * Creates a new FunctionCall instance from a string or object.
     */
    static createFrom($$source: any = {}): FunctionCall {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new FunctionCall($$parsedSource as Partial<FunctionCall>);
    }
}

/**
 * ImageURLDetail is the detail of the image url.
 */
export enum ImageURLDetail {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    /**
     * ImageURLDetailHigh means the high quality image url.
     */
    ImageURLDetailHigh = "high",

    /**
     * ImageURLDetailLow means the low quality image url.
     */
    ImageURLDetailLow = "low",

    /**
     * ImageURLDetailAuto means the auto quality image url.
     */
    ImageURLDetailAuto = "auto",
};

/**
 * LogProb represents the probability information for a token.
 */
export class LogProb {
    /**
     * Token represents the text of the token, which is a contiguous sequence of characters
     * (e.g., a word, part of a word, or punctuation) as understood by the tokenization process used by the language model.
     */
    "token": string;

    /**
     * LogProb is the log probability of this token, if it is within the top 20 most likely tokens.
     * Otherwise, the value `-9999.0` is used to signify that the token is very unlikely.
     */
    "logprob": number;

    /**
     * Bytes is a list of integers representing the UTF-8 bytes representation of the token.
     * Useful in instances where characters are represented by multiple tokens and
     * their byte representations must be combined to generate the correct text
     * representation. Can be `null` if there is no bytes representation for the token.
     * Omitting the field if it is null
     */
    "bytes"?: number[];

    /**
     * TopLogProbs is a list of the most likely tokens and their log probability, at this token position.
     * In rare cases, there may be fewer than the number of requested top_logprobs returned.
     */
    "top_logprobs": TopLogProb[];

    /** Creates a new LogProb instance. */
    constructor($$source: Partial<LogProb> = {}) {
        if (!("token" in $$source)) {
            this["token"] = "";
        }
        if (!("logprob" in $$source)) {
            this["logprob"] = 0;
        }
        if (!("top_logprobs" in $$source)) {
            this["top_logprobs"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new LogProb instance from a string or object.
     */
    static createFrom($$source: any = {}): LogProb {
        const $$createField2_0 = $$createType9;
        const $$createField3_0 = $$createType11;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("bytes" in $$parsedSource) {
            $$parsedSource["bytes"] = $$createField2_0($$parsedSource["bytes"]);
        }
        if ("top_logprobs" in $$parsedSource) {
            $$parsedSource["top_logprobs"] = $$createField3_0($$parsedSource["top_logprobs"]);
        }
        return new LogProb($$parsedSource as Partial<LogProb>);
    }
}

/**
 * LogProbs is the top-level structure containing the log probability information.
 */
export class LogProbs {
    /**
     * Content is a list of message content tokens with log probability information.
     */
    "content": LogProb[];

    /** Creates a new LogProbs instance. */
    constructor($$source: Partial<LogProbs> = {}) {
        if (!("content" in $$source)) {
            this["content"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new LogProbs instance from a string or object.
     */
    static createFrom($$source: any = {}): LogProbs {
        const $$createField0_0 = $$createType13;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("content" in $$parsedSource) {
            $$parsedSource["content"] = $$createField0_0($$parsedSource["content"]);
        }
        return new LogProbs($$parsedSource as Partial<LogProbs>);
    }
}

export class Message {
    "role": RoleType;
    "content": string;

    /**
     * if MultiContent is not empty, use this instead of Content
     * if MultiContent is empty, use Content
     */
    "multi_content"?: ChatMessagePart[];
    "name"?: string;

    /**
     * only for AssistantMessage
     */
    "tool_calls"?: ToolCall[];

    /**
     * only for ToolMessage
     */
    "tool_call_id"?: string;

    /**
     * only for ToolMessage
     */
    "tool_name"?: string;
    "response_meta"?: ResponseMeta | null;

    /**
     * ReasoningContent is the thinking process of the model, which will be included when the model returns reasoning content.
     */
    "reasoning_content"?: string;

    /**
     * customized information for model implementation
     */
    "extra"?: { [_: string]: any };

    /** Creates a new Message instance. */
    constructor($$source: Partial<Message> = {}) {
        if (!("role" in $$source)) {
            this["role"] = RoleType.$zero;
        }
        if (!("content" in $$source)) {
            this["content"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Message instance from a string or object.
     */
    static createFrom($$source: any = {}): Message {
        const $$createField2_0 = $$createType15;
        const $$createField4_0 = $$createType17;
        const $$createField7_0 = $$createType19;
        const $$createField9_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("multi_content" in $$parsedSource) {
            $$parsedSource["multi_content"] = $$createField2_0($$parsedSource["multi_content"]);
        }
        if ("tool_calls" in $$parsedSource) {
            $$parsedSource["tool_calls"] = $$createField4_0($$parsedSource["tool_calls"]);
        }
        if ("response_meta" in $$parsedSource) {
            $$parsedSource["response_meta"] = $$createField7_0($$parsedSource["response_meta"]);
        }
        if ("extra" in $$parsedSource) {
            $$parsedSource["extra"] = $$createField9_0($$parsedSource["extra"]);
        }
        return new Message($$parsedSource as Partial<Message>);
    }
}

export class PromptTokenDetails {
    /**
     * Cached tokens present in the prompt.
     */
    "cached_tokens": number;

    /** Creates a new PromptTokenDetails instance. */
    constructor($$source: Partial<PromptTokenDetails> = {}) {
        if (!("cached_tokens" in $$source)) {
            this["cached_tokens"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PromptTokenDetails instance from a string or object.
     */
    static createFrom($$source: any = {}): PromptTokenDetails {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new PromptTokenDetails($$parsedSource as Partial<PromptTokenDetails>);
    }
}

/**
 * ResponseMeta collects meta information about a chat response.
 */
export class ResponseMeta {
    /**
     * FinishReason is the reason why the chat response is finished.
     * It's usually "stop", "length", "tool_calls", "content_filter", "null". This is defined by chat model implementation.
     */
    "finish_reason"?: string;

    /**
     * Usage is the token usage of the chat response, whether usage exists depends on whether the chat model implementation returns.
     */
    "usage"?: TokenUsage | null;

    /**
     * LogProbs is Log probability information.
     */
    "logprobs"?: LogProbs | null;

    /** Creates a new ResponseMeta instance. */
    constructor($$source: Partial<ResponseMeta> = {}) {

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ResponseMeta instance from a string or object.
     */
    static createFrom($$source: any = {}): ResponseMeta {
        const $$createField1_0 = $$createType21;
        const $$createField2_0 = $$createType23;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("usage" in $$parsedSource) {
            $$parsedSource["usage"] = $$createField1_0($$parsedSource["usage"]);
        }
        if ("logprobs" in $$parsedSource) {
            $$parsedSource["logprobs"] = $$createField2_0($$parsedSource["logprobs"]);
        }
        return new ResponseMeta($$parsedSource as Partial<ResponseMeta>);
    }
}

/**
 * RoleType is the type of the role of a message.
 */
export enum RoleType {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    /**
     * Assistant is the role of an assistant, means the message is returned by ChatModel.
     */
    Assistant = "assistant",

    /**
     * User is the role of a user, means the message is a user message.
     */
    User = "user",

    /**
     * System is the role of a system, means the message is a system message.
     */
    System = "system",

    /**
     * Tool is the role of a tool, means the message is a tool call output.
     */
    Tool = "tool",
};

/**
 * TokenUsage Represents the token usage of chat model request.
 */
export class TokenUsage {
    /**
     * PromptTokens is the number of prompt tokens, including all the input tokens of this request.
     */
    "prompt_tokens": number;

    /**
     * PromptTokenDetails is a breakdown of the prompt tokens.
     */
    "prompt_token_details": PromptTokenDetails;

    /**
     * CompletionTokens is the number of completion tokens.
     */
    "completion_tokens": number;

    /**
     * TotalTokens is the total number of tokens.
     */
    "total_tokens": number;

    /** Creates a new TokenUsage instance. */
    constructor($$source: Partial<TokenUsage> = {}) {
        if (!("prompt_tokens" in $$source)) {
            this["prompt_tokens"] = 0;
        }
        if (!("prompt_token_details" in $$source)) {
            this["prompt_token_details"] = (new PromptTokenDetails());
        }
        if (!("completion_tokens" in $$source)) {
            this["completion_tokens"] = 0;
        }
        if (!("total_tokens" in $$source)) {
            this["total_tokens"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TokenUsage instance from a string or object.
     */
    static createFrom($$source: any = {}): TokenUsage {
        const $$createField1_0 = $$createType24;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("prompt_token_details" in $$parsedSource) {
            $$parsedSource["prompt_token_details"] = $$createField1_0($$parsedSource["prompt_token_details"]);
        }
        return new TokenUsage($$parsedSource as Partial<TokenUsage>);
    }
}

/**
 * ToolCall is the tool call in a message.
 * It's used in Assistant Message when there are tool calls should be made.
 */
export class ToolCall {
    /**
     * Index is used when there are multiple tool calls in a message.
     * In stream mode, it's used to identify the chunk of the tool call for merging.
     */
    "index"?: number | null;

    /**
     * ID is the id of the tool call, it can be used to identify the specific tool call.
     */
    "id": string;

    /**
     * Type is the type of the tool call, default is "function".
     */
    "type": string;

    /**
     * Function is the function call to be made.
     */
    "function": FunctionCall;

    /**
     * Extra is used to store extra information for the tool call.
     */
    "extra"?: { [_: string]: any };

    /** Creates a new ToolCall instance. */
    constructor($$source: Partial<ToolCall> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("type" in $$source)) {
            this["type"] = "";
        }
        if (!("function" in $$source)) {
            this["function"] = (new FunctionCall());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ToolCall instance from a string or object.
     */
    static createFrom($$source: any = {}): ToolCall {
        const $$createField3_0 = $$createType25;
        const $$createField4_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("function" in $$parsedSource) {
            $$parsedSource["function"] = $$createField3_0($$parsedSource["function"]);
        }
        if ("extra" in $$parsedSource) {
            $$parsedSource["extra"] = $$createField4_0($$parsedSource["extra"]);
        }
        return new ToolCall($$parsedSource as Partial<ToolCall>);
    }
}

export class TopLogProb {
    /**
     * Token represents the text of the token, which is a contiguous sequence of characters
     * (e.g., a word, part of a word, or punctuation) as understood by the tokenization process used by the language model.
     */
    "token": string;

    /**
     * LogProb is the log probability of this token, if it is within the top 20 most likely tokens.
     * Otherwise, the value `-9999.0` is used to signify that the token is very unlikely.
     */
    "logprob": number;

    /**
     * Bytes is a list of integers representing the UTF-8 bytes representation of the token.
     * Useful in instances where characters are represented by multiple tokens and
     * their byte representations must be combined to generate the correct text
     * representation. Can be `null` if there is no bytes representation for the token.
     */
    "bytes"?: number[];

    /** Creates a new TopLogProb instance. */
    constructor($$source: Partial<TopLogProb> = {}) {
        if (!("token" in $$source)) {
            this["token"] = "";
        }
        if (!("logprob" in $$source)) {
            this["logprob"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TopLogProb instance from a string or object.
     */
    static createFrom($$source: any = {}): TopLogProb {
        const $$createField2_0 = $$createType9;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("bytes" in $$parsedSource) {
            $$parsedSource["bytes"] = $$createField2_0($$parsedSource["bytes"]);
        }
        return new TopLogProb($$parsedSource as Partial<TopLogProb>);
    }
}

// Private type creation functions
const $$createType0 = $Create.Map($Create.Any, $Create.Any);
const $$createType1 = ChatMessageImageURL.createFrom;
const $$createType2 = $Create.Nullable($$createType1);
const $$createType3 = ChatMessageAudioURL.createFrom;
const $$createType4 = $Create.Nullable($$createType3);
const $$createType5 = ChatMessageVideoURL.createFrom;
const $$createType6 = $Create.Nullable($$createType5);
const $$createType7 = ChatMessageFileURL.createFrom;
const $$createType8 = $Create.Nullable($$createType7);
const $$createType9 = $Create.Array($Create.Any);
const $$createType10 = TopLogProb.createFrom;
const $$createType11 = $Create.Array($$createType10);
const $$createType12 = LogProb.createFrom;
const $$createType13 = $Create.Array($$createType12);
const $$createType14 = ChatMessagePart.createFrom;
const $$createType15 = $Create.Array($$createType14);
const $$createType16 = ToolCall.createFrom;
const $$createType17 = $Create.Array($$createType16);
const $$createType18 = ResponseMeta.createFrom;
const $$createType19 = $Create.Nullable($$createType18);
const $$createType20 = TokenUsage.createFrom;
const $$createType21 = $Create.Nullable($$createType20);
const $$createType22 = LogProbs.createFrom;
const $$createType23 = $Create.Nullable($$createType22);
const $$createType24 = PromptTokenDetails.createFrom;
const $$createType25 = FunctionCall.createFrom;
