// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        v5.29.3
// source: rpc/service/auth.proto

package service

import (
	common "gitlab.linhf.cn/project/lemontea/lemon_tea_desktop/rpc/common"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// FieldType 字段类型枚举
type FieldType int32

const (
	FieldType_FIELD_TYPE_UNSPECIFIED FieldType = 0
	FieldType_FIELD_TYPE_USERNAME    FieldType = 1
	FieldType_FIELD_TYPE_EMAIL       FieldType = 2
)

// Enum value maps for FieldType.
var (
	FieldType_name = map[int32]string{
		0: "FIELD_TYPE_UNSPECIFIED",
		1: "FIELD_TYPE_USERNAME",
		2: "FIELD_TYPE_EMAIL",
	}
	FieldType_value = map[string]int32{
		"FIELD_TYPE_UNSPECIFIED": 0,
		"FIELD_TYPE_USERNAME":    1,
		"FIELD_TYPE_EMAIL":       2,
	}
)

func (x FieldType) Enum() *FieldType {
	p := new(FieldType)
	*p = x
	return p
}

func (x FieldType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FieldType) Descriptor() protoreflect.EnumDescriptor {
	return file_rpc_service_auth_proto_enumTypes[0].Descriptor()
}

func (FieldType) Type() protoreflect.EnumType {
	return &file_rpc_service_auth_proto_enumTypes[0]
}

func (x FieldType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use FieldType.Descriptor instead.
func (FieldType) EnumDescriptor() ([]byte, []int) {
	return file_rpc_service_auth_proto_rawDescGZIP(), []int{0}
}

// SendEmailVerificationCodeRequest 发送邮件验证码请求
type SendEmailVerificationCodeRequest struct {
	state         protoimpl.MessageState      `protogen:"open.v1"`
	Email         string                      `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"` // 邮箱地址
	Username      string                      `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	CodeType      common.VerificationCodeType `protobuf:"varint,3,opt,name=code_type,json=codeType,proto3,enum=lemon_tea.common.VerificationCodeType" json:"code_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendEmailVerificationCodeRequest) Reset() {
	*x = SendEmailVerificationCodeRequest{}
	mi := &file_rpc_service_auth_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendEmailVerificationCodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendEmailVerificationCodeRequest) ProtoMessage() {}

func (x *SendEmailVerificationCodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_service_auth_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendEmailVerificationCodeRequest.ProtoReflect.Descriptor instead.
func (*SendEmailVerificationCodeRequest) Descriptor() ([]byte, []int) {
	return file_rpc_service_auth_proto_rawDescGZIP(), []int{0}
}

func (x *SendEmailVerificationCodeRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *SendEmailVerificationCodeRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *SendEmailVerificationCodeRequest) GetCodeType() common.VerificationCodeType {
	if x != nil {
		return x.CodeType
	}
	return common.VerificationCodeType(0)
}

// SendEmailVerificationCodeResponse 发送邮件验证码返回
type SendEmailVerificationCodeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"` // 是否成功
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`  // 响应消息
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendEmailVerificationCodeResponse) Reset() {
	*x = SendEmailVerificationCodeResponse{}
	mi := &file_rpc_service_auth_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendEmailVerificationCodeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendEmailVerificationCodeResponse) ProtoMessage() {}

func (x *SendEmailVerificationCodeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_service_auth_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendEmailVerificationCodeResponse.ProtoReflect.Descriptor instead.
func (*SendEmailVerificationCodeResponse) Descriptor() ([]byte, []int) {
	return file_rpc_service_auth_proto_rawDescGZIP(), []int{1}
}

func (x *SendEmailVerificationCodeResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *SendEmailVerificationCodeResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// CheckFieldAvailabilityRequest 检查字段可用性请求
type CheckFieldAvailabilityRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FieldType     FieldType              `protobuf:"varint,1,opt,name=field_type,json=fieldType,proto3,enum=lemon_tea.server.FieldType" json:"field_type,omitempty"` // 字段类型
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`                                                           // 字段值
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckFieldAvailabilityRequest) Reset() {
	*x = CheckFieldAvailabilityRequest{}
	mi := &file_rpc_service_auth_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckFieldAvailabilityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckFieldAvailabilityRequest) ProtoMessage() {}

func (x *CheckFieldAvailabilityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_service_auth_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckFieldAvailabilityRequest.ProtoReflect.Descriptor instead.
func (*CheckFieldAvailabilityRequest) Descriptor() ([]byte, []int) {
	return file_rpc_service_auth_proto_rawDescGZIP(), []int{2}
}

func (x *CheckFieldAvailabilityRequest) GetFieldType() FieldType {
	if x != nil {
		return x.FieldType
	}
	return FieldType_FIELD_TYPE_UNSPECIFIED
}

func (x *CheckFieldAvailabilityRequest) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

// CheckFieldAvailabilityResponse 检查字段可用性返回
type CheckFieldAvailabilityResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Available     bool                   `protobuf:"varint,1,opt,name=available,proto3" json:"available,omitempty"` // 是否可用
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckFieldAvailabilityResponse) Reset() {
	*x = CheckFieldAvailabilityResponse{}
	mi := &file_rpc_service_auth_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckFieldAvailabilityResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckFieldAvailabilityResponse) ProtoMessage() {}

func (x *CheckFieldAvailabilityResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_service_auth_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckFieldAvailabilityResponse.ProtoReflect.Descriptor instead.
func (*CheckFieldAvailabilityResponse) Descriptor() ([]byte, []int) {
	return file_rpc_service_auth_proto_rawDescGZIP(), []int{3}
}

func (x *CheckFieldAvailabilityResponse) GetAvailable() bool {
	if x != nil {
		return x.Available
	}
	return false
}

// RegisterRequest 注册请求
type RegisterRequest struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	Username              string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`                                                           // 用户名
	PasswordMd5           string                 `protobuf:"bytes,2,opt,name=password_md5,json=passwordMd5,proto3" json:"password_md5,omitempty"`                                  // 密码MD5
	Email                 string                 `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`                                                                 // 邮箱
	EmailVerificationCode int64                  `protobuf:"varint,4,opt,name=email_verification_code,json=emailVerificationCode,proto3" json:"email_verification_code,omitempty"` // 邮箱验证码
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *RegisterRequest) Reset() {
	*x = RegisterRequest{}
	mi := &file_rpc_service_auth_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequest) ProtoMessage() {}

func (x *RegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_service_auth_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRequest.ProtoReflect.Descriptor instead.
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return file_rpc_service_auth_proto_rawDescGZIP(), []int{4}
}

func (x *RegisterRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *RegisterRequest) GetPasswordMd5() string {
	if x != nil {
		return x.PasswordMd5
	}
	return ""
}

func (x *RegisterRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *RegisterRequest) GetEmailVerificationCode() int64 {
	if x != nil {
		return x.EmailVerificationCode
	}
	return 0
}

// RegisterResponse 注册返回
type RegisterResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`                  // 是否成功
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`                   // 响应消息
	UserId        *string                `protobuf:"bytes,3,opt,name=user_id,json=userId,proto3,oneof" json:"user_id,omitempty"` // 用户ID（成功时返回）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterResponse) Reset() {
	*x = RegisterResponse{}
	mi := &file_rpc_service_auth_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterResponse) ProtoMessage() {}

func (x *RegisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_service_auth_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterResponse.ProtoReflect.Descriptor instead.
func (*RegisterResponse) Descriptor() ([]byte, []int) {
	return file_rpc_service_auth_proto_rawDescGZIP(), []int{5}
}

func (x *RegisterResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RegisterResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *RegisterResponse) GetUserId() string {
	if x != nil && x.UserId != nil {
		return *x.UserId
	}
	return ""
}

// LoginRequest 登录请求
type LoginRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LoginField    string                 `protobuf:"bytes,1,opt,name=login_field,json=loginField,proto3" json:"login_field,omitempty"`    // 登录字段（用户名或邮箱）
	PasswordMd5   string                 `protobuf:"bytes,2,opt,name=password_md5,json=passwordMd5,proto3" json:"password_md5,omitempty"` // 密码MD5
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginRequest) Reset() {
	*x = LoginRequest{}
	mi := &file_rpc_service_auth_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginRequest) ProtoMessage() {}

func (x *LoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_service_auth_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginRequest.ProtoReflect.Descriptor instead.
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return file_rpc_service_auth_proto_rawDescGZIP(), []int{6}
}

func (x *LoginRequest) GetLoginField() string {
	if x != nil {
		return x.LoginField
	}
	return ""
}

func (x *LoginRequest) GetPasswordMd5() string {
	if x != nil {
		return x.PasswordMd5
	}
	return ""
}

// LoginResponse 登录返回
type LoginResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccessToken   *string                `protobuf:"bytes,1,opt,name=access_token,json=accessToken,proto3,oneof" json:"access_token,omitempty"` // 访问令牌
	ExpiresIn     *int64                 `protobuf:"varint,2,opt,name=expires_in,json=expiresIn,proto3,oneof" json:"expires_in,omitempty"`      // 令牌过期时间（秒）
	UserInfo      *UserInfo              `protobuf:"bytes,3,opt,name=user_info,json=userInfo,proto3,oneof" json:"user_info,omitempty"`          // 用户信息
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginResponse) Reset() {
	*x = LoginResponse{}
	mi := &file_rpc_service_auth_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginResponse) ProtoMessage() {}

func (x *LoginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_service_auth_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginResponse.ProtoReflect.Descriptor instead.
func (*LoginResponse) Descriptor() ([]byte, []int) {
	return file_rpc_service_auth_proto_rawDescGZIP(), []int{7}
}

func (x *LoginResponse) GetAccessToken() string {
	if x != nil && x.AccessToken != nil {
		return *x.AccessToken
	}
	return ""
}

func (x *LoginResponse) GetExpiresIn() int64 {
	if x != nil && x.ExpiresIn != nil {
		return *x.ExpiresIn
	}
	return 0
}

func (x *LoginResponse) GetUserInfo() *UserInfo {
	if x != nil {
		return x.UserInfo
	}
	return nil
}

// ResetPasswordRequest 重置密码请求
type ResetPasswordRequest struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	LoginField            string                 `protobuf:"bytes,1,opt,name=login_field,json=loginField,proto3" json:"login_field,omitempty"`                                    // 登录字段（用户名或邮箱）
	EmailVerificationCode string                 `protobuf:"bytes,2,opt,name=email_verification_code,json=emailVerificationCode,proto3" json:"email_verification_code,omitempty"` // 邮箱验证码
	NewPasswordMd5        string                 `protobuf:"bytes,3,opt,name=new_password_md5,json=newPasswordMd5,proto3" json:"new_password_md5,omitempty"`                      // 新密码MD5
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *ResetPasswordRequest) Reset() {
	*x = ResetPasswordRequest{}
	mi := &file_rpc_service_auth_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResetPasswordRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResetPasswordRequest) ProtoMessage() {}

func (x *ResetPasswordRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_service_auth_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResetPasswordRequest.ProtoReflect.Descriptor instead.
func (*ResetPasswordRequest) Descriptor() ([]byte, []int) {
	return file_rpc_service_auth_proto_rawDescGZIP(), []int{8}
}

func (x *ResetPasswordRequest) GetLoginField() string {
	if x != nil {
		return x.LoginField
	}
	return ""
}

func (x *ResetPasswordRequest) GetEmailVerificationCode() string {
	if x != nil {
		return x.EmailVerificationCode
	}
	return ""
}

func (x *ResetPasswordRequest) GetNewPasswordMd5() string {
	if x != nil {
		return x.NewPasswordMd5
	}
	return ""
}

// LogoutRequest 登出请求
type LogoutRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogoutRequest) Reset() {
	*x = LogoutRequest{}
	mi := &file_rpc_service_auth_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogoutRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogoutRequest) ProtoMessage() {}

func (x *LogoutRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_service_auth_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogoutRequest.ProtoReflect.Descriptor instead.
func (*LogoutRequest) Descriptor() ([]byte, []int) {
	return file_rpc_service_auth_proto_rawDescGZIP(), []int{9}
}

// UserInfo 用户信息
type UserInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`          // 用户ID
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`                     // 用户名
	Email         string                 `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`                           // 邮箱
	CreatedAt     int64                  `protobuf:"varint,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"` // 创建时间（Unix时间戳）
	UpdatedAt     int64                  `protobuf:"varint,5,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"` // 更新时间（Unix时间戳）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserInfo) Reset() {
	*x = UserInfo{}
	mi := &file_rpc_service_auth_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserInfo) ProtoMessage() {}

func (x *UserInfo) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_service_auth_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserInfo.ProtoReflect.Descriptor instead.
func (*UserInfo) Descriptor() ([]byte, []int) {
	return file_rpc_service_auth_proto_rawDescGZIP(), []int{10}
}

func (x *UserInfo) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *UserInfo) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *UserInfo) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *UserInfo) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *UserInfo) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

var File_rpc_service_auth_proto protoreflect.FileDescriptor

const file_rpc_service_auth_proto_rawDesc = "" +
	"\n" +
	"\x16rpc/service/auth.proto\x12\x10lemon_tea.server\x1a\x1cgoogle/api/annotations.proto\x1a\x18rpc/common/options.proto\x1a\x17rpc/common/common.proto\"\x99\x01\n" +
	" SendEmailVerificationCodeRequest\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12C\n" +
	"\tcode_type\x18\x03 \x01(\x0e2&.lemon_tea.common.VerificationCodeTypeR\bcodeType\"W\n" +
	"!SendEmailVerificationCodeResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"q\n" +
	"\x1dCheckFieldAvailabilityRequest\x12:\n" +
	"\n" +
	"field_type\x18\x01 \x01(\x0e2\x1b.lemon_tea.server.FieldTypeR\tfieldType\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\">\n" +
	"\x1eCheckFieldAvailabilityResponse\x12\x1c\n" +
	"\tavailable\x18\x01 \x01(\bR\tavailable\"\x9e\x01\n" +
	"\x0fRegisterRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12!\n" +
	"\fpassword_md5\x18\x02 \x01(\tR\vpasswordMd5\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email\x126\n" +
	"\x17email_verification_code\x18\x04 \x01(\x03R\x15emailVerificationCode\"p\n" +
	"\x10RegisterResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x1c\n" +
	"\auser_id\x18\x03 \x01(\tH\x00R\x06userId\x88\x01\x01B\n" +
	"\n" +
	"\b_user_id\"R\n" +
	"\fLoginRequest\x12\x1f\n" +
	"\vlogin_field\x18\x01 \x01(\tR\n" +
	"loginField\x12!\n" +
	"\fpassword_md5\x18\x02 \x01(\tR\vpasswordMd5\"\xc7\x01\n" +
	"\rLoginResponse\x12&\n" +
	"\faccess_token\x18\x01 \x01(\tH\x00R\vaccessToken\x88\x01\x01\x12\"\n" +
	"\n" +
	"expires_in\x18\x02 \x01(\x03H\x01R\texpiresIn\x88\x01\x01\x12<\n" +
	"\tuser_info\x18\x03 \x01(\v2\x1a.lemon_tea.server.UserInfoH\x02R\buserInfo\x88\x01\x01B\x0f\n" +
	"\r_access_tokenB\r\n" +
	"\v_expires_inB\f\n" +
	"\n" +
	"_user_info\"\x99\x01\n" +
	"\x14ResetPasswordRequest\x12\x1f\n" +
	"\vlogin_field\x18\x01 \x01(\tR\n" +
	"loginField\x126\n" +
	"\x17email_verification_code\x18\x02 \x01(\tR\x15emailVerificationCode\x12(\n" +
	"\x10new_password_md5\x18\x03 \x01(\tR\x0enewPasswordMd5\"\x0f\n" +
	"\rLogoutRequest\"\x93\x01\n" +
	"\bUserInfo\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email\x12\x1d\n" +
	"\n" +
	"created_at\x18\x04 \x01(\x03R\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x05 \x01(\x03R\tupdatedAt*V\n" +
	"\tFieldType\x12\x1a\n" +
	"\x16FIELD_TYPE_UNSPECIFIED\x10\x00\x12\x17\n" +
	"\x13FIELD_TYPE_USERNAME\x10\x01\x12\x14\n" +
	"\x10FIELD_TYPE_EMAIL\x10\x022\xe1\x05\n" +
	"\x04Auth\x12\x8d\x01\n" +
	"\x19SendEmailVerificationCode\x122.lemon_tea.server.SendEmailVerificationCodeRequest\x1a\x17.lemon_tea.common.Empty\"#\x82\xd3\xe4\x93\x02\x1d:\x01*\"\x18/v1/auth/send-email-code\x12\xa3\x01\n" +
	"\x16CheckFieldAvailability\x12/.lemon_tea.server.CheckFieldAvailabilityRequest\x1a0.lemon_tea.server.CheckFieldAvailabilityResponse\"&\x82\xd3\xe4\x93\x02 :\x01*\"\x1b/v1/auth/check-availability\x12d\n" +
	"\bRegister\x12!.lemon_tea.server.RegisterRequest\x1a\x17.lemon_tea.common.Empty\"\x1c\x82\xd3\xe4\x93\x02\x16:\x01*\"\x11/v1/auth/register\x12c\n" +
	"\x05Login\x12\x1e.lemon_tea.server.LoginRequest\x1a\x1f.lemon_tea.server.LoginResponse\"\x19\x82\xd3\xe4\x93\x02\x13:\x01*\"\x0e/v1/auth/login\x12t\n" +
	"\rResetPassword\x12&.lemon_tea.server.ResetPasswordRequest\x1a\x17.lemon_tea.common.Empty\"\"\x82\xd3\xe4\x93\x02\x1c:\x01*\"\x17/v1/auth/reset-password\x12b\n" +
	"\x06Logout\x12\x1f.lemon_tea.server.LogoutRequest\x1a\x17.lemon_tea.common.Empty\"\x1e\x88\xb5\x18\x01\x82\xd3\xe4\x93\x02\x14:\x01*\"\x0f/v1/auth/logoutB@Z>gitlab.linhf.cn/project/lemontea/lemon_tea_desktop/rpc/serviceb\x06proto3"

var (
	file_rpc_service_auth_proto_rawDescOnce sync.Once
	file_rpc_service_auth_proto_rawDescData []byte
)

func file_rpc_service_auth_proto_rawDescGZIP() []byte {
	file_rpc_service_auth_proto_rawDescOnce.Do(func() {
		file_rpc_service_auth_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_rpc_service_auth_proto_rawDesc), len(file_rpc_service_auth_proto_rawDesc)))
	})
	return file_rpc_service_auth_proto_rawDescData
}

var file_rpc_service_auth_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_rpc_service_auth_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_rpc_service_auth_proto_goTypes = []any{
	(FieldType)(0),                            // 0: lemon_tea.server.FieldType
	(*SendEmailVerificationCodeRequest)(nil),  // 1: lemon_tea.server.SendEmailVerificationCodeRequest
	(*SendEmailVerificationCodeResponse)(nil), // 2: lemon_tea.server.SendEmailVerificationCodeResponse
	(*CheckFieldAvailabilityRequest)(nil),     // 3: lemon_tea.server.CheckFieldAvailabilityRequest
	(*CheckFieldAvailabilityResponse)(nil),    // 4: lemon_tea.server.CheckFieldAvailabilityResponse
	(*RegisterRequest)(nil),                   // 5: lemon_tea.server.RegisterRequest
	(*RegisterResponse)(nil),                  // 6: lemon_tea.server.RegisterResponse
	(*LoginRequest)(nil),                      // 7: lemon_tea.server.LoginRequest
	(*LoginResponse)(nil),                     // 8: lemon_tea.server.LoginResponse
	(*ResetPasswordRequest)(nil),              // 9: lemon_tea.server.ResetPasswordRequest
	(*LogoutRequest)(nil),                     // 10: lemon_tea.server.LogoutRequest
	(*UserInfo)(nil),                          // 11: lemon_tea.server.UserInfo
	(common.VerificationCodeType)(0),          // 12: lemon_tea.common.VerificationCodeType
	(*common.Empty)(nil),                      // 13: lemon_tea.common.Empty
}
var file_rpc_service_auth_proto_depIdxs = []int32{
	12, // 0: lemon_tea.server.SendEmailVerificationCodeRequest.code_type:type_name -> lemon_tea.common.VerificationCodeType
	0,  // 1: lemon_tea.server.CheckFieldAvailabilityRequest.field_type:type_name -> lemon_tea.server.FieldType
	11, // 2: lemon_tea.server.LoginResponse.user_info:type_name -> lemon_tea.server.UserInfo
	1,  // 3: lemon_tea.server.Auth.SendEmailVerificationCode:input_type -> lemon_tea.server.SendEmailVerificationCodeRequest
	3,  // 4: lemon_tea.server.Auth.CheckFieldAvailability:input_type -> lemon_tea.server.CheckFieldAvailabilityRequest
	5,  // 5: lemon_tea.server.Auth.Register:input_type -> lemon_tea.server.RegisterRequest
	7,  // 6: lemon_tea.server.Auth.Login:input_type -> lemon_tea.server.LoginRequest
	9,  // 7: lemon_tea.server.Auth.ResetPassword:input_type -> lemon_tea.server.ResetPasswordRequest
	10, // 8: lemon_tea.server.Auth.Logout:input_type -> lemon_tea.server.LogoutRequest
	13, // 9: lemon_tea.server.Auth.SendEmailVerificationCode:output_type -> lemon_tea.common.Empty
	4,  // 10: lemon_tea.server.Auth.CheckFieldAvailability:output_type -> lemon_tea.server.CheckFieldAvailabilityResponse
	13, // 11: lemon_tea.server.Auth.Register:output_type -> lemon_tea.common.Empty
	8,  // 12: lemon_tea.server.Auth.Login:output_type -> lemon_tea.server.LoginResponse
	13, // 13: lemon_tea.server.Auth.ResetPassword:output_type -> lemon_tea.common.Empty
	13, // 14: lemon_tea.server.Auth.Logout:output_type -> lemon_tea.common.Empty
	9,  // [9:15] is the sub-list for method output_type
	3,  // [3:9] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_rpc_service_auth_proto_init() }
func file_rpc_service_auth_proto_init() {
	if File_rpc_service_auth_proto != nil {
		return
	}
	file_rpc_service_auth_proto_msgTypes[5].OneofWrappers = []any{}
	file_rpc_service_auth_proto_msgTypes[7].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_rpc_service_auth_proto_rawDesc), len(file_rpc_service_auth_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_rpc_service_auth_proto_goTypes,
		DependencyIndexes: file_rpc_service_auth_proto_depIdxs,
		EnumInfos:         file_rpc_service_auth_proto_enumTypes,
		MessageInfos:      file_rpc_service_auth_proto_msgTypes,
	}.Build()
	File_rpc_service_auth_proto = out.File
	file_rpc_service_auth_proto_goTypes = nil
	file_rpc_service_auth_proto_depIdxs = nil
}
