// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        v5.29.3
// source: rpc/service/chat.proto

package service

import (
	common "gitlab.linhf.cn/project/lemontea/lemon_tea_desktop/rpc/common"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// CreateChatCompletionRequest 与 OpenAI Chat Completions 请求体对齐
type CompletionsRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Model             string                 `protobuf:"bytes,1,opt,name=model,proto3" json:"model,omitempty"`                                                                                  // 模型名称（必需）
	Messages          []*common.Message      `protobuf:"bytes,2,rep,name=messages,proto3" json:"messages,omitempty"`                                                                            // 对话消息列表（必需）
	Temperature       *float64               `protobuf:"fixed64,3,opt,name=temperature,proto3,oneof" json:"temperature,omitempty"`                                                              // 随机性控制，0-2，默认1
	MaxTokens         *int32                 `protobuf:"varint,4,opt,name=max_tokens,json=maxTokens,proto3,oneof" json:"max_tokens,omitempty"`                                                  // 最大生成token数
	TopP              *float64               `protobuf:"fixed64,5,opt,name=top_p,json=topP,proto3,oneof" json:"top_p,omitempty"`                                                                // 核采样，0-1，默认1
	N                 *int32                 `protobuf:"varint,6,opt,name=n,proto3,oneof" json:"n,omitempty"`                                                                                   // 生成多少个选择，默认1
	Stream            *bool                  `protobuf:"varint,7,opt,name=stream,proto3,oneof" json:"stream,omitempty"`                                                                         // 是否流式返回，默认false
	Stop              *string                `protobuf:"bytes,8,opt,name=stop,proto3,oneof" json:"stop,omitempty"`                                                                              // 停止序列
	StopSequence      []string               `protobuf:"bytes,9,rep,name=stop_sequence,json=stopSequence,proto3" json:"stop_sequence,omitempty"`                                                // 停止序列列表
	PresencePenalty   *float64               `protobuf:"fixed64,10,opt,name=presence_penalty,json=presencePenalty,proto3,oneof" json:"presence_penalty,omitempty"`                              // 存在惩罚，-2.0到2.0，默认0
	FrequencyPenalty  *float64               `protobuf:"fixed64,11,opt,name=frequency_penalty,json=frequencyPenalty,proto3,oneof" json:"frequency_penalty,omitempty"`                           // 频率惩罚，-2.0到2.0，默认0
	RepetitionPenalty *float64               `protobuf:"fixed64,12,opt,name=repetition_penalty,json=repetitionPenalty,proto3,oneof" json:"repetition_penalty,omitempty"`                        // 重复惩罚
	User              *string                `protobuf:"bytes,13,opt,name=user,proto3,oneof" json:"user,omitempty"`                                                                             // 用户标识符
	Tools             []*ChatCompletionTool  `protobuf:"bytes,14,rep,name=tools,proto3" json:"tools,omitempty"`                                                                                 // 可用工具列表
	ToolChoice        *ToolChoice            `protobuf:"bytes,15,opt,name=tool_choice,json=toolChoice,proto3,oneof" json:"tool_choice,omitempty"`                                               // 工具选择策略
	ResponseFormat    *ResponseFormat        `protobuf:"bytes,16,opt,name=response_format,json=responseFormat,proto3,oneof" json:"response_format,omitempty"`                                   // 响应格式
	Seed              *int32                 `protobuf:"varint,17,opt,name=seed,proto3,oneof" json:"seed,omitempty"`                                                                            // 随机种子
	Metadata          map[string]string      `protobuf:"bytes,18,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // 额外元数据
	// 以下为业务字段
	NonStandard       bool               `protobuf:"varint,19,opt,name=non_standard,json=nonStandard,proto3" json:"non_standard,omitempty"` // 是否为非标准对话
	ChatUuid          string             `protobuf:"bytes,20,opt,name=chat_uuid,json=chatUuid,proto3" json:"chat_uuid,omitempty"`           // 对话id
	CompletionsCustom *CompletionsCustom `protobuf:"bytes,21,opt,name=completions_custom,json=completionsCustom,proto3" json:"completions_custom,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *CompletionsRequest) Reset() {
	*x = CompletionsRequest{}
	mi := &file_rpc_service_chat_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompletionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompletionsRequest) ProtoMessage() {}

func (x *CompletionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_service_chat_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompletionsRequest.ProtoReflect.Descriptor instead.
func (*CompletionsRequest) Descriptor() ([]byte, []int) {
	return file_rpc_service_chat_proto_rawDescGZIP(), []int{0}
}

func (x *CompletionsRequest) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *CompletionsRequest) GetMessages() []*common.Message {
	if x != nil {
		return x.Messages
	}
	return nil
}

func (x *CompletionsRequest) GetTemperature() float64 {
	if x != nil && x.Temperature != nil {
		return *x.Temperature
	}
	return 0
}

func (x *CompletionsRequest) GetMaxTokens() int32 {
	if x != nil && x.MaxTokens != nil {
		return *x.MaxTokens
	}
	return 0
}

func (x *CompletionsRequest) GetTopP() float64 {
	if x != nil && x.TopP != nil {
		return *x.TopP
	}
	return 0
}

func (x *CompletionsRequest) GetN() int32 {
	if x != nil && x.N != nil {
		return *x.N
	}
	return 0
}

func (x *CompletionsRequest) GetStream() bool {
	if x != nil && x.Stream != nil {
		return *x.Stream
	}
	return false
}

func (x *CompletionsRequest) GetStop() string {
	if x != nil && x.Stop != nil {
		return *x.Stop
	}
	return ""
}

func (x *CompletionsRequest) GetStopSequence() []string {
	if x != nil {
		return x.StopSequence
	}
	return nil
}

func (x *CompletionsRequest) GetPresencePenalty() float64 {
	if x != nil && x.PresencePenalty != nil {
		return *x.PresencePenalty
	}
	return 0
}

func (x *CompletionsRequest) GetFrequencyPenalty() float64 {
	if x != nil && x.FrequencyPenalty != nil {
		return *x.FrequencyPenalty
	}
	return 0
}

func (x *CompletionsRequest) GetRepetitionPenalty() float64 {
	if x != nil && x.RepetitionPenalty != nil {
		return *x.RepetitionPenalty
	}
	return 0
}

func (x *CompletionsRequest) GetUser() string {
	if x != nil && x.User != nil {
		return *x.User
	}
	return ""
}

func (x *CompletionsRequest) GetTools() []*ChatCompletionTool {
	if x != nil {
		return x.Tools
	}
	return nil
}

func (x *CompletionsRequest) GetToolChoice() *ToolChoice {
	if x != nil {
		return x.ToolChoice
	}
	return nil
}

func (x *CompletionsRequest) GetResponseFormat() *ResponseFormat {
	if x != nil {
		return x.ResponseFormat
	}
	return nil
}

func (x *CompletionsRequest) GetSeed() int32 {
	if x != nil && x.Seed != nil {
		return *x.Seed
	}
	return 0
}

func (x *CompletionsRequest) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *CompletionsRequest) GetNonStandard() bool {
	if x != nil {
		return x.NonStandard
	}
	return false
}

func (x *CompletionsRequest) GetChatUuid() string {
	if x != nil {
		return x.ChatUuid
	}
	return ""
}

func (x *CompletionsRequest) GetCompletionsCustom() *CompletionsCustom {
	if x != nil {
		return x.CompletionsCustom
	}
	return nil
}

// CompletionsCustom 业务自定义
type CompletionsCustom struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	UseMemory        bool                   `protobuf:"varint,1,opt,name=use_memory,json=useMemory,proto3" json:"use_memory,omitempty"`                        // 是否启用记忆
	UseMultipleAgent bool                   `protobuf:"varint,2,opt,name=use_multiple_agent,json=useMultipleAgent,proto3" json:"use_multiple_agent,omitempty"` // 是否启用多思维体
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *CompletionsCustom) Reset() {
	*x = CompletionsCustom{}
	mi := &file_rpc_service_chat_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompletionsCustom) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompletionsCustom) ProtoMessage() {}

func (x *CompletionsCustom) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_service_chat_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompletionsCustom.ProtoReflect.Descriptor instead.
func (*CompletionsCustom) Descriptor() ([]byte, []int) {
	return file_rpc_service_chat_proto_rawDescGZIP(), []int{1}
}

func (x *CompletionsCustom) GetUseMemory() bool {
	if x != nil {
		return x.UseMemory
	}
	return false
}

func (x *CompletionsCustom) GetUseMultipleAgent() bool {
	if x != nil {
		return x.UseMultipleAgent
	}
	return false
}

// ChatCompletionChunk 与 OpenAI Chat Completions 流式 chunk 对齐
type CompletionsResponse struct {
	state             protoimpl.MessageState  `protogen:"open.v1"`
	Id                string                  `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`                                                                                       // 响应唯一标识符
	Object            string                  `protobuf:"bytes,2,opt,name=object,proto3" json:"object,omitempty"`                                                                               // 对象类型，通常为"chat.completion"
	Created           int64                   `protobuf:"varint,3,opt,name=created,proto3" json:"created,omitempty"`                                                                            // 创建时间戳
	Model             string                  `protobuf:"bytes,4,opt,name=model,proto3" json:"model,omitempty"`                                                                                 // 使用的模型名称
	Choices           []*ChatCompletionChoice `protobuf:"bytes,5,rep,name=choices,proto3" json:"choices,omitempty"`                                                                             // 生成的选择列表
	Usage             *common.TokenUsage      `protobuf:"bytes,6,opt,name=usage,proto3,oneof" json:"usage,omitempty"`                                                                           // token使用情况
	SystemFingerprint *string                 `protobuf:"bytes,7,opt,name=system_fingerprint,json=systemFingerprint,proto3,oneof" json:"system_fingerprint,omitempty"`                          // 系统指纹
	Metadata          map[string]string       `protobuf:"bytes,8,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // 额外元数据
	// 以下为业务字段
	NonStandard   bool   `protobuf:"varint,9,opt,name=non_standard,json=nonStandard,proto3" json:"non_standard,omitempty"` // 是否为非标准对话
	ChatUuid      string `protobuf:"bytes,10,opt,name=chat_uuid,json=chatUuid,proto3" json:"chat_uuid,omitempty"`          // 对话id
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompletionsResponse) Reset() {
	*x = CompletionsResponse{}
	mi := &file_rpc_service_chat_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompletionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompletionsResponse) ProtoMessage() {}

func (x *CompletionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_service_chat_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompletionsResponse.ProtoReflect.Descriptor instead.
func (*CompletionsResponse) Descriptor() ([]byte, []int) {
	return file_rpc_service_chat_proto_rawDescGZIP(), []int{2}
}

func (x *CompletionsResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CompletionsResponse) GetObject() string {
	if x != nil {
		return x.Object
	}
	return ""
}

func (x *CompletionsResponse) GetCreated() int64 {
	if x != nil {
		return x.Created
	}
	return 0
}

func (x *CompletionsResponse) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *CompletionsResponse) GetChoices() []*ChatCompletionChoice {
	if x != nil {
		return x.Choices
	}
	return nil
}

func (x *CompletionsResponse) GetUsage() *common.TokenUsage {
	if x != nil {
		return x.Usage
	}
	return nil
}

func (x *CompletionsResponse) GetSystemFingerprint() string {
	if x != nil && x.SystemFingerprint != nil {
		return *x.SystemFingerprint
	}
	return ""
}

func (x *CompletionsResponse) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *CompletionsResponse) GetNonStandard() bool {
	if x != nil {
		return x.NonStandard
	}
	return false
}

func (x *CompletionsResponse) GetChatUuid() string {
	if x != nil {
		return x.ChatUuid
	}
	return ""
}

// ChatTitleRequest 获取对话标题请求
type ChatTitleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChatUuid      string                 `protobuf:"bytes,1,opt,name=chat_uuid,json=chatUuid,proto3" json:"chat_uuid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatTitleRequest) Reset() {
	*x = ChatTitleRequest{}
	mi := &file_rpc_service_chat_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatTitleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatTitleRequest) ProtoMessage() {}

func (x *ChatTitleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_service_chat_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatTitleRequest.ProtoReflect.Descriptor instead.
func (*ChatTitleRequest) Descriptor() ([]byte, []int) {
	return file_rpc_service_chat_proto_rawDescGZIP(), []int{3}
}

func (x *ChatTitleRequest) GetChatUuid() string {
	if x != nil {
		return x.ChatUuid
	}
	return ""
}

// ChatTitleResponse 获取对话标题响应
type ChatTitleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatTitleResponse) Reset() {
	*x = ChatTitleResponse{}
	mi := &file_rpc_service_chat_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatTitleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatTitleResponse) ProtoMessage() {}

func (x *ChatTitleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_service_chat_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatTitleResponse.ProtoReflect.Descriptor instead.
func (*ChatTitleResponse) Descriptor() ([]byte, []int) {
	return file_rpc_service_chat_proto_rawDescGZIP(), []int{4}
}

func (x *ChatTitleResponse) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

// ChatTitleSaveRequest 保存对话标题请求
type ChatTitleSaveRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChatUuid      string                 `protobuf:"bytes,1,opt,name=chat_uuid,json=chatUuid,proto3" json:"chat_uuid,omitempty"`
	ChatTitle     string                 `protobuf:"bytes,2,opt,name=chat_title,json=chatTitle,proto3" json:"chat_title,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatTitleSaveRequest) Reset() {
	*x = ChatTitleSaveRequest{}
	mi := &file_rpc_service_chat_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatTitleSaveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatTitleSaveRequest) ProtoMessage() {}

func (x *ChatTitleSaveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_service_chat_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatTitleSaveRequest.ProtoReflect.Descriptor instead.
func (*ChatTitleSaveRequest) Descriptor() ([]byte, []int) {
	return file_rpc_service_chat_proto_rawDescGZIP(), []int{5}
}

func (x *ChatTitleSaveRequest) GetChatUuid() string {
	if x != nil {
		return x.ChatUuid
	}
	return ""
}

func (x *ChatTitleSaveRequest) GetChatTitle() string {
	if x != nil {
		return x.ChatTitle
	}
	return ""
}

// ListChatsRequest 获取对话列表请求
type ListChatsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Offset        int64                  `protobuf:"varint,1,opt,name=offset,proto3" json:"offset,omitempty"`
	Limit         int64                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Filter        *ListChatsFilter       `protobuf:"bytes,3,opt,name=filter,proto3,oneof" json:"filter,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListChatsRequest) Reset() {
	*x = ListChatsRequest{}
	mi := &file_rpc_service_chat_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListChatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListChatsRequest) ProtoMessage() {}

func (x *ListChatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_service_chat_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListChatsRequest.ProtoReflect.Descriptor instead.
func (*ListChatsRequest) Descriptor() ([]byte, []int) {
	return file_rpc_service_chat_proto_rawDescGZIP(), []int{6}
}

func (x *ListChatsRequest) GetOffset() int64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *ListChatsRequest) GetLimit() int64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListChatsRequest) GetFilter() *ListChatsFilter {
	if x != nil {
		return x.Filter
	}
	return nil
}

type ListChatsFilter struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tag           *string                `protobuf:"bytes,1,opt,name=tag,proto3,oneof" json:"tag,omitempty"`
	Keyword       *string                `protobuf:"bytes,2,opt,name=keyword,proto3,oneof" json:"keyword,omitempty"` // 搜索关键字，为空则不搜索
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListChatsFilter) Reset() {
	*x = ListChatsFilter{}
	mi := &file_rpc_service_chat_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListChatsFilter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListChatsFilter) ProtoMessage() {}

func (x *ListChatsFilter) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_service_chat_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListChatsFilter.ProtoReflect.Descriptor instead.
func (*ListChatsFilter) Descriptor() ([]byte, []int) {
	return file_rpc_service_chat_proto_rawDescGZIP(), []int{7}
}

func (x *ListChatsFilter) GetTag() string {
	if x != nil && x.Tag != nil {
		return *x.Tag
	}
	return ""
}

func (x *ListChatsFilter) GetKeyword() string {
	if x != nil && x.Keyword != nil {
		return *x.Keyword
	}
	return ""
}

// ListChatsResponse 获取对话列表响应
type ListChatsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Chats         []*common.ChatInfo     `protobuf:"bytes,1,rep,name=chats,proto3" json:"chats,omitempty"`                              // 对话列表
	TotalCount    int64                  `protobuf:"varint,2,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"` // 总数量
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListChatsResponse) Reset() {
	*x = ListChatsResponse{}
	mi := &file_rpc_service_chat_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListChatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListChatsResponse) ProtoMessage() {}

func (x *ListChatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_service_chat_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListChatsResponse.ProtoReflect.Descriptor instead.
func (*ListChatsResponse) Descriptor() ([]byte, []int) {
	return file_rpc_service_chat_proto_rawDescGZIP(), []int{8}
}

func (x *ListChatsResponse) GetChats() []*common.ChatInfo {
	if x != nil {
		return x.Chats
	}
	return nil
}

func (x *ListChatsResponse) GetTotalCount() int64 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

// DeleteChatRequest 删除对话请求
type DeleteChatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChatUuid      string                 `protobuf:"bytes,1,opt,name=chat_uuid,json=chatUuid,proto3" json:"chat_uuid,omitempty"` // 要删除的对话 ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteChatRequest) Reset() {
	*x = DeleteChatRequest{}
	mi := &file_rpc_service_chat_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteChatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteChatRequest) ProtoMessage() {}

func (x *DeleteChatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_service_chat_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteChatRequest.ProtoReflect.Descriptor instead.
func (*DeleteChatRequest) Descriptor() ([]byte, []int) {
	return file_rpc_service_chat_proto_rawDescGZIP(), []int{9}
}

func (x *DeleteChatRequest) GetChatUuid() string {
	if x != nil {
		return x.ChatUuid
	}
	return ""
}

// GetChatMessagesRequest 获取对话消息请求
type GetChatMessagesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChatUuid      string                 `protobuf:"bytes,1,opt,name=chat_uuid,json=chatUuid,proto3" json:"chat_uuid,omitempty"` // 对话 ID
	Offset        int64                  `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	Limit         int64                  `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetChatMessagesRequest) Reset() {
	*x = GetChatMessagesRequest{}
	mi := &file_rpc_service_chat_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetChatMessagesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetChatMessagesRequest) ProtoMessage() {}

func (x *GetChatMessagesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_service_chat_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetChatMessagesRequest.ProtoReflect.Descriptor instead.
func (*GetChatMessagesRequest) Descriptor() ([]byte, []int) {
	return file_rpc_service_chat_proto_rawDescGZIP(), []int{10}
}

func (x *GetChatMessagesRequest) GetChatUuid() string {
	if x != nil {
		return x.ChatUuid
	}
	return ""
}

func (x *GetChatMessagesRequest) GetOffset() int64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *GetChatMessagesRequest) GetLimit() int64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

// GetChatMessagesResponse 获取对话消息响应
type GetChatMessagesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Messages      []*common.Message      `protobuf:"bytes,1,rep,name=messages,proto3" json:"messages,omitempty"`                        // 消息列表
	TotalCount    int32                  `protobuf:"varint,2,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"` // 总消息数量
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetChatMessagesResponse) Reset() {
	*x = GetChatMessagesResponse{}
	mi := &file_rpc_service_chat_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetChatMessagesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetChatMessagesResponse) ProtoMessage() {}

func (x *GetChatMessagesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_service_chat_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetChatMessagesResponse.ProtoReflect.Descriptor instead.
func (*GetChatMessagesResponse) Descriptor() ([]byte, []int) {
	return file_rpc_service_chat_proto_rawDescGZIP(), []int{11}
}

func (x *GetChatMessagesResponse) GetMessages() []*common.Message {
	if x != nil {
		return x.Messages
	}
	return nil
}

func (x *GetChatMessagesResponse) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

// DeleteChatMessageRequest 删除对话消息请求
type DeleteChatMessageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChatUuid      string                 `protobuf:"bytes,1,opt,name=chat_uuid,json=chatUuid,proto3" json:"chat_uuid,omitempty"`    // 对话 ID
	MessageId     string                 `protobuf:"bytes,2,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"` // 要删除的消息 ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteChatMessageRequest) Reset() {
	*x = DeleteChatMessageRequest{}
	mi := &file_rpc_service_chat_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteChatMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteChatMessageRequest) ProtoMessage() {}

func (x *DeleteChatMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_service_chat_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteChatMessageRequest.ProtoReflect.Descriptor instead.
func (*DeleteChatMessageRequest) Descriptor() ([]byte, []int) {
	return file_rpc_service_chat_proto_rawDescGZIP(), []int{12}
}

func (x *DeleteChatMessageRequest) GetChatUuid() string {
	if x != nil {
		return x.ChatUuid
	}
	return ""
}

func (x *DeleteChatMessageRequest) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

// DeleteChatMessageResponse 删除对话消息响应
type DeleteChatMessageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"` // 删除是否成功
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`  // 响应消息
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteChatMessageResponse) Reset() {
	*x = DeleteChatMessageResponse{}
	mi := &file_rpc_service_chat_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteChatMessageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteChatMessageResponse) ProtoMessage() {}

func (x *DeleteChatMessageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_service_chat_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteChatMessageResponse.ProtoReflect.Descriptor instead.
func (*DeleteChatMessageResponse) Descriptor() ([]byte, []int) {
	return file_rpc_service_chat_proto_rawDescGZIP(), []int{13}
}

func (x *DeleteChatMessageResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *DeleteChatMessageResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// ChatCompletionTool 工具定义
type ChatCompletionTool struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Type          string                  `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`         // 工具类型，通常为"function"
	Function      *ChatCompletionFunction `protobuf:"bytes,2,opt,name=function,proto3" json:"function,omitempty"` // 函数定义
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatCompletionTool) Reset() {
	*x = ChatCompletionTool{}
	mi := &file_rpc_service_chat_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatCompletionTool) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatCompletionTool) ProtoMessage() {}

func (x *ChatCompletionTool) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_service_chat_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatCompletionTool.ProtoReflect.Descriptor instead.
func (*ChatCompletionTool) Descriptor() ([]byte, []int) {
	return file_rpc_service_chat_proto_rawDescGZIP(), []int{14}
}

func (x *ChatCompletionTool) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *ChatCompletionTool) GetFunction() *ChatCompletionFunction {
	if x != nil {
		return x.Function
	}
	return nil
}

// ChatCompletionFunction 函数定义
type ChatCompletionFunction struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`                     // 函数名称
	Description   *string                `protobuf:"bytes,2,opt,name=description,proto3,oneof" json:"description,omitempty"` // 函数描述
	Parameters    *string                `protobuf:"bytes,3,opt,name=parameters,proto3,oneof" json:"parameters,omitempty"`   // JSON Schema格式的参数定义
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatCompletionFunction) Reset() {
	*x = ChatCompletionFunction{}
	mi := &file_rpc_service_chat_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatCompletionFunction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatCompletionFunction) ProtoMessage() {}

func (x *ChatCompletionFunction) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_service_chat_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatCompletionFunction.ProtoReflect.Descriptor instead.
func (*ChatCompletionFunction) Descriptor() ([]byte, []int) {
	return file_rpc_service_chat_proto_rawDescGZIP(), []int{15}
}

func (x *ChatCompletionFunction) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ChatCompletionFunction) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

func (x *ChatCompletionFunction) GetParameters() string {
	if x != nil && x.Parameters != nil {
		return *x.Parameters
	}
	return ""
}

// ToolChoice 工具选择策略
type ToolChoice struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Choice:
	//
	//	*ToolChoice_Mode
	//	*ToolChoice_Named
	Choice        isToolChoice_Choice `protobuf_oneof:"choice"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ToolChoice) Reset() {
	*x = ToolChoice{}
	mi := &file_rpc_service_chat_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToolChoice) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToolChoice) ProtoMessage() {}

func (x *ToolChoice) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_service_chat_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToolChoice.ProtoReflect.Descriptor instead.
func (*ToolChoice) Descriptor() ([]byte, []int) {
	return file_rpc_service_chat_proto_rawDescGZIP(), []int{16}
}

func (x *ToolChoice) GetChoice() isToolChoice_Choice {
	if x != nil {
		return x.Choice
	}
	return nil
}

func (x *ToolChoice) GetMode() string {
	if x != nil {
		if x, ok := x.Choice.(*ToolChoice_Mode); ok {
			return x.Mode
		}
	}
	return ""
}

func (x *ToolChoice) GetNamed() *ChatCompletionNamedToolChoice {
	if x != nil {
		if x, ok := x.Choice.(*ToolChoice_Named); ok {
			return x.Named
		}
	}
	return nil
}

type isToolChoice_Choice interface {
	isToolChoice_Choice()
}

type ToolChoice_Mode struct {
	Mode string `protobuf:"bytes,1,opt,name=mode,proto3,oneof"` // "none", "auto", "required"
}

type ToolChoice_Named struct {
	Named *ChatCompletionNamedToolChoice `protobuf:"bytes,2,opt,name=named,proto3,oneof"` // 指定特定工具
}

func (*ToolChoice_Mode) isToolChoice_Choice() {}

func (*ToolChoice_Named) isToolChoice_Choice() {}

// ChatCompletionNamedToolChoice 指定特定工具
type ChatCompletionNamedToolChoice struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Type          string                  `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`         // 工具类型
	Function      *ChatCompletionFunction `protobuf:"bytes,2,opt,name=function,proto3" json:"function,omitempty"` // 指定的函数
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatCompletionNamedToolChoice) Reset() {
	*x = ChatCompletionNamedToolChoice{}
	mi := &file_rpc_service_chat_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatCompletionNamedToolChoice) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatCompletionNamedToolChoice) ProtoMessage() {}

func (x *ChatCompletionNamedToolChoice) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_service_chat_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatCompletionNamedToolChoice.ProtoReflect.Descriptor instead.
func (*ChatCompletionNamedToolChoice) Descriptor() ([]byte, []int) {
	return file_rpc_service_chat_proto_rawDescGZIP(), []int{17}
}

func (x *ChatCompletionNamedToolChoice) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *ChatCompletionNamedToolChoice) GetFunction() *ChatCompletionFunction {
	if x != nil {
		return x.Function
	}
	return nil
}

// ResponseFormat 响应格式
type ResponseFormat struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`                                     // "text" 或 "json_object"
	JsonSchema    *string                `protobuf:"bytes,2,opt,name=json_schema,json=jsonSchema,proto3,oneof" json:"json_schema,omitempty"` // JSON Schema定义（当type为json_object时）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResponseFormat) Reset() {
	*x = ResponseFormat{}
	mi := &file_rpc_service_chat_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResponseFormat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseFormat) ProtoMessage() {}

func (x *ResponseFormat) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_service_chat_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponseFormat.ProtoReflect.Descriptor instead.
func (*ResponseFormat) Descriptor() ([]byte, []int) {
	return file_rpc_service_chat_proto_rawDescGZIP(), []int{18}
}

func (x *ResponseFormat) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *ResponseFormat) GetJsonSchema() string {
	if x != nil && x.JsonSchema != nil {
		return *x.JsonSchema
	}
	return ""
}

// ChatCompletionChoice 聊天完成选择
type ChatCompletionChoice struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Index         int32                  `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"`                                        // 选择索引
	Delta         *common.Message        `protobuf:"bytes,2,opt,name=delta,proto3" json:"delta,omitempty"`                                         // 生成的消息
	Logprobs      *common.LogProbs       `protobuf:"bytes,3,opt,name=logprobs,proto3,oneof" json:"logprobs,omitempty"`                             // 对数概率信息
	FinishReason  *string                `protobuf:"bytes,4,opt,name=finish_reason,json=finishReason,proto3,oneof" json:"finish_reason,omitempty"` // 结束原因："stop", "length", "tool_calls", "content_filter", "function_call"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatCompletionChoice) Reset() {
	*x = ChatCompletionChoice{}
	mi := &file_rpc_service_chat_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatCompletionChoice) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatCompletionChoice) ProtoMessage() {}

func (x *ChatCompletionChoice) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_service_chat_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatCompletionChoice.ProtoReflect.Descriptor instead.
func (*ChatCompletionChoice) Descriptor() ([]byte, []int) {
	return file_rpc_service_chat_proto_rawDescGZIP(), []int{19}
}

func (x *ChatCompletionChoice) GetIndex() int32 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *ChatCompletionChoice) GetDelta() *common.Message {
	if x != nil {
		return x.Delta
	}
	return nil
}

func (x *ChatCompletionChoice) GetLogprobs() *common.LogProbs {
	if x != nil {
		return x.Logprobs
	}
	return nil
}

func (x *ChatCompletionChoice) GetFinishReason() string {
	if x != nil && x.FinishReason != nil {
		return *x.FinishReason
	}
	return ""
}

// ChatCompletionChunk 流式响应块（用于流式传输）
type ChatCompletionChunk struct {
	state             protoimpl.MessageState       `protogen:"open.v1"`
	Id                string                       `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`                                                              // 响应唯一标识符
	Object            string                       `protobuf:"bytes,2,opt,name=object,proto3" json:"object,omitempty"`                                                      // 对象类型，通常为"chat.completion.chunk"
	Created           int64                        `protobuf:"varint,3,opt,name=created,proto3" json:"created,omitempty"`                                                   // 创建时间戳
	Model             string                       `protobuf:"bytes,4,opt,name=model,proto3" json:"model,omitempty"`                                                        // 使用的模型名称
	Choices           []*ChatCompletionChunkChoice `protobuf:"bytes,5,rep,name=choices,proto3" json:"choices,omitempty"`                                                    // 增量选择列表
	Usage             *common.TokenUsage           `protobuf:"bytes,6,opt,name=usage,proto3,oneof" json:"usage,omitempty"`                                                  // token使用情况（通常只在最后一个chunk中出现）
	SystemFingerprint *string                      `protobuf:"bytes,7,opt,name=system_fingerprint,json=systemFingerprint,proto3,oneof" json:"system_fingerprint,omitempty"` // 系统指纹
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ChatCompletionChunk) Reset() {
	*x = ChatCompletionChunk{}
	mi := &file_rpc_service_chat_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatCompletionChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatCompletionChunk) ProtoMessage() {}

func (x *ChatCompletionChunk) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_service_chat_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatCompletionChunk.ProtoReflect.Descriptor instead.
func (*ChatCompletionChunk) Descriptor() ([]byte, []int) {
	return file_rpc_service_chat_proto_rawDescGZIP(), []int{20}
}

func (x *ChatCompletionChunk) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ChatCompletionChunk) GetObject() string {
	if x != nil {
		return x.Object
	}
	return ""
}

func (x *ChatCompletionChunk) GetCreated() int64 {
	if x != nil {
		return x.Created
	}
	return 0
}

func (x *ChatCompletionChunk) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *ChatCompletionChunk) GetChoices() []*ChatCompletionChunkChoice {
	if x != nil {
		return x.Choices
	}
	return nil
}

func (x *ChatCompletionChunk) GetUsage() *common.TokenUsage {
	if x != nil {
		return x.Usage
	}
	return nil
}

func (x *ChatCompletionChunk) GetSystemFingerprint() string {
	if x != nil && x.SystemFingerprint != nil {
		return *x.SystemFingerprint
	}
	return ""
}

// ChatCompletionChunkChoice 流式响应选择
type ChatCompletionChunkChoice struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	Index         int32                     `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"`                                        // 选择索引
	Delta         *ChatCompletionChunkDelta `protobuf:"bytes,2,opt,name=delta,proto3,oneof" json:"delta,omitempty"`                                   // 增量内容
	Logprobs      *common.LogProbs          `protobuf:"bytes,3,opt,name=logprobs,proto3,oneof" json:"logprobs,omitempty"`                             // 对数概率信息
	FinishReason  *string                   `protobuf:"bytes,4,opt,name=finish_reason,json=finishReason,proto3,oneof" json:"finish_reason,omitempty"` // 结束原因（只在最后一个chunk中出现）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatCompletionChunkChoice) Reset() {
	*x = ChatCompletionChunkChoice{}
	mi := &file_rpc_service_chat_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatCompletionChunkChoice) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatCompletionChunkChoice) ProtoMessage() {}

func (x *ChatCompletionChunkChoice) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_service_chat_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatCompletionChunkChoice.ProtoReflect.Descriptor instead.
func (*ChatCompletionChunkChoice) Descriptor() ([]byte, []int) {
	return file_rpc_service_chat_proto_rawDescGZIP(), []int{21}
}

func (x *ChatCompletionChunkChoice) GetIndex() int32 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *ChatCompletionChunkChoice) GetDelta() *ChatCompletionChunkDelta {
	if x != nil {
		return x.Delta
	}
	return nil
}

func (x *ChatCompletionChunkChoice) GetLogprobs() *common.LogProbs {
	if x != nil {
		return x.Logprobs
	}
	return nil
}

func (x *ChatCompletionChunkChoice) GetFinishReason() string {
	if x != nil && x.FinishReason != nil {
		return *x.FinishReason
	}
	return ""
}

// ChatCompletionChunkDelta 流式响应增量内容
type ChatCompletionChunkDelta struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Role          *string                `protobuf:"bytes,1,opt,name=role,proto3,oneof" json:"role,omitempty"`                      // 角色（只在第一个chunk中出现）
	Content       *string                `protobuf:"bytes,2,opt,name=content,proto3,oneof" json:"content,omitempty"`                // 增量内容
	ToolCalls     []*common.ToolCall     `protobuf:"bytes,3,rep,name=tool_calls,json=toolCalls,proto3" json:"tool_calls,omitempty"` // 增量工具调用
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatCompletionChunkDelta) Reset() {
	*x = ChatCompletionChunkDelta{}
	mi := &file_rpc_service_chat_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatCompletionChunkDelta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatCompletionChunkDelta) ProtoMessage() {}

func (x *ChatCompletionChunkDelta) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_service_chat_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatCompletionChunkDelta.ProtoReflect.Descriptor instead.
func (*ChatCompletionChunkDelta) Descriptor() ([]byte, []int) {
	return file_rpc_service_chat_proto_rawDescGZIP(), []int{22}
}

func (x *ChatCompletionChunkDelta) GetRole() string {
	if x != nil && x.Role != nil {
		return *x.Role
	}
	return ""
}

func (x *ChatCompletionChunkDelta) GetContent() string {
	if x != nil && x.Content != nil {
		return *x.Content
	}
	return ""
}

func (x *ChatCompletionChunkDelta) GetToolCalls() []*common.ToolCall {
	if x != nil {
		return x.ToolCalls
	}
	return nil
}

var File_rpc_service_chat_proto protoreflect.FileDescriptor

const file_rpc_service_chat_proto_rawDesc = "" +
	"\n" +
	"\x16rpc/service/chat.proto\x12\x10lemon_tea.server\x1a\x1cgoogle/api/annotations.proto\x1a\x17rpc/common/common.proto\x1a\x18rpc/common/options.proto\"\xa8\t\n" +
	"\x12CompletionsRequest\x12\x14\n" +
	"\x05model\x18\x01 \x01(\tR\x05model\x125\n" +
	"\bmessages\x18\x02 \x03(\v2\x19.lemon_tea.common.MessageR\bmessages\x12%\n" +
	"\vtemperature\x18\x03 \x01(\x01H\x00R\vtemperature\x88\x01\x01\x12\"\n" +
	"\n" +
	"max_tokens\x18\x04 \x01(\x05H\x01R\tmaxTokens\x88\x01\x01\x12\x18\n" +
	"\x05top_p\x18\x05 \x01(\x01H\x02R\x04topP\x88\x01\x01\x12\x11\n" +
	"\x01n\x18\x06 \x01(\x05H\x03R\x01n\x88\x01\x01\x12\x1b\n" +
	"\x06stream\x18\a \x01(\bH\x04R\x06stream\x88\x01\x01\x12\x17\n" +
	"\x04stop\x18\b \x01(\tH\x05R\x04stop\x88\x01\x01\x12#\n" +
	"\rstop_sequence\x18\t \x03(\tR\fstopSequence\x12.\n" +
	"\x10presence_penalty\x18\n" +
	" \x01(\x01H\x06R\x0fpresencePenalty\x88\x01\x01\x120\n" +
	"\x11frequency_penalty\x18\v \x01(\x01H\aR\x10frequencyPenalty\x88\x01\x01\x122\n" +
	"\x12repetition_penalty\x18\f \x01(\x01H\bR\x11repetitionPenalty\x88\x01\x01\x12\x17\n" +
	"\x04user\x18\r \x01(\tH\tR\x04user\x88\x01\x01\x12:\n" +
	"\x05tools\x18\x0e \x03(\v2$.lemon_tea.server.ChatCompletionToolR\x05tools\x12B\n" +
	"\vtool_choice\x18\x0f \x01(\v2\x1c.lemon_tea.server.ToolChoiceH\n" +
	"R\n" +
	"toolChoice\x88\x01\x01\x12N\n" +
	"\x0fresponse_format\x18\x10 \x01(\v2 .lemon_tea.server.ResponseFormatH\vR\x0eresponseFormat\x88\x01\x01\x12\x17\n" +
	"\x04seed\x18\x11 \x01(\x05H\fR\x04seed\x88\x01\x01\x12N\n" +
	"\bmetadata\x18\x12 \x03(\v22.lemon_tea.server.CompletionsRequest.MetadataEntryR\bmetadata\x12!\n" +
	"\fnon_standard\x18\x13 \x01(\bR\vnonStandard\x12\x1b\n" +
	"\tchat_uuid\x18\x14 \x01(\tR\bchatUuid\x12R\n" +
	"\x12completions_custom\x18\x15 \x01(\v2#.lemon_tea.server.CompletionsCustomR\x11completionsCustom\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01B\x0e\n" +
	"\f_temperatureB\r\n" +
	"\v_max_tokensB\b\n" +
	"\x06_top_pB\x04\n" +
	"\x02_nB\t\n" +
	"\a_streamB\a\n" +
	"\x05_stopB\x13\n" +
	"\x11_presence_penaltyB\x14\n" +
	"\x12_frequency_penaltyB\x15\n" +
	"\x13_repetition_penaltyB\a\n" +
	"\x05_userB\x0e\n" +
	"\f_tool_choiceB\x12\n" +
	"\x10_response_formatB\a\n" +
	"\x05_seed\"`\n" +
	"\x11CompletionsCustom\x12\x1d\n" +
	"\n" +
	"use_memory\x18\x01 \x01(\bR\tuseMemory\x12,\n" +
	"\x12use_multiple_agent\x18\x02 \x01(\bR\x10useMultipleAgent\"\x8b\x04\n" +
	"\x13CompletionsResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06object\x18\x02 \x01(\tR\x06object\x12\x18\n" +
	"\acreated\x18\x03 \x01(\x03R\acreated\x12\x14\n" +
	"\x05model\x18\x04 \x01(\tR\x05model\x12@\n" +
	"\achoices\x18\x05 \x03(\v2&.lemon_tea.server.ChatCompletionChoiceR\achoices\x127\n" +
	"\x05usage\x18\x06 \x01(\v2\x1c.lemon_tea.common.TokenUsageH\x00R\x05usage\x88\x01\x01\x122\n" +
	"\x12system_fingerprint\x18\a \x01(\tH\x01R\x11systemFingerprint\x88\x01\x01\x12O\n" +
	"\bmetadata\x18\b \x03(\v23.lemon_tea.server.CompletionsResponse.MetadataEntryR\bmetadata\x12!\n" +
	"\fnon_standard\x18\t \x01(\bR\vnonStandard\x12\x1b\n" +
	"\tchat_uuid\x18\n" +
	" \x01(\tR\bchatUuid\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01B\b\n" +
	"\x06_usageB\x15\n" +
	"\x13_system_fingerprint\"/\n" +
	"\x10ChatTitleRequest\x12\x1b\n" +
	"\tchat_uuid\x18\x01 \x01(\tR\bchatUuid\")\n" +
	"\x11ChatTitleResponse\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\"R\n" +
	"\x14ChatTitleSaveRequest\x12\x1b\n" +
	"\tchat_uuid\x18\x01 \x01(\tR\bchatUuid\x12\x1d\n" +
	"\n" +
	"chat_title\x18\x02 \x01(\tR\tchatTitle\"\x8b\x01\n" +
	"\x10ListChatsRequest\x12\x16\n" +
	"\x06offset\x18\x01 \x01(\x03R\x06offset\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x03R\x05limit\x12>\n" +
	"\x06filter\x18\x03 \x01(\v2!.lemon_tea.server.ListChatsFilterH\x00R\x06filter\x88\x01\x01B\t\n" +
	"\a_filter\"[\n" +
	"\x0fListChatsFilter\x12\x15\n" +
	"\x03tag\x18\x01 \x01(\tH\x00R\x03tag\x88\x01\x01\x12\x1d\n" +
	"\akeyword\x18\x02 \x01(\tH\x01R\akeyword\x88\x01\x01B\x06\n" +
	"\x04_tagB\n" +
	"\n" +
	"\b_keyword\"f\n" +
	"\x11ListChatsResponse\x120\n" +
	"\x05chats\x18\x01 \x03(\v2\x1a.lemon_tea.common.ChatInfoR\x05chats\x12\x1f\n" +
	"\vtotal_count\x18\x02 \x01(\x03R\n" +
	"totalCount\"0\n" +
	"\x11DeleteChatRequest\x12\x1b\n" +
	"\tchat_uuid\x18\x01 \x01(\tR\bchatUuid\"c\n" +
	"\x16GetChatMessagesRequest\x12\x1b\n" +
	"\tchat_uuid\x18\x01 \x01(\tR\bchatUuid\x12\x16\n" +
	"\x06offset\x18\x02 \x01(\x03R\x06offset\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x03R\x05limit\"q\n" +
	"\x17GetChatMessagesResponse\x125\n" +
	"\bmessages\x18\x01 \x03(\v2\x19.lemon_tea.common.MessageR\bmessages\x12\x1f\n" +
	"\vtotal_count\x18\x02 \x01(\x05R\n" +
	"totalCount\"V\n" +
	"\x18DeleteChatMessageRequest\x12\x1b\n" +
	"\tchat_uuid\x18\x01 \x01(\tR\bchatUuid\x12\x1d\n" +
	"\n" +
	"message_id\x18\x02 \x01(\tR\tmessageId\"O\n" +
	"\x19DeleteChatMessageResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"n\n" +
	"\x12ChatCompletionTool\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12D\n" +
	"\bfunction\x18\x02 \x01(\v2(.lemon_tea.server.ChatCompletionFunctionR\bfunction\"\x97\x01\n" +
	"\x16ChatCompletionFunction\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12%\n" +
	"\vdescription\x18\x02 \x01(\tH\x00R\vdescription\x88\x01\x01\x12#\n" +
	"\n" +
	"parameters\x18\x03 \x01(\tH\x01R\n" +
	"parameters\x88\x01\x01B\x0e\n" +
	"\f_descriptionB\r\n" +
	"\v_parameters\"u\n" +
	"\n" +
	"ToolChoice\x12\x14\n" +
	"\x04mode\x18\x01 \x01(\tH\x00R\x04mode\x12G\n" +
	"\x05named\x18\x02 \x01(\v2/.lemon_tea.server.ChatCompletionNamedToolChoiceH\x00R\x05namedB\b\n" +
	"\x06choice\"y\n" +
	"\x1dChatCompletionNamedToolChoice\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12D\n" +
	"\bfunction\x18\x02 \x01(\v2(.lemon_tea.server.ChatCompletionFunctionR\bfunction\"Z\n" +
	"\x0eResponseFormat\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12$\n" +
	"\vjson_schema\x18\x02 \x01(\tH\x00R\n" +
	"jsonSchema\x88\x01\x01B\x0e\n" +
	"\f_json_schema\"\xe3\x01\n" +
	"\x14ChatCompletionChoice\x12\x14\n" +
	"\x05index\x18\x01 \x01(\x05R\x05index\x12/\n" +
	"\x05delta\x18\x02 \x01(\v2\x19.lemon_tea.common.MessageR\x05delta\x12;\n" +
	"\blogprobs\x18\x03 \x01(\v2\x1a.lemon_tea.common.LogProbsH\x00R\blogprobs\x88\x01\x01\x12(\n" +
	"\rfinish_reason\x18\x04 \x01(\tH\x01R\ffinishReason\x88\x01\x01B\v\n" +
	"\t_logprobsB\x10\n" +
	"\x0e_finish_reason\"\xc2\x02\n" +
	"\x13ChatCompletionChunk\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06object\x18\x02 \x01(\tR\x06object\x12\x18\n" +
	"\acreated\x18\x03 \x01(\x03R\acreated\x12\x14\n" +
	"\x05model\x18\x04 \x01(\tR\x05model\x12E\n" +
	"\achoices\x18\x05 \x03(\v2+.lemon_tea.server.ChatCompletionChunkChoiceR\achoices\x127\n" +
	"\x05usage\x18\x06 \x01(\v2\x1c.lemon_tea.common.TokenUsageH\x00R\x05usage\x88\x01\x01\x122\n" +
	"\x12system_fingerprint\x18\a \x01(\tH\x01R\x11systemFingerprint\x88\x01\x01B\b\n" +
	"\x06_usageB\x15\n" +
	"\x13_system_fingerprint\"\x88\x02\n" +
	"\x19ChatCompletionChunkChoice\x12\x14\n" +
	"\x05index\x18\x01 \x01(\x05R\x05index\x12E\n" +
	"\x05delta\x18\x02 \x01(\v2*.lemon_tea.server.ChatCompletionChunkDeltaH\x00R\x05delta\x88\x01\x01\x12;\n" +
	"\blogprobs\x18\x03 \x01(\v2\x1a.lemon_tea.common.LogProbsH\x01R\blogprobs\x88\x01\x01\x12(\n" +
	"\rfinish_reason\x18\x04 \x01(\tH\x02R\ffinishReason\x88\x01\x01B\b\n" +
	"\x06_deltaB\v\n" +
	"\t_logprobsB\x10\n" +
	"\x0e_finish_reason\"\xa2\x01\n" +
	"\x18ChatCompletionChunkDelta\x12\x17\n" +
	"\x04role\x18\x01 \x01(\tH\x00R\x04role\x88\x01\x01\x12\x1d\n" +
	"\acontent\x18\x02 \x01(\tH\x01R\acontent\x88\x01\x01\x129\n" +
	"\n" +
	"tool_calls\x18\x03 \x03(\v2\x1a.lemon_tea.common.ToolCallR\ttoolCallsB\a\n" +
	"\x05_roleB\n" +
	"\n" +
	"\b_content2\xd9\a\n" +
	"\x04Chat\x12\x81\x01\n" +
	"\vCompletions\x12$.lemon_tea.server.CompletionsRequest\x1a%.lemon_tea.server.CompletionsResponse\"#\x88\xb5\x18\x01\x82\xd3\xe4\x93\x02\x19:\x01*\"\x14/v1/chat/completions0\x01\x12\x80\x01\n" +
	"\tChatTitle\x12\".lemon_tea.server.ChatTitleRequest\x1a#.lemon_tea.server.ChatTitleResponse\"*\x88\xb5\x18\x01\x82\xd3\xe4\x93\x02 :\x01*\"\x1b/v1/chats/title/{chat_uuid}\x12\x8e\x01\n" +
	"\rChatTitleSave\x12&.lemon_tea.server.ChatTitleSaveRequest\x1a\x17.lemon_tea.common.Empty\"<\x88\xb5\x18\x01\x82\xd3\xe4\x93\x022:\x01*\"-/v1/chats/title/save/{chat_uuid}/{chat_title}\x12r\n" +
	"\tListChats\x12\".lemon_tea.server.ListChatsRequest\x1a#.lemon_tea.server.ListChatsResponse\"\x1c\x88\xb5\x18\x01\x82\xd3\xe4\x93\x02\x12:\x01*\"\r/v1/chats/get\x12w\n" +
	"\n" +
	"DeleteChat\x12#.lemon_tea.server.DeleteChatRequest\x1a\x17.lemon_tea.common.Empty\"+\x88\xb5\x18\x01\x82\xd3\xe4\x93\x02!:\x01*\"\x1c/v1/chats/delete/{chat_uuid}\x12\x99\x01\n" +
	"\x0fGetChatMessages\x12(.lemon_tea.server.GetChatMessagesRequest\x1a).lemon_tea.server.GetChatMessagesResponse\"1\x88\xb5\x18\x01\x82\xd3\xe4\x93\x02':\x01*\"\"/v1/chats/messages/get/{chat_uuid}\x12\xaf\x01\n" +
	"\x11DeleteChatMessage\x12*.lemon_tea.server.DeleteChatMessageRequest\x1a+.lemon_tea.server.DeleteChatMessageResponse\"A\x88\xb5\x18\x01\x82\xd3\xe4\x93\x027:\x01*\"2/v1/chats/messages/delete/{chat_uuid}/{message_id}B@Z>gitlab.linhf.cn/project/lemontea/lemon_tea_desktop/rpc/serviceb\x06proto3"

var (
	file_rpc_service_chat_proto_rawDescOnce sync.Once
	file_rpc_service_chat_proto_rawDescData []byte
)

func file_rpc_service_chat_proto_rawDescGZIP() []byte {
	file_rpc_service_chat_proto_rawDescOnce.Do(func() {
		file_rpc_service_chat_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_rpc_service_chat_proto_rawDesc), len(file_rpc_service_chat_proto_rawDesc)))
	})
	return file_rpc_service_chat_proto_rawDescData
}

var file_rpc_service_chat_proto_msgTypes = make([]protoimpl.MessageInfo, 25)
var file_rpc_service_chat_proto_goTypes = []any{
	(*CompletionsRequest)(nil),            // 0: lemon_tea.server.CompletionsRequest
	(*CompletionsCustom)(nil),             // 1: lemon_tea.server.CompletionsCustom
	(*CompletionsResponse)(nil),           // 2: lemon_tea.server.CompletionsResponse
	(*ChatTitleRequest)(nil),              // 3: lemon_tea.server.ChatTitleRequest
	(*ChatTitleResponse)(nil),             // 4: lemon_tea.server.ChatTitleResponse
	(*ChatTitleSaveRequest)(nil),          // 5: lemon_tea.server.ChatTitleSaveRequest
	(*ListChatsRequest)(nil),              // 6: lemon_tea.server.ListChatsRequest
	(*ListChatsFilter)(nil),               // 7: lemon_tea.server.ListChatsFilter
	(*ListChatsResponse)(nil),             // 8: lemon_tea.server.ListChatsResponse
	(*DeleteChatRequest)(nil),             // 9: lemon_tea.server.DeleteChatRequest
	(*GetChatMessagesRequest)(nil),        // 10: lemon_tea.server.GetChatMessagesRequest
	(*GetChatMessagesResponse)(nil),       // 11: lemon_tea.server.GetChatMessagesResponse
	(*DeleteChatMessageRequest)(nil),      // 12: lemon_tea.server.DeleteChatMessageRequest
	(*DeleteChatMessageResponse)(nil),     // 13: lemon_tea.server.DeleteChatMessageResponse
	(*ChatCompletionTool)(nil),            // 14: lemon_tea.server.ChatCompletionTool
	(*ChatCompletionFunction)(nil),        // 15: lemon_tea.server.ChatCompletionFunction
	(*ToolChoice)(nil),                    // 16: lemon_tea.server.ToolChoice
	(*ChatCompletionNamedToolChoice)(nil), // 17: lemon_tea.server.ChatCompletionNamedToolChoice
	(*ResponseFormat)(nil),                // 18: lemon_tea.server.ResponseFormat
	(*ChatCompletionChoice)(nil),          // 19: lemon_tea.server.ChatCompletionChoice
	(*ChatCompletionChunk)(nil),           // 20: lemon_tea.server.ChatCompletionChunk
	(*ChatCompletionChunkChoice)(nil),     // 21: lemon_tea.server.ChatCompletionChunkChoice
	(*ChatCompletionChunkDelta)(nil),      // 22: lemon_tea.server.ChatCompletionChunkDelta
	nil,                                   // 23: lemon_tea.server.CompletionsRequest.MetadataEntry
	nil,                                   // 24: lemon_tea.server.CompletionsResponse.MetadataEntry
	(*common.Message)(nil),                // 25: lemon_tea.common.Message
	(*common.TokenUsage)(nil),             // 26: lemon_tea.common.TokenUsage
	(*common.ChatInfo)(nil),               // 27: lemon_tea.common.ChatInfo
	(*common.LogProbs)(nil),               // 28: lemon_tea.common.LogProbs
	(*common.ToolCall)(nil),               // 29: lemon_tea.common.ToolCall
	(*common.Empty)(nil),                  // 30: lemon_tea.common.Empty
}
var file_rpc_service_chat_proto_depIdxs = []int32{
	25, // 0: lemon_tea.server.CompletionsRequest.messages:type_name -> lemon_tea.common.Message
	14, // 1: lemon_tea.server.CompletionsRequest.tools:type_name -> lemon_tea.server.ChatCompletionTool
	16, // 2: lemon_tea.server.CompletionsRequest.tool_choice:type_name -> lemon_tea.server.ToolChoice
	18, // 3: lemon_tea.server.CompletionsRequest.response_format:type_name -> lemon_tea.server.ResponseFormat
	23, // 4: lemon_tea.server.CompletionsRequest.metadata:type_name -> lemon_tea.server.CompletionsRequest.MetadataEntry
	1,  // 5: lemon_tea.server.CompletionsRequest.completions_custom:type_name -> lemon_tea.server.CompletionsCustom
	19, // 6: lemon_tea.server.CompletionsResponse.choices:type_name -> lemon_tea.server.ChatCompletionChoice
	26, // 7: lemon_tea.server.CompletionsResponse.usage:type_name -> lemon_tea.common.TokenUsage
	24, // 8: lemon_tea.server.CompletionsResponse.metadata:type_name -> lemon_tea.server.CompletionsResponse.MetadataEntry
	7,  // 9: lemon_tea.server.ListChatsRequest.filter:type_name -> lemon_tea.server.ListChatsFilter
	27, // 10: lemon_tea.server.ListChatsResponse.chats:type_name -> lemon_tea.common.ChatInfo
	25, // 11: lemon_tea.server.GetChatMessagesResponse.messages:type_name -> lemon_tea.common.Message
	15, // 12: lemon_tea.server.ChatCompletionTool.function:type_name -> lemon_tea.server.ChatCompletionFunction
	17, // 13: lemon_tea.server.ToolChoice.named:type_name -> lemon_tea.server.ChatCompletionNamedToolChoice
	15, // 14: lemon_tea.server.ChatCompletionNamedToolChoice.function:type_name -> lemon_tea.server.ChatCompletionFunction
	25, // 15: lemon_tea.server.ChatCompletionChoice.delta:type_name -> lemon_tea.common.Message
	28, // 16: lemon_tea.server.ChatCompletionChoice.logprobs:type_name -> lemon_tea.common.LogProbs
	21, // 17: lemon_tea.server.ChatCompletionChunk.choices:type_name -> lemon_tea.server.ChatCompletionChunkChoice
	26, // 18: lemon_tea.server.ChatCompletionChunk.usage:type_name -> lemon_tea.common.TokenUsage
	22, // 19: lemon_tea.server.ChatCompletionChunkChoice.delta:type_name -> lemon_tea.server.ChatCompletionChunkDelta
	28, // 20: lemon_tea.server.ChatCompletionChunkChoice.logprobs:type_name -> lemon_tea.common.LogProbs
	29, // 21: lemon_tea.server.ChatCompletionChunkDelta.tool_calls:type_name -> lemon_tea.common.ToolCall
	0,  // 22: lemon_tea.server.Chat.Completions:input_type -> lemon_tea.server.CompletionsRequest
	3,  // 23: lemon_tea.server.Chat.ChatTitle:input_type -> lemon_tea.server.ChatTitleRequest
	5,  // 24: lemon_tea.server.Chat.ChatTitleSave:input_type -> lemon_tea.server.ChatTitleSaveRequest
	6,  // 25: lemon_tea.server.Chat.ListChats:input_type -> lemon_tea.server.ListChatsRequest
	9,  // 26: lemon_tea.server.Chat.DeleteChat:input_type -> lemon_tea.server.DeleteChatRequest
	10, // 27: lemon_tea.server.Chat.GetChatMessages:input_type -> lemon_tea.server.GetChatMessagesRequest
	12, // 28: lemon_tea.server.Chat.DeleteChatMessage:input_type -> lemon_tea.server.DeleteChatMessageRequest
	2,  // 29: lemon_tea.server.Chat.Completions:output_type -> lemon_tea.server.CompletionsResponse
	4,  // 30: lemon_tea.server.Chat.ChatTitle:output_type -> lemon_tea.server.ChatTitleResponse
	30, // 31: lemon_tea.server.Chat.ChatTitleSave:output_type -> lemon_tea.common.Empty
	8,  // 32: lemon_tea.server.Chat.ListChats:output_type -> lemon_tea.server.ListChatsResponse
	30, // 33: lemon_tea.server.Chat.DeleteChat:output_type -> lemon_tea.common.Empty
	11, // 34: lemon_tea.server.Chat.GetChatMessages:output_type -> lemon_tea.server.GetChatMessagesResponse
	13, // 35: lemon_tea.server.Chat.DeleteChatMessage:output_type -> lemon_tea.server.DeleteChatMessageResponse
	29, // [29:36] is the sub-list for method output_type
	22, // [22:29] is the sub-list for method input_type
	22, // [22:22] is the sub-list for extension type_name
	22, // [22:22] is the sub-list for extension extendee
	0,  // [0:22] is the sub-list for field type_name
}

func init() { file_rpc_service_chat_proto_init() }
func file_rpc_service_chat_proto_init() {
	if File_rpc_service_chat_proto != nil {
		return
	}
	file_rpc_service_chat_proto_msgTypes[0].OneofWrappers = []any{}
	file_rpc_service_chat_proto_msgTypes[2].OneofWrappers = []any{}
	file_rpc_service_chat_proto_msgTypes[6].OneofWrappers = []any{}
	file_rpc_service_chat_proto_msgTypes[7].OneofWrappers = []any{}
	file_rpc_service_chat_proto_msgTypes[15].OneofWrappers = []any{}
	file_rpc_service_chat_proto_msgTypes[16].OneofWrappers = []any{
		(*ToolChoice_Mode)(nil),
		(*ToolChoice_Named)(nil),
	}
	file_rpc_service_chat_proto_msgTypes[18].OneofWrappers = []any{}
	file_rpc_service_chat_proto_msgTypes[19].OneofWrappers = []any{}
	file_rpc_service_chat_proto_msgTypes[20].OneofWrappers = []any{}
	file_rpc_service_chat_proto_msgTypes[21].OneofWrappers = []any{}
	file_rpc_service_chat_proto_msgTypes[22].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_rpc_service_chat_proto_rawDesc), len(file_rpc_service_chat_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   25,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_rpc_service_chat_proto_goTypes,
		DependencyIndexes: file_rpc_service_chat_proto_depIdxs,
		MessageInfos:      file_rpc_service_chat_proto_msgTypes,
	}.Build()
	File_rpc_service_chat_proto = out.File
	file_rpc_service_chat_proto_goTypes = nil
	file_rpc_service_chat_proto_depIdxs = nil
}
