// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        v5.29.3
// source: rpc/service/models.proto

package service

import (
	common "gitlab.linhf.cn/project/lemontea/lemon_tea_desktop/rpc/common"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ListModelsRequest 允许通过 providerId 或直接 base_url/api_key 指定目标提供方
type ModelsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LlmProviderId string                 `protobuf:"bytes,1,opt,name=llm_provider_id,json=llmProviderId,proto3" json:"llm_provider_id,omitempty"` // 优先使用 providerId
	BaseUrl       string                 `protobuf:"bytes,2,opt,name=base_url,json=baseUrl,proto3" json:"base_url,omitempty"`                     // 当未提供 providerId 时使用
	ApiKey        string                 `protobuf:"bytes,3,opt,name=api_key,json=apiKey,proto3" json:"api_key,omitempty"`                        // 当未提供 providerId 时使用
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ModelsRequest) Reset() {
	*x = ModelsRequest{}
	mi := &file_rpc_service_models_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ModelsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModelsRequest) ProtoMessage() {}

func (x *ModelsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_service_models_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModelsRequest.ProtoReflect.Descriptor instead.
func (*ModelsRequest) Descriptor() ([]byte, []int) {
	return file_rpc_service_models_proto_rawDescGZIP(), []int{0}
}

func (x *ModelsRequest) GetLlmProviderId() string {
	if x != nil {
		return x.LlmProviderId
	}
	return ""
}

func (x *ModelsRequest) GetBaseUrl() string {
	if x != nil {
		return x.BaseUrl
	}
	return ""
}

func (x *ModelsRequest) GetApiKey() string {
	if x != nil {
		return x.ApiKey
	}
	return ""
}

type ModelsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Object        string                 `protobuf:"bytes,1,opt,name=object,proto3" json:"object,omitempty"`
	Data          []*common.Model        `protobuf:"bytes,2,rep,name=data,proto3" json:"data,omitempty"` // 模型列表
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ModelsResponse) Reset() {
	*x = ModelsResponse{}
	mi := &file_rpc_service_models_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ModelsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModelsResponse) ProtoMessage() {}

func (x *ModelsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_service_models_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModelsResponse.ProtoReflect.Descriptor instead.
func (*ModelsResponse) Descriptor() ([]byte, []int) {
	return file_rpc_service_models_proto_rawDescGZIP(), []int{1}
}

func (x *ModelsResponse) GetObject() string {
	if x != nil {
		return x.Object
	}
	return ""
}

func (x *ModelsResponse) GetData() []*common.Model {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_rpc_service_models_proto protoreflect.FileDescriptor

const file_rpc_service_models_proto_rawDesc = "" +
	"\n" +
	"\x18rpc/service/models.proto\x12\x10lemon_tea.server\x1a\x1cgoogle/api/annotations.proto\x1a\x17rpc/common/common.proto\x1a\x18rpc/common/options.proto\"k\n" +
	"\rModelsRequest\x12&\n" +
	"\x0fllm_provider_id\x18\x01 \x01(\tR\rllmProviderId\x12\x19\n" +
	"\bbase_url\x18\x02 \x01(\tR\abaseUrl\x12\x17\n" +
	"\aapi_key\x18\x03 \x01(\tR\x06apiKey\"U\n" +
	"\x0eModelsResponse\x12\x16\n" +
	"\x06object\x18\x01 \x01(\tR\x06object\x12+\n" +
	"\x04data\x18\x02 \x03(\v2\x17.lemon_tea.common.ModelR\x04data2m\n" +
	"\x06Models\x12c\n" +
	"\x06models\x12\x1f.lemon_tea.server.ModelsRequest\x1a .lemon_tea.server.ModelsResponse\"\x16\x88\xb5\x18\x01\x82\xd3\xe4\x93\x02\f\"\n" +
	"/v1/modelsB@Z>gitlab.linhf.cn/project/lemontea/lemon_tea_desktop/rpc/serviceb\x06proto3"

var (
	file_rpc_service_models_proto_rawDescOnce sync.Once
	file_rpc_service_models_proto_rawDescData []byte
)

func file_rpc_service_models_proto_rawDescGZIP() []byte {
	file_rpc_service_models_proto_rawDescOnce.Do(func() {
		file_rpc_service_models_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_rpc_service_models_proto_rawDesc), len(file_rpc_service_models_proto_rawDesc)))
	})
	return file_rpc_service_models_proto_rawDescData
}

var file_rpc_service_models_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_rpc_service_models_proto_goTypes = []any{
	(*ModelsRequest)(nil),  // 0: lemon_tea.server.ModelsRequest
	(*ModelsResponse)(nil), // 1: lemon_tea.server.ModelsResponse
	(*common.Model)(nil),   // 2: lemon_tea.common.Model
}
var file_rpc_service_models_proto_depIdxs = []int32{
	2, // 0: lemon_tea.server.ModelsResponse.data:type_name -> lemon_tea.common.Model
	0, // 1: lemon_tea.server.Models.models:input_type -> lemon_tea.server.ModelsRequest
	1, // 2: lemon_tea.server.Models.models:output_type -> lemon_tea.server.ModelsResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_rpc_service_models_proto_init() }
func file_rpc_service_models_proto_init() {
	if File_rpc_service_models_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_rpc_service_models_proto_rawDesc), len(file_rpc_service_models_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_rpc_service_models_proto_goTypes,
		DependencyIndexes: file_rpc_service_models_proto_depIdxs,
		MessageInfos:      file_rpc_service_models_proto_msgTypes,
	}.Build()
	File_rpc_service_models_proto = out.File
	file_rpc_service_models_proto_goTypes = nil
	file_rpc_service_models_proto_depIdxs = nil
}
