// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class OpenFileInput {
    "path": string;

    /** Creates a new OpenFileInput instance. */
    constructor($$source: Partial<OpenFileInput> = {}) {
        if (!("path" in $$source)) {
            this["path"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new OpenFileInput instance from a string or object.
     */
    static createFrom($$source: any = {}): OpenFileInput {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new OpenFileInput($$parsedSource as Partial<OpenFileInput>);
    }
}

export class OpenFileOutput {

    /** Creates a new OpenFileOutput instance. */
    constructor($$source: Partial<OpenFileOutput> = {}) {

        Object.assign(this, $$source);
    }

    /**
     * Creates a new OpenFileOutput instance from a string or object.
     */
    static createFrom($$source: any = {}): OpenFileOutput {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new OpenFileOutput($$parsedSource as Partial<OpenFileOutput>);
    }
}

export class SaveTempFileInput {
    /**
     * original filename, e.g. "screenshot.png"
     */
    "name": string;

    /**
     * base64-encoded file content
     */
    "data": string;

    /**
     * e.g. "image/png"
     */
    "mime": string;

    /** Creates a new SaveTempFileInput instance. */
    constructor($$source: Partial<SaveTempFileInput> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("data" in $$source)) {
            this["data"] = "";
        }
        if (!("mime" in $$source)) {
            this["mime"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SaveTempFileInput instance from a string or object.
     */
    static createFrom($$source: any = {}): SaveTempFileInput {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SaveTempFileInput($$parsedSource as Partial<SaveTempFileInput>);
    }
}

export class SaveTempFileOutput {
    "file_path": string;

    /** Creates a new SaveTempFileOutput instance. */
    constructor($$source: Partial<SaveTempFileOutput> = {}) {
        if (!("file_path" in $$source)) {
            this["file_path"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SaveTempFileOutput instance from a string or object.
     */
    static createFrom($$source: any = {}): SaveTempFileOutput {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SaveTempFileOutput($$parsedSource as Partial<SaveTempFileOutput>);
    }
}

export class SelectFileInput {
    "default_folder_path": string;

    /** Creates a new SelectFileInput instance. */
    constructor($$source: Partial<SelectFileInput> = {}) {
        if (!("default_folder_path" in $$source)) {
            this["default_folder_path"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SelectFileInput instance from a string or object.
     */
    static createFrom($$source: any = {}): SelectFileInput {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SelectFileInput($$parsedSource as Partial<SelectFileInput>);
    }
}

export class SelectFileOutput {
    "file_path": string;

    /** Creates a new SelectFileOutput instance. */
    constructor($$source: Partial<SelectFileOutput> = {}) {
        if (!("file_path" in $$source)) {
            this["file_path"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SelectFileOutput instance from a string or object.
     */
    static createFrom($$source: any = {}): SelectFileOutput {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SelectFileOutput($$parsedSource as Partial<SelectFileOutput>);
    }
}

export class SelectFolderInput {
    "folder_path": string;

    /** Creates a new SelectFolderInput instance. */
    constructor($$source: Partial<SelectFolderInput> = {}) {
        if (!("folder_path" in $$source)) {
            this["folder_path"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SelectFolderInput instance from a string or object.
     */
    static createFrom($$source: any = {}): SelectFolderInput {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SelectFolderInput($$parsedSource as Partial<SelectFolderInput>);
    }
}

export class SelectFolderOutput {
    "folder_path": string;

    /** Creates a new SelectFolderOutput instance. */
    constructor($$source: Partial<SelectFolderOutput> = {}) {
        if (!("folder_path" in $$source)) {
            this["folder_path"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SelectFolderOutput instance from a string or object.
     */
    static createFrom($$source: any = {}): SelectFolderOutput {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SelectFolderOutput($$parsedSource as Partial<SelectFolderOutput>);
    }
}
