// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Onboarding manages the first-launch initialization flow.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as onboarding_dto$0 from "./onboarding_dto/models.js";

/**
 * EnterHome opens the main window and closes the onboarding window.
 */
export function EnterHome(input: onboarding_dto$0.EnterHomeInput): $CancellablePromise<onboarding_dto$0.EnterHomeOutput | null> {
    return $Call.ByID(3770658681, input).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * ExitApp terminates the Wails application; the OS-level process exits.
 */
export function ExitApp(input: onboarding_dto$0.ExitAppInput): $CancellablePromise<onboarding_dto$0.ExitAppOutput | null> {
    return $Call.ByID(2218182635, input).then(($result: any) => {
        return $$createType3($result);
    });
}

/**
 * IsInitialized reports whether the application has completed first-launch onboarding.
 */
export function IsInitialized(input: onboarding_dto$0.IsInitializedInput): $CancellablePromise<onboarding_dto$0.IsInitializedOutput | null> {
    return $Call.ByID(444292286, input).then(($result: any) => {
        return $$createType5($result);
    });
}

/**
 * SaveProviderAndMarkInitialized creates the first provider and writes the init.json marker.
 * Returns an error if the provider creation fails; the init marker is only written on success.
 */
export function SaveProviderAndMarkInitialized(input: onboarding_dto$0.SaveProviderAndMarkInitializedInput): $CancellablePromise<onboarding_dto$0.SaveProviderAndMarkInitializedOutput | null> {
    return $Call.ByID(2739250534, input).then(($result: any) => {
        return $$createType7($result);
    });
}

// Private type creation functions
const $$createType0 = onboarding_dto$0.EnterHomeOutput.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = onboarding_dto$0.ExitAppOutput.createFrom;
const $$createType3 = $Create.Nullable($$createType2);
const $$createType4 = onboarding_dto$0.IsInitializedOutput.createFrom;
const $$createType5 = $Create.Nullable($$createType4);
const $$createType6 = onboarding_dto$0.SaveProviderAndMarkInitializedOutput.createFrom;
const $$createType7 = $Create.Nullable($$createType6);
