// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * CreateSkillInput provides the fields needed to create a new user skill.
 */
export class CreateSkillInput {
    "name": string;
    "description": string;
    "body": string;

    /** Creates a new CreateSkillInput instance. */
    constructor($$source: Partial<CreateSkillInput> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("description" in $$source)) {
            this["description"] = "";
        }
        if (!("body" in $$source)) {
            this["body"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CreateSkillInput instance from a string or object.
     */
    static createFrom($$source: any = {}): CreateSkillInput {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new CreateSkillInput($$parsedSource as Partial<CreateSkillInput>);
    }
}

/**
 * CreateSkillOutput returns the newly created skill.
 */
export class CreateSkillOutput {
    "skill": SkillItem;

    /** Creates a new CreateSkillOutput instance. */
    constructor($$source: Partial<CreateSkillOutput> = {}) {
        if (!("skill" in $$source)) {
            this["skill"] = (new SkillItem());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CreateSkillOutput instance from a string or object.
     */
    static createFrom($$source: any = {}): CreateSkillOutput {
        const $$createField0_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("skill" in $$parsedSource) {
            $$parsedSource["skill"] = $$createField0_0($$parsedSource["skill"]);
        }
        return new CreateSkillOutput($$parsedSource as Partial<CreateSkillOutput>);
    }
}

/**
 * DeleteSkillInput identifies the skill to delete by name.
 */
export class DeleteSkillInput {
    "name": string;

    /** Creates a new DeleteSkillInput instance. */
    constructor($$source: Partial<DeleteSkillInput> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DeleteSkillInput instance from a string or object.
     */
    static createFrom($$source: any = {}): DeleteSkillInput {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new DeleteSkillInput($$parsedSource as Partial<DeleteSkillInput>);
    }
}

/**
 * DeleteSkillOutput is returned on successful deletion.
 */
export class DeleteSkillOutput {

    /** Creates a new DeleteSkillOutput instance. */
    constructor($$source: Partial<DeleteSkillOutput> = {}) {

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DeleteSkillOutput instance from a string or object.
     */
    static createFrom($$source: any = {}): DeleteSkillOutput {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new DeleteSkillOutput($$parsedSource as Partial<DeleteSkillOutput>);
    }
}

/**
 * GetSkillInput requests a single skill by name.
 */
export class GetSkillInput {
    "name": string;

    /** Creates a new GetSkillInput instance. */
    constructor($$source: Partial<GetSkillInput> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new GetSkillInput instance from a string or object.
     */
    static createFrom($$source: any = {}): GetSkillInput {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new GetSkillInput($$parsedSource as Partial<GetSkillInput>);
    }
}

/**
 * GetSkillOutput returns the requested skill.
 */
export class GetSkillOutput {
    "skill": SkillItem;

    /** Creates a new GetSkillOutput instance. */
    constructor($$source: Partial<GetSkillOutput> = {}) {
        if (!("skill" in $$source)) {
            this["skill"] = (new SkillItem());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new GetSkillOutput instance from a string or object.
     */
    static createFrom($$source: any = {}): GetSkillOutput {
        const $$createField0_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("skill" in $$parsedSource) {
            $$parsedSource["skill"] = $$createField0_0($$parsedSource["skill"]);
        }
        return new GetSkillOutput($$parsedSource as Partial<GetSkillOutput>);
    }
}

/**
 * ImportSkillInput provides a local file path to a SKILL.md for importing.
 */
export class ImportSkillInput {
    "path": string;

    /** Creates a new ImportSkillInput instance. */
    constructor($$source: Partial<ImportSkillInput> = {}) {
        if (!("path" in $$source)) {
            this["path"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ImportSkillInput instance from a string or object.
     */
    static createFrom($$source: any = {}): ImportSkillInput {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ImportSkillInput($$parsedSource as Partial<ImportSkillInput>);
    }
}

/**
 * ImportSkillOutput returns the imported skill.
 */
export class ImportSkillOutput {
    "skill": SkillItem;

    /** Creates a new ImportSkillOutput instance. */
    constructor($$source: Partial<ImportSkillOutput> = {}) {
        if (!("skill" in $$source)) {
            this["skill"] = (new SkillItem());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ImportSkillOutput instance from a string or object.
     */
    static createFrom($$source: any = {}): ImportSkillOutput {
        const $$createField0_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("skill" in $$parsedSource) {
            $$parsedSource["skill"] = $$createField0_0($$parsedSource["skill"]);
        }
        return new ImportSkillOutput($$parsedSource as Partial<ImportSkillOutput>);
    }
}

/**
 * ListSkillsInput is the request payload for listing all skills.
 */
export class ListSkillsInput {

    /** Creates a new ListSkillsInput instance. */
    constructor($$source: Partial<ListSkillsInput> = {}) {

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ListSkillsInput instance from a string or object.
     */
    static createFrom($$source: any = {}): ListSkillsInput {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ListSkillsInput($$parsedSource as Partial<ListSkillsInput>);
    }
}

/**
 * ListSkillsOutput returns all known skills.
 */
export class ListSkillsOutput {
    "skills": SkillItem[];

    /** Creates a new ListSkillsOutput instance. */
    constructor($$source: Partial<ListSkillsOutput> = {}) {
        if (!("skills" in $$source)) {
            this["skills"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ListSkillsOutput instance from a string or object.
     */
    static createFrom($$source: any = {}): ListSkillsOutput {
        const $$createField0_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("skills" in $$parsedSource) {
            $$parsedSource["skills"] = $$createField0_0($$parsedSource["skills"]);
        }
        return new ListSkillsOutput($$parsedSource as Partial<ListSkillsOutput>);
    }
}

/**
 * SkillItem is the view-model representation of one skill returned to the frontend.
 */
export class SkillItem {
    "name": string;
    "description": string;
    "body"?: string;
    "source": string;
    "disabled": boolean;

    /** Creates a new SkillItem instance. */
    constructor($$source: Partial<SkillItem> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("description" in $$source)) {
            this["description"] = "";
        }
        if (!("source" in $$source)) {
            this["source"] = "";
        }
        if (!("disabled" in $$source)) {
            this["disabled"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SkillItem instance from a string or object.
     */
    static createFrom($$source: any = {}): SkillItem {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SkillItem($$parsedSource as Partial<SkillItem>);
    }
}

/**
 * ToggleSkillInput identifies the skill and desired disabled state.
 */
export class ToggleSkillInput {
    "name": string;
    "disabled": boolean;

    /** Creates a new ToggleSkillInput instance. */
    constructor($$source: Partial<ToggleSkillInput> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("disabled" in $$source)) {
            this["disabled"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ToggleSkillInput instance from a string or object.
     */
    static createFrom($$source: any = {}): ToggleSkillInput {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ToggleSkillInput($$parsedSource as Partial<ToggleSkillInput>);
    }
}

/**
 * ToggleSkillOutput returns the skill after toggling its disabled state.
 */
export class ToggleSkillOutput {
    "skill": SkillItem;

    /** Creates a new ToggleSkillOutput instance. */
    constructor($$source: Partial<ToggleSkillOutput> = {}) {
        if (!("skill" in $$source)) {
            this["skill"] = (new SkillItem());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ToggleSkillOutput instance from a string or object.
     */
    static createFrom($$source: any = {}): ToggleSkillOutput {
        const $$createField0_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("skill" in $$parsedSource) {
            $$parsedSource["skill"] = $$createField0_0($$parsedSource["skill"]);
        }
        return new ToggleSkillOutput($$parsedSource as Partial<ToggleSkillOutput>);
    }
}

/**
 * UpdateSkillInput provides the fields needed to update an existing user skill.
 */
export class UpdateSkillInput {
    "name": string;
    "new_name"?: string;
    "description": string;
    "body": string;

    /** Creates a new UpdateSkillInput instance. */
    constructor($$source: Partial<UpdateSkillInput> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("description" in $$source)) {
            this["description"] = "";
        }
        if (!("body" in $$source)) {
            this["body"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new UpdateSkillInput instance from a string or object.
     */
    static createFrom($$source: any = {}): UpdateSkillInput {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new UpdateSkillInput($$parsedSource as Partial<UpdateSkillInput>);
    }
}

/**
 * UpdateSkillOutput returns the updated skill.
 */
export class UpdateSkillOutput {
    "skill": SkillItem;

    /** Creates a new UpdateSkillOutput instance. */
    constructor($$source: Partial<UpdateSkillOutput> = {}) {
        if (!("skill" in $$source)) {
            this["skill"] = (new SkillItem());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new UpdateSkillOutput instance from a string or object.
     */
    static createFrom($$source: any = {}): UpdateSkillOutput {
        const $$createField0_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("skill" in $$parsedSource) {
            $$parsedSource["skill"] = $$createField0_0($$parsedSource["skill"]);
        }
        return new UpdateSkillOutput($$parsedSource as Partial<UpdateSkillOutput>);
    }
}

// Private type creation functions
const $$createType0 = SkillItem.createFrom;
const $$createType1 = $Create.Array($$createType0);
