// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Runtime manages local Node.js runtime download and lifecycle.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as runtime_dto$0 from "./runtime_dto/models.js";

/**
 * CancelDownload aborts an in-progress download (if any).
 */
export function CancelDownload(input: runtime_dto$0.CancelDownloadInput): $CancellablePromise<runtime_dto$0.CancelDownloadOutput | null> {
    return $Call.ByID(3895614460, input).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * DownloadNode starts an asynchronous Node.js download, returning immediately.
 */
export function DownloadNode(input: runtime_dto$0.DownloadNodeInput): $CancellablePromise<runtime_dto$0.DownloadNodeOutput | null> {
    return $Call.ByID(3297534578, input).then(($result: any) => {
        return $$createType3($result);
    });
}

/**
 * GetStatus returns the current persisted Node runtime state.
 */
export function GetStatus(input: runtime_dto$0.GetStatusInput): $CancellablePromise<runtime_dto$0.GetStatusOutput | null> {
    return $Call.ByID(3219470164, input).then(($result: any) => {
        return $$createType5($result);
    });
}

/**
 * MarkDownloadLater records a user choice to download the runtime later.
 */
export function MarkDownloadLater(input: runtime_dto$0.MarkDownloadLaterInput): $CancellablePromise<runtime_dto$0.MarkDownloadLaterOutput | null> {
    return $Call.ByID(2282911535, input).then(($result: any) => {
        return $$createType7($result);
    });
}

// Private type creation functions
const $$createType0 = runtime_dto$0.CancelDownloadOutput.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = runtime_dto$0.DownloadNodeOutput.createFrom;
const $$createType3 = $Create.Nullable($$createType2);
const $$createType4 = runtime_dto$0.GetStatusOutput.createFrom;
const $$createType5 = $Create.Nullable($$createType4);
const $$createType6 = runtime_dto$0.MarkDownloadLaterOutput.createFrom;
const $$createType7 = $Create.Nullable($$createType6);
