// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as file_dto$0 from "./file_dto/models.js";

/**
 * OpenFile open a file
 */
export function OpenFile(input: file_dto$0.OpenFileInput): $CancellablePromise<file_dto$0.OpenFileOutput | null> {
    return $Call.ByID(528429392, input).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * SaveTempFile decodes base64 data and writes it to the app temp directory.
 * Returns the absolute file path on success.
 */
export function SaveTempFile(input: file_dto$0.SaveTempFileInput): $CancellablePromise<file_dto$0.SaveTempFileOutput | null> {
    return $Call.ByID(876414915, input).then(($result: any) => {
        return $$createType3($result);
    });
}

/**
 * SelectFile select a file
 */
export function SelectFile(input: file_dto$0.SelectFileInput): $CancellablePromise<file_dto$0.SelectFileOutput | null> {
    return $Call.ByID(2211995752, input).then(($result: any) => {
        return $$createType5($result);
    });
}

/**
 * SelectFolder select a folder
 */
export function SelectFolder(input: file_dto$0.SelectFolderInput): $CancellablePromise<file_dto$0.SelectFolderOutput | null> {
    return $Call.ByID(2775297918, input).then(($result: any) => {
        return $$createType7($result);
    });
}

// Private type creation functions
const $$createType0 = file_dto$0.OpenFileOutput.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = file_dto$0.SaveTempFileOutput.createFrom;
const $$createType3 = $Create.Nullable($$createType2);
const $$createType4 = file_dto$0.SelectFileOutput.createFrom;
const $$createType5 = $Create.Nullable($$createType4);
const $$createType6 = file_dto$0.SelectFolderOutput.createFrom;
const $$createType7 = $Create.Nullable($$createType6);
