// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Agent exposes backend agent operations to the frontend.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as agent_dto$0 from "./agent_dto/models.js";

export function CreateSession(input: agent_dto$0.CreateSessionInput): $CancellablePromise<agent_dto$0.CreateSessionOutput | null> {
    return $Call.ByID(1220427190, input).then(($result: any) => {
        return $$createType1($result);
    });
}

export function DeleteSession(input: agent_dto$0.DeleteSessionInput): $CancellablePromise<agent_dto$0.DeleteSessionOutput | null> {
    return $Call.ByID(3587730355, input).then(($result: any) => {
        return $$createType3($result);
    });
}

export function GenerateTitle(input: agent_dto$0.GenerateTitleInput): $CancellablePromise<agent_dto$0.GenerateTitleOutput | null> {
    return $Call.ByID(965227685, input).then(($result: any) => {
        return $$createType5($result);
    });
}

export function ListSessions(input: agent_dto$0.ListSessionsInput): $CancellablePromise<agent_dto$0.ListSessionsOutput | null> {
    return $Call.ByID(137264783, input).then(($result: any) => {
        return $$createType7($result);
    });
}

export function LoadSessionMessages(input: agent_dto$0.LoadSessionMessagesInput): $CancellablePromise<agent_dto$0.LoadSessionMessagesOutput | null> {
    return $Call.ByID(227823110, input).then(($result: any) => {
        return $$createType9($result);
    });
}

export function MarkSessionRead(input: agent_dto$0.MarkSessionReadInput): $CancellablePromise<agent_dto$0.MarkSessionReadOutput | null> {
    return $Call.ByID(1534226609, input).then(($result: any) => {
        return $$createType11($result);
    });
}

export function RenameSession(input: agent_dto$0.RenameSessionInput): $CancellablePromise<agent_dto$0.RenameSessionOutput | null> {
    return $Call.ByID(3843747644, input).then(($result: any) => {
        return $$createType13($result);
    });
}

export function RespondToConfirm(input: agent_dto$0.RespondToConfirmInput): $CancellablePromise<agent_dto$0.RespondToConfirmOutput | null> {
    return $Call.ByID(1746829762, input).then(($result: any) => {
        return $$createType15($result);
    });
}

export function SendMessage(input: agent_dto$0.SendMessageInput): $CancellablePromise<agent_dto$0.SendMessageOutput | null> {
    return $Call.ByID(1812786987, input).then(($result: any) => {
        return $$createType17($result);
    });
}

/**
 * SpawnTaskSession creates a task session and asynchronously submits its first turn.
 */
export function SpawnTaskSession(input: agent_dto$0.SpawnTaskSessionInput): $CancellablePromise<agent_dto$0.SpawnTaskSessionOutput | null> {
    return $Call.ByID(2875604664, input).then(($result: any) => {
        return $$createType19($result);
    });
}

export function StopGeneration(input: agent_dto$0.StopGenerationInput): $CancellablePromise<agent_dto$0.StopGenerationOutput | null> {
    return $Call.ByID(2535651424, input).then(($result: any) => {
        return $$createType21($result);
    });
}

export function ToggleStarSession(input: agent_dto$0.ToggleStarSessionInput): $CancellablePromise<agent_dto$0.ToggleStarSessionOutput | null> {
    return $Call.ByID(1498792194, input).then(($result: any) => {
        return $$createType23($result);
    });
}

// Private type creation functions
const $$createType0 = agent_dto$0.CreateSessionOutput.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = agent_dto$0.DeleteSessionOutput.createFrom;
const $$createType3 = $Create.Nullable($$createType2);
const $$createType4 = agent_dto$0.GenerateTitleOutput.createFrom;
const $$createType5 = $Create.Nullable($$createType4);
const $$createType6 = agent_dto$0.ListSessionsOutput.createFrom;
const $$createType7 = $Create.Nullable($$createType6);
const $$createType8 = agent_dto$0.LoadSessionMessagesOutput.createFrom;
const $$createType9 = $Create.Nullable($$createType8);
const $$createType10 = agent_dto$0.MarkSessionReadOutput.createFrom;
const $$createType11 = $Create.Nullable($$createType10);
const $$createType12 = agent_dto$0.RenameSessionOutput.createFrom;
const $$createType13 = $Create.Nullable($$createType12);
const $$createType14 = agent_dto$0.RespondToConfirmOutput.createFrom;
const $$createType15 = $Create.Nullable($$createType14);
const $$createType16 = agent_dto$0.SendMessageOutput.createFrom;
const $$createType17 = $Create.Nullable($$createType16);
const $$createType18 = agent_dto$0.SpawnTaskSessionOutput.createFrom;
const $$createType19 = $Create.Nullable($$createType18);
const $$createType20 = agent_dto$0.StopGenerationOutput.createFrom;
const $$createType21 = $Create.Nullable($$createType20);
const $$createType22 = agent_dto$0.ToggleStarSessionOutput.createFrom;
const $$createType23 = $Create.Nullable($$createType22);
