// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as data_models$0 from "../../../models/data_models/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as terminal$0 from "../../../pkg/terminal/models.js";

/**
 * ListTerminalsInput identifies the chat session whose terminals should be loaded.
 */
export class ListTerminalsInput {
    "session_id": number;

    /** Creates a new ListTerminalsInput instance. */
    constructor($$source: Partial<ListTerminalsInput> = {}) {
        if (!("session_id" in $$source)) {
            this["session_id"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ListTerminalsInput instance from a string or object.
     */
    static createFrom($$source: any = {}): ListTerminalsInput {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ListTerminalsInput($$parsedSource as Partial<ListTerminalsInput>);
    }
}

/**
 * ListTerminalsOutput returns terminal metadata for a chat session.
 */
export class ListTerminalsOutput {
    "items": terminal$0.Info[];

    /** Creates a new ListTerminalsOutput instance. */
    constructor($$source: Partial<ListTerminalsOutput> = {}) {
        if (!("items" in $$source)) {
            this["items"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ListTerminalsOutput instance from a string or object.
     */
    static createFrom($$source: any = {}): ListTerminalsOutput {
        const $$createField0_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("items" in $$parsedSource) {
            $$parsedSource["items"] = $$createField0_0($$parsedSource["items"]);
        }
        return new ListTerminalsOutput($$parsedSource as Partial<ListTerminalsOutput>);
    }
}

/**
 * ReadTerminalOutputInput identifies the terminal and cursor to read from.
 */
export class ReadTerminalOutputInput {
    "terminal_id": string;
    "cursor": number;

    /** Creates a new ReadTerminalOutputInput instance. */
    constructor($$source: Partial<ReadTerminalOutputInput> = {}) {
        if (!("terminal_id" in $$source)) {
            this["terminal_id"] = "";
        }
        if (!("cursor" in $$source)) {
            this["cursor"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ReadTerminalOutputInput instance from a string or object.
     */
    static createFrom($$source: any = {}): ReadTerminalOutputInput {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ReadTerminalOutputInput($$parsedSource as Partial<ReadTerminalOutputInput>);
    }
}

/**
 * ReadTerminalOutputOutput returns terminal output chunks after the cursor.
 */
export class ReadTerminalOutputOutput {
    "chunks": terminal$0.TerminalOutputChunk[];

    /** Creates a new ReadTerminalOutputOutput instance. */
    constructor($$source: Partial<ReadTerminalOutputOutput> = {}) {
        if (!("chunks" in $$source)) {
            this["chunks"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ReadTerminalOutputOutput instance from a string or object.
     */
    static createFrom($$source: any = {}): ReadTerminalOutputOutput {
        const $$createField0_0 = $$createType3;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("chunks" in $$parsedSource) {
            $$parsedSource["chunks"] = $$createField0_0($$parsedSource["chunks"]);
        }
        return new ReadTerminalOutputOutput($$parsedSource as Partial<ReadTerminalOutputOutput>);
    }
}

/**
 * ResizeTerminalInput carries the current frontend terminal dimensions.
 */
export class ResizeTerminalInput {
    "terminal_id": string;
    "rows": number;
    "cols": number;

    /** Creates a new ResizeTerminalInput instance. */
    constructor($$source: Partial<ResizeTerminalInput> = {}) {
        if (!("terminal_id" in $$source)) {
            this["terminal_id"] = "";
        }
        if (!("rows" in $$source)) {
            this["rows"] = 0;
        }
        if (!("cols" in $$source)) {
            this["cols"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ResizeTerminalInput instance from a string or object.
     */
    static createFrom($$source: any = {}): ResizeTerminalInput {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ResizeTerminalInput($$parsedSource as Partial<ResizeTerminalInput>);
    }
}

/**
 * ResizeTerminalOutput acknowledges that the resize request was handled.
 */
export class ResizeTerminalOutput {

    /** Creates a new ResizeTerminalOutput instance. */
    constructor($$source: Partial<ResizeTerminalOutput> = {}) {

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ResizeTerminalOutput instance from a string or object.
     */
    static createFrom($$source: any = {}): ResizeTerminalOutput {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ResizeTerminalOutput($$parsedSource as Partial<ResizeTerminalOutput>);
    }
}

/**
 * WriteTerminalInputInput carries user input destined for an active terminal.
 */
export class WriteTerminalInputInput {
    "terminal_id": string;
    "data": string;

    /** Creates a new WriteTerminalInputInput instance. */
    constructor($$source: Partial<WriteTerminalInputInput> = {}) {
        if (!("terminal_id" in $$source)) {
            this["terminal_id"] = "";
        }
        if (!("data" in $$source)) {
            this["data"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new WriteTerminalInputInput instance from a string or object.
     */
    static createFrom($$source: any = {}): WriteTerminalInputInput {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new WriteTerminalInputInput($$parsedSource as Partial<WriteTerminalInputInput>);
    }
}

/**
 * WriteTerminalInputOutput acknowledges that terminal input was accepted.
 */
export class WriteTerminalInputOutput {

    /** Creates a new WriteTerminalInputOutput instance. */
    constructor($$source: Partial<WriteTerminalInputOutput> = {}) {

        Object.assign(this, $$source);
    }

    /**
     * Creates a new WriteTerminalInputOutput instance from a string or object.
     */
    static createFrom($$source: any = {}): WriteTerminalInputOutput {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new WriteTerminalInputOutput($$parsedSource as Partial<WriteTerminalInputOutput>);
    }
}

// Private type creation functions
const $$createType0 = terminal$0.Info.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = data_models$0.TerminalOutputChunk.createFrom;
const $$createType3 = $Create.Array($$createType2);
